### ISSUE TITLE
What does "build_stubbed" means?

### ISSUE THREAD

**Issue by jeffrey008** [thoughtbot/factory_bot#1004]
Hello, I am new to `factory_girl`. Sorry if I asked some stupid question.

In `GETTING_STARTED.md`, there is one thing called `build_stubbed`.
```ruby
# Returns an object with all defined attributes stubbed out
stub = build_stubbed(:user)
```
The comment is not really helpful, can anyone please explain more about this? Perhaps we can update the readme to help out people to understand too.

**Comment by Thomascountz** [comment]
Check out more here: [_Use Factory Girl's build_stubbed for a Faster Test Suite_](https://robots.thoughtbot.com/use-factory-girls-build-stubbed-for-a-faster-test)

> build_stubbed is the younger, more hip sibling to build; it instantiates and assigns attributes just like build, but that’s where the similarities end. It makes objects look look _[sic]_ like they’ve been persisted, creates associations with the build_stubbed strategy (whereas build still uses create), and stubs out a handful of methods that interact with the database and raises if you call them. This leads to much faster tests and reduces your test dependency on a database.
