### ISSUE TITLE
FactoryGirl assigning attribute to parent's method param

### ISSUE THREAD

**Issue by stevenspiel** [thoughtbot/factory_bot#1037]
```rb
FactoryGirl.define do
  factory :potato do
    association :food_group, factory: :vegetable, method: :build
  end
end

build(:potato)
```

I'm getting ```undefined method `method=' for #<Vegetable...```

`method` should be specifying the persistence of the parent object, not an attribute of the parent object. Perhaps it's because it's a polymorphic association? I've tried rearranging the options hashes with no luck. 

`association :food_group, { factory: :vegetable }, method: :build`
`association :food_group, { factory: :vegetable, method: :build }`

Is this not supported anymore. Using `3.5.0`

Additional setup below if you're interested:

```rb
class Potato < ActiveRecord::Base
  belongs_to :food_group, polymorphic: true
end

class Vegetable < ActiveRecord::Base
end

FactoryGirl.define do
  factory :potato do
    association :food_group, factory: :vegetable, method: :build
  end

  factory :vegetable do
    tastiness { 5 }
  end
end

build(:potato)
```

**Comment by composerinteralia** [comment]
I think you might mean 'strategy: build' rather than 'method: build'. See https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#associations
