### ISSUE TITLE
How to generate different attributes everytime

### ISSUE THREAD

**Issue by poc7667** [thoughtbot/factory_bot#1047]
In my code , the 100 stores are sharing the same attributes.

I thought it should create a different one every time.

	(1..100).each do
	  store_attr = FG.attributes_for :store
	  store_attr[:account] = accounts.sample
	  stores << Store.create(store_attr)
	end

	FactoryGirl.define do
	  factory :store do
	    name Faker::Company.name
	    latitude 1.5
	    longitude 1.5
	    street Faker::Address.street_address
	    city Faker::Address.city
	    state Faker::Address.state
	    zip_code Faker::Address.zip_code
	    phone Faker::PhoneNumber.cell_phone
	    email Faker::Internet.email
	    website "https://#{Faker::Internet.domain_name}"
	    account nil
	    factory :complete_store do
	      name 'store_with_account'
	      account
	    end
	  end
	end

**Comment by composerinteralia** [comment]
I think you are looking for [dynamic attributes](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#dynamic-attributes), which can be added by passing a block:

```rb
name { Faker::Company.name }
```

You are not the first person to have had this question. Read [this issue](https://github.com/thoughtbot/factory_girl/issues/592) if you are curious.
