### ISSUE TITLE
Rename of FactoryGirl to FactoryBot has broken my projects

### ISSUE THREAD

**Issue by iHiD** [thoughtbot/factory_bot#1055]
This is a duplicate of the [same issue on factory_bot_rails](https://github.com/thoughtbot/factory_bot_rails/issues/243) but I thought it was worth duplicating so others can find it.

----

> Hello. Sorry for the slightly dramatic issue title, but I couldn't find a gentler way to say it :)

> Running bundle update and running tests now gives:
> ```NameError: uninitialized constant ActionView::TestCase::FactoryGirl```

> Renaming FactoryGirl to FactoryBot everywhere in my code fixes the issue, but I think such a breaking change should result in a Major version increment, not a Patch increment. I would suggest reverting the 4.8 branch to factory_girl and release 5.0 as factory_bot.

**Comment by S-hack** [comment]
What is the motivation for the change? It's a huge inconvenience and... seems a bit sexist.

**Comment by iHiD** [comment]
> What is the motivation for the change?

The logic for the change is covered in #921 and related discussions linked from there.

>  It's a huge inconvenience and... seems a bit sexist.

The correctness or not of the change itself is not the point on this issue. This is purely about whether the knock on effect of the fact this was done via a patch version change, rather than as a major release.

**Comment by markprzepiora** [comment]
Definitely should have been a major version change (unless backwards-compatible aliases were included).

But come on guys, this isn't rocket science.

    ag -0l FactoryGirl spec | xargs -0 sed -i 's/FactoryGirl/FactoryBot/g'

It's pretty obvious that a lot of people complaining about this change are just on some anti-feminism crusade.

**Comment by iHiD** [comment]
> But come on guys, this isn't rocket science.

Totally agree that fixing it is a 2min job.

However, it's totally unexpected to run `bundle update` and find your test-suite break. It took me as an experienced developer 10mins to work out why FactoryGirl suddenly failed and understand what was going on, etc. Less experienced developers will be totally stumped for significantly longer than that. Therefore, I think this is something that should be reversed on this branch and released onto a major branch.

What is not rocket science for you and me may well feel like rocket science to a beginner who started programming more recently.

> It's pretty obvious that a lot of people complaining about this change are just on some anti-feminism crusade.

Agreed.

**Comment by markprzepiora** [comment]
> However, it's totally unexpected to run bundle update and find your test-suite break. It took me as an experienced developer 10mins to work out why FactoryGirl suddenly failed and understand what was going on, etc. Less experienced developers will be totally stumped for significantly longer than that. Therefore, I think this is something that should be reversed on this branch and released onto a major branch.

Agreed completely. Or add aliases that issue a deprecation warning.

**Comment by Euraldius** [comment]
Hey! Sorry for the trouble this is causing; we didn't expect it to be a breaking change. The intended behavior is that you see a deprecation warning when you run the test suite. We're investigating now.

**Comment by iHiD** [comment]
Thanks @Euraldius

The issue is that defining factories or including in test suites uses the FactoryGirl constant so now that constant is missing, all the consuming code breaks. If you want anyone to pair with on it, feel free to email me :)

**Comment by schneems** [comment]
Wanted to chime in and say I like the name change. I’ve also written a bunch on versioning and deprecations. In the future I think these might be of some use:

- https://www.schneems.com/2015/11/29/what-is-semver.html
- https://blog.codeship.com/the-straight-dope-on-deprecations/

**Comment by joshuaclayton** [comment]
@schneems thanks for the support, and those are a solid reminder. We'd tested this on a number of projects both internal and external to thoughtbot (e.g. client projects) and for each where we'd locked to `~> 4.8.0`, the extent of the impact was a couple of deprecation warnings (which we expected!), but a fully green suite.

We'd introduced https://github.com/thoughtbot/factory_bot/blob/master/lib/factory_girl.rb#L3 to effectively alias constants, but that doesn't seem to have been enough.

In the meantime, we've yanked version 4.8.2 of both `factory_girl` and `factory_girl_rails` to prevent further issues.

For those who've installed 4.8.2 of the gems, you can uninstall them with:

```sh
gem uninstall factory_girl --version 4.8.2
gem uninstall factory_girl_rails --version 4.8.2
```

You may also want to lock your Gemfile to `"4.8.1"` for the time being.

**Comment by Euraldius** [comment]
Note: you can use `factory_bot` and `factory_bot_rails` if you want to - those should be working. (The only change you'll need to make is the rename.) I'll add a note in the README about that

**Comment by iHiD** [comment]
@joshuaclayton @Euraldius Thanks for the quick action.

I've put a sample repo together for you that shows the problems I'm getting [here](https://github.com/iHiD/bots_not_girls/commits/master). It has 3 commits - a boilerplate Rails app. the addition of factory_girl_rails 4.8.0 and then the change to master. 

After commit 2 I get:
<img width="440" alt="screen shot 2017-10-21 at 20 02 51" src="https://user-images.githubusercontent.com/286476/31855079-2fb9b09e-b69b-11e7-9051-71b2877dac9d.png">

After commit 3 I get:
<img width="913" alt="screen shot 2017-10-21 at 20 02 32" src="https://user-images.githubusercontent.com/286476/31855081-35ccd63c-b69b-11e7-825e-494be32342ce.png">

(`bert` = `bundle exec rake test`)

These are different errors to the one I get in real projects, which is `NameError: uninitialized constant ActionView::TestCase::FactoryGirl` - I can't reproduce that in this boilerplate app, it just fails to load the tests instead. So there seem to be a couple of issues in there somewhere. I've noticed that this release also packages previous commits as well as the FactoryGirl rename, so something else might be responsible for this bit.

Thanks again for your hard work on this. Let me know if I can be of help in testing anything.

**Comment by iHiD** [comment]
Final note. If I remove `factory_girl` from being explicit in the Gemfile (and just have `factory_girl_rails` at either `4.8.2` or `master`), I get the original `uninitialized constant ActionView::TestCase::FactoryGirl`. So I wonder if that is to do with how `factory_girl_rails` is loading `factory_girl` implicitly, and whether the constant is no longer auto-loaded or something.

**Comment by songsta** [comment]
I think I'm also suffering from this change, although I'm pretty much a noob, so might be wrong.

I'm trying to get cucumber to run with FactoryBot but when I follow the instructions in the "Getting Started"

```
# env.rb (Rails example location - RAILS_ROOT/features/support/env.rb)
World(FactoryBot::Syntax::Methods)

```
I end up with 

 `uninitialized constant FactoryBot (NameError)`

**Comment by tcpj** [comment]
Thanks @tastycode

**Comment by quangv** [comment]
@tcpj sensing sarcasm in your comment...

Yes! Thank you @tastycode and 👏 ThoughtBot, especially @joshuaclayton and @Euraldius for leading the heroic efforts. 👍

**Comment by nukeop** [comment]
Great! We don't want any girls in our code.

**Comment by tcpj** [comment]
> sensing sarcasm in your comment...

Sensing right. This guy is having bad times because some SJW got offended.

**Comment by joshuaclayton** [comment]
@iHiD Thanks for your help here! I'll dig into your example repo, and see how it differs from some of the internal projects we've been running this on (without changing to `FactoryBot`) with success. The alias (https://github.com/thoughtbot/factory_bot/blob/c716ce01b448ce4e0bf855c5a2c63ecb9206322e/lib/factory_girl.rb#L3) doesn't seem to "stick" in certain situations, resulting in the `uninitialized constant` issues you're able to produce.

**Comment by tvw** [comment]
It is dead simple. When the consuming code needs to be changed, it is major version change.

See semver.org:

"1. MAJOR version when you make incompatible API changes"

Changing the namespace is an incompatible API change.

**Comment by mjankowski** [comment]
We have yanked version 4.8.2 which broke code for people - we apologize for the issues.

Version 4.9.0 is out with nothing but a deprecation warning.

We will have a blog post explaining the whole change along with upgrade instructions in the near future.

**Comment by iHiD** [comment]
@mjankowski Thank you for dealing with this so promptly. 

I'm closing this. Could you lock it once I have please as I suspect the ongoing comments from people hit by this will not be particularly helpful... :)

**Comment by mjankowski** [comment]
Blog post now up: https://robots.thoughtbot.com/factory_bot
