### ISSUE TITLE
Link to name change explanation redirects back to new repository URL

### ISSUE THREAD

**Issue by jellymann** [thoughtbot/factory_bot#1060]
I was curious to read more about the recent name change, and I saw that there is a link to "An explanation of the name" in the README. However, when I clicked on it, it just redirected me back to the new factory_bot repository.

**Comment by coisnepe** [comment]
Perhaps it linked to [this commit](https://github.com/thoughtbot/factory_bot/commit/903d4325feb9c373863601cdab3fca4b6118fca7#diff-04c6e90faac2675aa89e2176d2eec7d8), which introduced [NAME.md](https://github.com/thoughtbot/factory_bot/blob/master/NAME.md)?

**Comment by jellymann** [comment]
@coisnepe No, I'm referring to change here: https://github.com/thoughtbot/factory_bot/pull/1051/files#diff-04c6e90faac2675aa89e2176d2eec7d8R8

The issue was pointed out in a comment there, but was not addressed.

**Comment by mjankowski** [comment]
Yes - that explanation precedes the recent name change, and was intended to explain the old ("girl") naming for people who were confused by it.

We can probably remove that section of the readme, and that whole explanation file now. We could also consider expanding that file to give a more full historical accounting of the original naming and the ongoing change to bot.

**Comment by quangv** [comment]
seems related to https://github.com/thoughtbot/factory_bot/pull/1056
