### ISSUE TITLE
Make the repository completely gender neutral

### ISSUE THREAD

**Issue by Circuit8** [thoughtbot/factory_bot#1067]
I already suggested this change in #1066 but my pull request and issue were closed without any reason.

If we're aiming at removing any reference to gender in the repository (as we clearly are as the name was changed from factory_girl to factory_bot) then we should remove all the references to John in the code aswell (lots of examples use `John Doe`).

This would actually be a much more straightforward change than renaming the entire repository and breaking thousands of peoples code, all you would have to do is merge my pull request #1065 , and the repository would be slightly less offensive, which is obviously really important to us now.

Please don't just close this issue without responding to my points and allowing a fair discussion.

**Comment by promoderates** [comment]
I cant comment for thoughtbot or @joshuaclayton. I agree to the change. Many people agree that john promotes a male-dominated culture. Also john has other meanings. It means toilet. There is a problem with the name you chose. It follows the theme but not real. Robots do not have 'human' sernames. Not sure why they didnt tell you this. Maybe change that? Then they can accept.

**Comment by Circuit8** [comment]
@promoderates Good point. I'll change all `doe` references in the code to a similar string. Would be great if we can look at getting this merged once I've done that.

**Comment by mjankowski** [comment]
Your point has been made. Please move on.

**Comment by Circuit8** [comment]
@mjankowski I'm sorry but that seems rather unfair. Why is it that one persons definition of what is offensive is being favoured over someone elses? 

If we're prepared to change the actual name of the gem, why not make this much smaller change?

**Comment by mjankowski** [comment]
We are favoring our definition of what's offensive because it's our project, hence our judgement is most relevant here. I feel ok about this and consider it not only fair, but well earned.

I accept your right to disagree with us, and such disagreement has been noted!

Again, please move on.

**Comment by Circuit8** [comment]
Well if there is an issue with having the use of a gendered name in the title of the project, then surely you should have an issue with having gendered names within the project itself.

I'm confused as by your own logic this ought to offend you.

**Comment by mjankowski** [comment]
> Well if there is an issue with having the use of a gendered name in the title of the project,

There is an issue, we've described it in lots of places, including multiple project issues and PRs and a blog post. It's not so much a gendered name as it literally a name for a gender being assigned to something (a software library) which does not have a gender.

> then surely you should have an issue with having gendered names within the project itself.

We don't. They're pretty benign examples where something which has a gender is given a name commonly associated with one; and even better, the name they are given is a pretty common pattern when you have a case of "I want to use a generic name here to make the point that it doesn't matter who the actual person is and this is just some stand-in data".

> I'm confused as by your own logic this ought to offend you.

Your confusion has been noted. Please move on.
