### ISSUE TITLE
Setting an  X_id value in FactoryBot that isn't a foreign key doesn't always work right

### ISSUE THREAD

**Issue by drsharp** [thoughtbot/factory_bot#1096]
I ran into this problem recently. I posted a SO post and got a good answer, but they recommended I also post it as an issue here because it may be fixable or there may be a different, recommended approach.

The short of it is:

If I have two attributes on my model, call them `feature` and `feature_id` but they are NOT references to some other model (like `Feature`) and instead are just text strings in the DB... FactoryBot seems to try to do some Rails introspection wizardry with them.

For a full write-up, see: [How do I set an _id value in FactoryBot that isn't a foreign key?](https://stackoverflow.com/questions/48179555/how-do-i-set-an-id-value-in-factorybot-that-isnt-a-foreign-key) or read on below:

-------------

I have a model that looks like this via the schema (stripped down to just the relevant stuff):

    create_table "items", force: :cascade do |t|
        t.text "team"
        t.text "feature_id"
        t.text "feature"
        t.timestamps
    end

However, `feature_id` and `feature` are NOT references to a feature object... they are just strings.

I've defined my factory like this:

    FactoryBot.define do
      factory :item do
        team "TheTeam"
        sequence(:feature_id) {|n| "Feature#{n}" }
        feature { Faker::Lorem.sentence }
      end
    end

And the simple case works:

    > FactoryBot.create(:item)
    => #<Item:0x007fad8cbfc048
     id: 1,
     team: "TheTeam",
     feature_id: "Feature1",
     feature: "Qui voluptatem animi et rerum et.",
     created_at: Wed, 10 Jan 2018 02:40:01 UTC +00:00,
     updated_at: Wed, 10 Jan 2018 02:40:01 UTC +00:00>

But when I want to specify my own `feature_id` this is what happens:

    > FactoryBot.create(:item, feature_id: "123")
    => #<Item:0x007fad8d30a880
     id: 2,
     team: "TheTeam",
     feature_id: "123",
     feature: nil,
     created_at: Wed, 10 Jan 2018 02:40:59 UTC +00:00,
     updated_at: Wed, 10 Jan 2018 02:40:59 UTC +00:00>

You can see that `feature` is now `nil`. I'm assuming this is because it's trying to infer that `feature_id` and `feature` are somehow related. But in this case, I don't want them to be.

**Is there a better way to define the factory so that it just treats them as unrelated fields?**

BTW, if I try to set both the `feature_id` and `feature` it looks like this:

    > FactoryBot.create(:item, feature_id: "123", feature: "hi")
    => #<Item:0x007fad8d262810
     id: 3,
     team: "TheTeam",
     feature_id: nil,
     feature: nil,
     created_at: Wed, 10 Jan 2018 02:45:01 UTC +00:00,
     updated_at: Wed, 10 Jan 2018 02:45:01 UTC +00:00>

So it just sets both fields to `nil`. I suspect FactoryBot is trying to be "smart" about these fields based on their names. I'd change them but they are already set that way in the Db.

**Comment by drsharp** [comment]
I'm using FactoryBot (formerly FactoryGirl) to create some factory data for my tests. I have a model that looks like this via the schema (stripped down to just the relevant stuff):

    create_table "items", force: :cascade do |t|
        t.text "team"
        t.text "feature_id"
        t.text "feature"
        t.timestamps
    end

However, `feature_id` and `feature` are NOT references to a feature object... they are just strings.

I've defined my factory like this:

    FactoryBot.define do
      factory :item do
        team "TheTeam"
        sequence(:feature_id) {|n| "Feature#{n}" }
        feature { Faker::Lorem.sentence }
      end
    end

And the simple case works:

    > FactoryBot.create(:item)
    => #<Item:0x007fad8cbfc048
     id: 1,
     team: "TheTeam",
     feature_id: "Feature1",
     feature: "Qui voluptatem animi et rerum et.",
     created_at: Wed, 10 Jan 2018 02:40:01 UTC +00:00,
     updated_at: Wed, 10 Jan 2018 02:40:01 UTC +00:00>

But when I want to specify my own `feature_id` this is what happens:

    > FactoryBot.create(:item, feature_id: "123")
    => #<Item:0x007fad8d30a880
     id: 2,
     team: "TheTeam",
     feature_id: "123",
     feature: nil,
     created_at: Wed, 10 Jan 2018 02:40:59 UTC +00:00,
     updated_at: Wed, 10 Jan 2018 02:40:59 UTC +00:00>

You can see that `feature` is now `nil`. I'm assuming this is because it's trying to infer that `feature_id` and `feature` are somehow related. But in this case, I don't want them to be.

**Is there a better way to define the factory so that it just treats them as unrelated fields?**


BTW, if I try to set both the `feature_id` and `feature` it looks like this:

    > FactoryBot.create(:item, feature_id: "123", feature: "hi")
    => #<Item:0x007fad8d262810
     id: 3,
     team: "TheTeam",
     feature_id: nil,
     feature: nil,
     created_at: Wed, 10 Jan 2018 02:45:01 UTC +00:00,
     updated_at: Wed, 10 Jan 2018 02:45:01 UTC +00:00>

So it just sets both fields to `nil`. I suspect FactoryBot is trying to be "smart" about these fields based on their names. I'd change them but they are already set that way in the Db.

**Comment by composerinteralia** [comment]
You could try using transient attributes, which I don't think use the ActiveRecord-specific aliasing:

```rb
factory :item do
  team "TheTeam"

  transient do
    sequence(:feature_id) { |n| "Feature#{n}" }
    feature { Faker::Lorem.sentence }
  end

  after(:build) do |item, evaluator|
    item.feature_id = evaluator.feature_id
    item.feature = evaluator.feature
  end
end
```

**Comment by composerinteralia** [comment]
Closing in favor of #1142
