### ISSUE TITLE
Upgrade guide grep command doesn't work when multiple usages on same line

### ISSUE THREAD

**Issue by ezpuzz** [thoughtbot/factory_bot#1104]
Your command in https://github.com/thoughtbot/factory_bot/blob/4-9-0-stable/UPGRADE_FROM_FACTORY_GIRL.md only handles single instances of `FactoryBot` per line

**Comment by rdunlop** [comment]
@ezpuzz I dealt with this in https://github.com/thoughtbot/factory_bot/pull/1107....but I've had no takers to actually review/merge it.

**Comment by composerinteralia** [comment]
Seems to have been resolved: https://github.com/thoughtbot/factory_bot/pull/1107#issuecomment-389025611
