### ISSUE TITLE
Easy to accidentally load spec/support/factory_bot.rb twice

### ISSUE THREAD

**Issue by jarvisjohnson** [thoughtbot/factory_bot#1106]
I came across the error of my factories being loaded twice because I was requiring `FactoryBot::Syntax::Methods` twice.

It's pretty easy to do by adding the whole snippet below in the Getting Started guide. ([A few others have noted on SO](https://stackoverflow.com/questions/9300231/factory-already-registered-user-factorygirlduplicatedefinitionerror/#answer-41080111))

```ruby 
# spec/support/factory_bot.rb
RSpec.configure do |config|
  config.include FactoryBot::Syntax::Methods
end

# RSpec without Rails
RSpec.configure do |config|
  config.include FactoryBot::Syntax::Methods

  config.before(:suite) do
    FactoryBot.find_definitions
  end
end
```

I've created [a quick PR](https://github.com/thoughtbot/factory_bot/pull/1105) to clarify a bit, would love if you guys could take a look!

**Comment by composerinteralia** [comment]
Closed by 8ad9cb1d716016c18c7fb349b32e474bb0aa4d94. Thanks!
