### ISSUE TITLE
Please clarify the release policy

### ISSUE THREAD

**Issue by ge-fa** [thoughtbot/factory_bot#1108]
Hi all,

As per the rename, I would like to package factory_bot for Debian. However, I'm confused:

- The tag `v4.8.2`, 2017/10/20, contained factory_bot.
- The tag `v4.9.0`, 2017/10/23, contained factory_girl.

Normally, for Debian packaging, a so called "watch" file is used, to check for the latest upstream release.
But in this case, this doesn't work properly, as the latest release is not about factory_bot, but about factory_girl.

Could you please clarify, what to expect in the future? In case there are further releases planned for factory_girl, would it be possible to use different release naming schemes for girl vs bot?

Thanks for your work and all the best!

**Comment by sciros** [comment]
Seconded. Please create a new tag to reconcile the latest version with the latest gem name.

**Comment by mikegee** [comment]
Since there have been so many issues with people confused by these versions, maybe the few changes in master can be released now as factory_bot 4.9.1 to reduce the noise?

**Comment by odlp** [comment]
Apologies for the confusion here. I've just released / tagged `factory_bot` and `factory_bot_rails` version `4.10.0`, which includes the rewind sequences feature.

Please feel free to reopen this hasn't resolved the issue.
