### ISSUE TITLE
factory_bot older than factory_girl

### ISSUE THREAD

**Issue by uplus** [thoughtbot/factory_bot#1109]
![image](https://user-images.githubusercontent.com/10358398/36466983-f582bf7a-171f-11e8-8a69-567474ee99ae.png)

Please update factory_bot :pray:

**Comment by mikegee** [comment]
[The diff](https://github.com/thoughtbot/factory_bot/compare/v4.8.2...v4.9.0) is only deprecation warnings and upgrade instructions.

**Comment by uplus** [comment]
I see. Thanks!
