### ISSUE TITLE
Kowtowing to PC Nonsense Erases History of Women's Lib

### ISSUE THREAD

**Issue by CodingAnarchy** [thoughtbot/factory_bot#1110]
Lowell, Massachusetts, named in honor of Francis Cabot Lowell, was founded in the early 1820s as a planned town for the manufacture of textiles. It introduced a new system of integrated manufacturing to the United States and established new patterns of employment and urban development that were soon replicated around New England and elsewhere.

By 1840, the factories in Lowell employed at some estimates more than 8,000 textile workers, commonly known as mill girls or _factory girls_. These "operatives"—so-called because they operated the looms and other machinery—were primarily women and children from farming backgrounds.

The Lowell mills were the first hint of the industrial revolution to come in the United States, and with their success came two different views of the factories. **For many of the mill girls, employment brought a sense of freedom. Unlike most young women of that era, they were free from parental authority, were able to earn their own money, and had broader educational opportunities. Many observers saw this challenge to the traditional roles of women as a threat to the American way of life.**

Changing the name to `FactoryBot` erased this connection to history and the first liberation of women from the strict gender roles of the home.  Feminism has gone full circle with this nonsense.

It saddens me that you changed the name to erase this history.

**Comment by mjankowski** [comment]
Noted, thanks.
