### ISSUE TITLE
Dealing with naming collisions in the factory definition DSL

### ISSUE THREAD

**Issue by RickCarlino** [thoughtbot/factory_bot#1111]
Hi folks!

I've been using FactoryBot for years. I have a model in my app with [the unfortunate name of "sequence.rb"](https://github.com/FarmBot/Farmbot-Web-App/blob/staging/app/models/sequence.rb#L5).

Anytime I want to create a factory that `belongs_to :sequence`...
```
FactoryBot.define do
  factory :sequence_thing do
    device # belongs to Device model
    sequence # Also belongs to Sequence model
  end
end

```
...I get the following error:

```
....../gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:122:in `sequence': wrong number of arguments (given 0, expected 1+) (ArgumentError)
```

I assume that FactoryBot _thinks_ I am trying to initiate a [sequence](http://www.rubydoc.info/gems/factory_bot/file/GETTING_STARTED.md#Sequences) and forgot to pass a block/args. That's not what I'm trying to do though. I am trying to instantiate a `sequence_thing` that has a `Sequence`.

Is there any way around the apparent naming collision aside from renaming the table?

Thanks for all the hard work everyone has put into maintaining this tool.

**Comment by joshuaclayton** [comment]
@RickCarlino as a quick sanity check, can you give this a whirl?

```ruby
factory :sequence_thing do
  # ...
  association :sequence
end
```

**Comment by RickCarlino** [comment]
:tada: That fixed it! Thanks @joshuaclayton
