### ISSUE TITLE
Not working with Ruby 2.5.0

### ISSUE THREAD

**Issue by ug0** [thoughtbot/factory_bot#1114]
I got these issues in my rails project(Rails 5.2.0.rc1, Ruby 2.5.0) using this gem.

1. Running tests got `uninitialized constant ActiveSupport::TestCase::FactoryBot (NameError)`
2. In the rails console, `FactoryBot` is not available(`uninitialized constant FactoryBot`).
3. Generating new model won't automatically generate factories(factories/*.rb).

Everything is working fine after I downgrade to Ruby 2.4.2.

I also created a [repo](https://github.com/ug0/factory_bot_issue) which could reproduce all the errors.

**Comment by mikegee** [comment]
How do I duplicate the problem? I cloned the repo, bundled and tried `bin/rails test`.

**Comment by ug0** [comment]
@mikegee It's strange. I tested this on another computer and I couldn't reproduce it either. However, I did encounter this problem at my workplace. I guess it's because of the operating system or some libraries? I'll check this again to see if I can find more info next Monday.

**Comment by ug0** [comment]
I'm still getting errors on the particular computer. But my colleague didn't get anything wrong with this repo. I'm closing this issue as I think it's nothing related to this gem.

**Comment by vmarquet** [comment]
Got the 

```
uninitialized constant ActiveSupport::TestCase::FactoryBot (NameError)
```

error, stopping spring solved it:

```
bin/spring stop
```

**Comment by ianaverno** [comment]
@ug0 Have you managed to resolve this for your local env?
Having the same issue with my local env with 2.6.6. 
CI builds pass, but I can't run them locally because of `uninitialized constant FactoryBot`
Since CI passes, I believe requiring explicitly isn't necessary (and never was prior to ruby and rails update)
