### ISSUE TITLE
Feature / Question after block callback support

### ISSUE THREAD

**Issue by aaronbhansen** [thoughtbot/factory_bot#1116]
Looking through the documentation and code, I was trying to find a way to have a callback after a block has completed. The example Would be this:

```
create(:order, date: '1/1/2018') do |order|
  create(:order_line, order: order, item: product1)
  create(:order_line, order: order, item: product2)
end
```

What I'm looking for is a callback after the order and its block has been called. I need to have some data calculated, but only once the order lines have been created on the order. The `after(:create)` callback on the order is too soon, and adding a callback for `after(:create)` on the order lines feel like the wrong place to put the concern and it would be called multiple times.

Essentially
```
create(:order, date: '1/1/2018') do |order|
  # after(:create) for the order has been called
  create(:order_line, order: order, item: product1)
  create(:order_line, order: order, item: product2)
end
# after(:block) for the order is called once everything within the block has finished
# Now run some after code that takes into consideration everything on the order and its children
```

Is that something that would be possible today?

**Comment by composerinteralia** [comment]
Nope, there is no callback available at that point. The callbacks are all triggered while going through the build strategy. At this point the object is done being built, so there are no more callbacks to trigger.

Perhaps you could move the creation of `order_line`s into the `after_create` callback. If you need a variable number of them, you could perhaps set that with a transient attribute. Then you would be able to do whatever else you need to do at the end of the `after_create` callback.
