### ISSUE TITLE
build_stubbed hardcoded IDs can overlap with previously-used database IDs 

### ISSUE THREAD

**Issue by lupine** [thoughtbot/factory_bot#1117]
Per https://gitlab.com/gitlab-org/gitlab-ee/issues/5461#note_65473777 and https://github.com/thoughtbot/factory_bot/blob/master/lib/factory_bot/strategy/stub.rb#L4

`build_stubbed` populates the `id` field with a hardcoded value starting at 1000 and incrementing monotonically from there. There's no way to customize it.

Our specs write stuff to the filesystem based on project ID, and take pains (using transactions and the delete strategy) to ensure that no ID is reused during the course of a spec run. It's not perfect, but means the filesystem activity doesn't cause inter-test problems... unless we've used `build_stubbed(:project)` and then created a thousand real projects afterwards!

From my reading, `build_stubbed` objects aren't supposed to ever touch the database, so what do you think to simply increasing the starting ID to an infeasibly large integer? Starting at 2^64 would put conflicts out of reach.

Adding an interface to customise the start number would be fine too.

While we're there, `@@next_id += 1` is subject to race conditions, although it's rare for specs to be multi-threaded. Might be worth fixing at the same time, though.

I'm happy to submit a PR for this, but I wanted to get agreement on the correct way forward before submitting one! WDYT?

**Comment by composerinteralia** [comment]
https://github.com/thoughtbot/factory_bot/pull/1002

**Comment by ms-liz-zhang** [comment]
I've also taken a crack at this issue. My approach was to stub the associations on the parent object so that the database is never hit in the first place: https://github.com/thoughtbot/factory_bot/pull/1363

**Comment by composerinteralia** [comment]
Merged https://github.com/thoughtbot/factory_bot/commit/65e64ec2a313c67e5f0c63c4afb96234f045b92e
