### ISSUE TITLE
Factory Bot Vs Factory Bot Rails

### ISSUE THREAD

**Issue by nathantech2005** [thoughtbot/factory_bot#1118]
The two different names for the gem name are causing problems. My install works fine until I migrate to the new name from factory girl. Using the factory_bot name without rails added to it causes the install to break. Does anyone know why there's two different names for the same gem. It's not providing any redundant fail safe. It's actually adding to complexity and causing possible problems like this.

**Comment by mikegee** [comment]
factory_bot_rails adds Rails integration to factory_bot, they aren't the same gem.

**Comment by nathantech2005** [comment]
Ah ok. Not sure what factory bot gem does on its own without rails? The
tutorials all over the internet are wrong.
