### ISSUE TITLE
Method 'generate' don't accept params when it in trait in hash. 

### ISSUE THREAD

**Issue by HooFoo** [thoughtbot/factory_bot#1119]
When it called in a hash for Postgres json field mock method 'generate' raise ArgumentError.
Example:
```
FactoryBot.define do
  factory :with_json do
    data {
      {
        data_field: generate(:string)
      }
    }
    trait :special do
    data {
      {
        data_field: generate(:string) # this raise ArgumentError
      }
    }
    end
  end
end
```

**Comment by composerinteralia** [comment]
It looks like you never defined the sequence, so I would expect `ArgumentError: Sequence not registered: string`.

I'm going to close for now, but feel free to open if you got a different error. I would need a bit more context on what went wrong. A reproduction script or sample repo demonstrating the bug would be most helpful.
