### ISSUE TITLE
`FactoryBot.build_stubbed` doesn't work with `Marshal.dump`

### ISSUE THREAD

**Issue by davidpdrsn** [thoughtbot/factory_bot#1120]
I get `TypeError: singleton can't be dumped` when I try to `Marshal.dump` something made with `build_stubbed`. Using `create` works just fine.

I discovered this because `Rails.cache.write(key, value)` calls `Marshal.dump(value)`.

Here is a reproduction script:

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.0"
  gem "sqlite3"
  gem "factory_bot_rails"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :first_name, null: false
  end
end

class User < ActiveRecord::Base
end

FactoryBot.define do
  factory :user do
    first_name "Bob"
  end
end

class BugTest < Minitest::Test
  def test_build_stubbed_works_with_marshal_dump
    user = FactoryBot.build_stubbed :user

    assert_equal "Bob", Marshal.load(Marshal.dump(user)).first_name
  end
end
```

Run script with `ruby script.rb`. [This](https://gist.github.com/davidpdrsn/ad6910ad723ff43bf10c1c20ba0519a3) is the output I get.

`ruby -v`: `ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]`

**Comment by composerinteralia** [comment]
Marshal cannot dump objects that define singleton methods (see https://ruby-doc.org/core-2.2.2/Marshal.html#method-c-dump). Build stubbed defines singleton methods to raise on any disabled persistence methods (https://github.com/thoughtbot/factory_bot/blob/master/lib/factory_bot/strategy/stub.rb#L62).

**Comment by composerinteralia** [comment]
I don't see a  clear path forward here, so I added a note about this limitation to the documentation. Happy to revisit if we come up with a better solution. Thanks!
