### ISSUE TITLE
build_stubbed inconsistency between .created_at and .attributes['created_at']

### ISSUE THREAD

**Issue by alexandergitter** [thoughtbot/factory_bot#1121]
A model created with `FactoryBot.build_stubbed` will return time values from the `created_at` and `updated_at` methods.
Trying to access these two fields through the `attributes` hash (e.g. `myobject.attributes['created_at']` or `myobject[:created_at]`) however, will return `nil`.

**Comment by composerinteralia** [comment]
Related to thoughtbot/factory_bot_rails#233

**Comment by composerinteralia** [comment]
Related to https://github.com/thoughtbot/factory_bot/pull/1058

**Comment by composerinteralia** [comment]
Should be fixed with #1223
