### ISSUE TITLE
y tho

### ISSUE THREAD

**Issue by ParzivalWolfram** [thoughtbot/factory_bot#1127]
Leave it to politics to make even software libraries change their names (thereby breaking a huge number of other things) because "men are bad, mkay?"

![no](https://user-images.githubusercontent.com/30007617/39502749-95b1778c-4d87-11e8-883d-e2d4aa8033b6.jpeg)

change it back plzty

**Comment by joshuaclayton** [comment]
We've previously discussed the "why" [here](https://robots.thoughtbot.com/factory_bot).
