### ISSUE TITLE
FactoryBot::DuplicateDefinitionError when referencing constant that does not exist

### ISSUE THREAD

**Issue by elimydlarz** [thoughtbot/factory_bot#1131]
@james-dowling and I just noticed that when we reference a constant that does not exist (whoops!) in the definition of a factory, it results in the following confusing error:

```
FactoryBot::DuplicateDefinitionError:  Factory already registered: activity
```

In our case, this definition - where `banana` is another factory - works fine:

```ruby
FactoryBot.define do
  factory :something do
    banana
  end
end
```

But if we try to assign a non-existent constant as a default for `banana`, we get that `FactoryBot::DuplicateDefinitionError`:

```ruby
FactoryBot.define do
  factory :something do
    banana ImaginaryConstant
  end
end
```

Perhaps the error causes FactoryBot to reload all the factory definitions for some reason?

**Comment by composerinteralia** [comment]
I am not having any luck reproducing this. Your second example gives me the expected `uninitialized constant ImaginaryConstant`:

```rb
require 'factory_bot'

class Something
end

FactoryBot.define do
  factory :something do
    banana ImaginaryConstant
  end
end
```

Any ideas what is missing?

You should normally only get a `FactoryBot::DuplicateDefinitionError` if you try to define two factories with the same name:

```rb
require 'factory_bot'

class Something
end

FactoryBot.define do
  factory :something do
  end

  factory :something do
  end
end
```

**Comment by composerinteralia** [comment]
I'm going to close for now. Feel free to reopen if I missed something. I would need a bit more context - ideally in the form of a reproduction script or a sample repo the demonstrates the issue. Thanks!
