### ISSUE TITLE
FactoryBot treats plain field as association

### ISSUE THREAD

**Issue by m0n9oose** [thoughtbot/factory_bot#1138]
Recently i've faced a problem with setting a value to field. After debugging I've realized that factory bot treat my field as association key.

Table `posts` has fields:
- `source`: int, not null (ActiveRecord enum)
- `source_id`, `varchar`, not null

Factory `post`:

```
FactoryBot.define do
  factory :post do
    source 1
    source_id { Faker::Crypto.md5.to_s }
  end
end
```

When I'm trying to build new `post` both fields are empty (since there's no association with such key)
It's also possible to remove `source` field value, then it's possible to set `source_id` but it's impossible to set both at the same time

Meantime if I rename `source` to `source_name` everything's work as expect

P.S. yes, i know, it's awful names for columns, but it's a huge db and a lot of legacy code.

```
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
factory_bot_rails (4.10.0)
MacOS 10.13.4
```

**Comment by composerinteralia** [comment]
FactoryBot makes assumptions about `source_id`/`source` (i.e. `source_id` is the foreign key and `source` is an association). 

I think this is related to #1096. You may be able to use the same workaround with transient attributes.

**Comment by composerinteralia** [comment]
Closing in favor of #1142
