### ISSUE TITLE
Question: Is it possible to reference the "current" attribute value when overriding it?

### ISSUE THREAD

**Issue by Epigene** [thoughtbot/factory_bot#1140]
Hi,

I've been using this gem for a couple years, so I think I know my way around, but this one has got me stumped. I know I can reference other attributes when setting some attribute, but what about referencing the "current" value of the field itself?

With JSON fields becoming more prominent, I have found the need to `merge` some default hash with additional options more prominent. Consider:

```rb
FactoryBot.define do
  factory :payload do
    transient do
      options { {} }
    end

    data { {default: "true"}.merge(options) }

    trait :custom do
       options { {default: "false"} }
    end
  end
end
```

Now I can do either:

`create(:payload, :custom)` or `create(:payload, options: {default: "false"})`, to get a "{default => "false"}" payload.

However, I can not do `create(:payload, :custom, options: {additional: "yup"})` to get a {default: "false", additional: "yup"}} payload.

It would all be solved if I could access `options` to merge with the value e.g.:

```rb
FactoryBot.define do
  factory :payload do
    transient do
      options { {} }
    end

    data { {default: "true"}.merge(options) }

    trait :custom do
       options { options.merge(default: "false") } # options can not reference itself :(
    end
  end
end
```

Obviously, the example above causes an infinite loop and a stack error.

Is what I want possible? Maybe I am approaching this all wrong..

**Comment by mikegee** [comment]
Is it possible from an [`after(:build)` callback](https://www.rubydoc.info/gems/factory_bot/file/GETTING_STARTED.md#Callbacks)?

**Comment by Epigene** [comment]
While `after(:build)` does provide a more flexible assignment alternative, the issue is not merging data with options, but options with more options.

**Comment by composerinteralia** [comment]
You could use two different transient attributes for this:

```rb
FactoryBot.define do
  factory :payload do
    transient do
      default_options { { default: "true" } }
      options { {} }
    end

    data { default_options.merge(options) }

    trait :custom do
      default_options { {default: "false"} }
    end
  end
end
```

It makes sense that `options { options.merge(default: "false") }` wouldn't work. Internally this defines an `options` method on an [evaluator](https://github.com/thoughtbot/factory_bot/blob/f71053bc26fcd6e378cd570ac5f62e6d24419995/lib/factory_bot/evaluator.rb) object. When we call that method, it executes the block in the context of the evaluator object (using `instance_eval`). So `options { options }` ends up being a recursive call to the same method.
