### ISSUE TITLE
Why did factory_girl become factory_bot?

### ISSUE THREAD

**Issue by patrick99e99** [thoughtbot/factory_bot#1148]
I am hoping it's not because of "politically correct" nonsense.

**Comment by mjankowski** [comment]
Don't worry, it's "not" because of that!

Full background: https://robots.thoughtbot.com/factory_bot

**Comment by patrick99e99** [comment]
Huh.. i just read your "why?" section and it looks like it's absolutely because of that!

Unfortunate...

**Comment by mjankowski** [comment]
Noted.
