### ISSUE TITLE
Why doesn't create_list return an ActiveRecord_Relation?

### ISSUE THREAD

**Issue by tibbon** [thoughtbot/factory_bot#1151]
It would seem most useful for testing scopes and such for `create_list` to return an `ActiveRecord_Relation` right? Is there any way to force it to do that?

**Comment by composerinteralia** [comment]
Thanks for the question. `create_list` is not specific to `ActiveRecord`, so it wouldn't make sense to return an `ActiveRecord` object. If you need to work with a `Relation`, you could try something like this:

```rb
users = `FactoryBot.create_list(:user, 5)`
User.where(id: users.map(&:id)
```
