### ISSUE TITLE
Customizing scaffold generator of factory_bot

### ISSUE THREAD

**Issue by Kani999** [thoughtbot/factory_bot#1157]
Is there any way how can I rewrite generator for `spec/factories/name_of_factory.rb` to be generated by my needs? 

I tried:

```
lib/templates/rspec/factory_bot.rb
lib/templates/rspec/scaffold/factory_bot.rb
```

Or my own generator:
```

lib/generators/rails/factory_bot_changes
lib/generators/rails/factory_bot_changes/USAGE
lib/generators/rails/factory_bot_changes/factory_bot_changes_generator.rb
lib/generators/rails/factory_bot_changes/templates
lib/generators/rails/factory_bot_changes/templates/factory_bot.rb
I also tried to change the config/application.rb
```

```
config.generators do |gen|
  gen.orm :active_record
  gen.template_engine :haml
  gen.test_framework :rspec,
                     fixtures: true,
                     view_specs: true,
                     helper_specs: true,
                     routing_specs: true,
                     controller_specs: true,
                     request_specs: true
  gen.helper :helper_and_policy
  gen.scaffold_controller :controller_with_smart_listing
  gen.fixture_replacement :factory_bot, dir: "spec/factories"
  # gen.fixture_replacement :factory_bot_changes, dir: "spec/factories"
  gen.factory_bot false
end
```

But nothing seems to be working.

Is there some folder, where I can put my own template which will be used?

**Comment by composerinteralia** [comment]
This sounds like a`factory_bot_rails` issues, related to https://github.com/thoughtbot/factory_bot_rails/issues/14 and https://github.com/thoughtbot/factory_bot_rails/issues/148. I think there may have been a custom template option in earlier versions, but it maybe got removed. I haven't looked into it too deeply. I'm going to close this issue, but feel free to add a comment on one of those other issues with any additional information. Thanks!
