### ISSUE TITLE
Document rubocop-rspec Cop for replacing deprecated static attributes

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/factory_bot#1160]
https://github.com/thoughtbot/factory_bot/pull/1135 deprecated static attributes, and I plan to remove them in factory_bot 5. [This Cop](https://github.com/rubocop-hq/rubocop-rspec/pull/666) allows you to automatically update your code to use dynamic attributes instead of static attributes. Once that PR gets merged, I would like to make sure we document the Cop in an obvious place: either in the README, an upgrade guide, or maybe in the deprecation warning itself.

**Comment by composerinteralia** [comment]
Get the latest version of rubocop-rspec and run:

```
rubocop \
  --require rubocop-rspec \
  --only FactoryBot/AttributeDefinedStatically \
  --auto-correct
```

**Comment by scottrobertson** [comment]
```
rubocop \
  --require rubocop-rspec \
  --only FactoryBot/AttributeDefinedStatically \
  --auto-correct
Inspecting 223 files

0 files inspected, no offenses detected
Unrecognized cop or department: FactoryBot/AttributeDefinedStatically.
```

Anything i need to do to get this working? I have the latest rubocop-rspec

**Comment by composerinteralia** [comment]
Hm, I have definitely seen this work. Can you double check the rubocop-rspec version in your gemfile.lock? It should be 1.28

**Comment by scottrobertson** [comment]
Hey

I was just about to delete my comment. For some reason, we had rubocop locked to an old version, which prevented rubocop-rspec from installing the newer version.

**Comment by rosskevin** [comment]
```
780 files inspected, no offenses detected

rubocop (0.59.0)
rubocop-rspec (1.29.1)
```
I've got deprecations all throughout the logs but when running the suggested rubocop command I also get nothing updated/no offenses...

**Comment by composerinteralia** [comment]
Is it possible you are running into this issue: https://github.com/thoughtbot/factory_bot/issues/1173?

**Comment by rosskevin** [comment]
Definitely @composerinteralia - thanks.

**Comment by JamesLivengood** [comment]
@composerinteralia also running into the same issue (factories aren't in `spec/factories` - how would I configure that?

**Comment by sbleon** [comment]
Here are the steps to get the autocorrect working if you're using Minitest:

1. `gem install rubocop-rspec`
2. Add the following to your .rubocop.yml
```
AllCops:
  RSpec:
    Patterns:
    - _test.rb
    - "(?:^|/)test/"

  RSpec/FactoryBot:
    Patterns:
    - test/factories/**/*.rb
```
3. `rubocop --require rubocop-rspec --only FactoryBot/AttributeDefinedStatically --auto-correct`

**Comment by composerinteralia** [comment]
RuboCop configuration: https://github.com/thoughtbot/factory_bot/issues/1173#issuecomment-421410343

**Comment by sunki** [comment]
```
$ gem list | grep cop
rubocop (0.52.1)
rubocop-rspec (1.29.1)
rubycop (1.0.1)
$ rubocop --require rubocop-rspec --only FactoryBot/AttributeDefinedStatically --auto-correct
cannot load such file -- rubocop-rspec
/Users/makk/.rvm/gems/ruby-2.5.1@gdeslon5/gems/rubocop-0.52.1/lib/rubocop/options.rb:63:in `require
```

**Comment by kimadactyl** [comment]
This doesn't work in the latest version but does if I lock my Gemfile to the ones noted above i.e. `rubocop (0.59.0)` +  `rubocop-rspec (1.29.1)`. Obviously I've sorted it now but thought I'd leave a note for the next person!
