### ISSUE TITLE
rubocop-rspec cop only configured to correct spec/factories/**/*.rb

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/factory_bot#1173]
https://github.com/rubocop-hq/rubocop-rspec/blob/master/config/default.yml

Unfortunately this means that the instructions in the deprecation warning only work if you have your factories in that location. I haven't looked into what is the best way to get this to work if you have the factories elsewhere.

**Comment by Darhazer** [comment]
@bquorning can you take a look?

**Comment by bquorning** [comment]
What is the deprecation message, exactly?

The last part of https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#defining-factories says

> Factories can be defined anywhere, but will be automatically loaded after calling `FactoryBot.find_definitions` if factories are defined in files at the following locations:
>```
>test/factories.rb
>spec/factories.rb
>test/factories/*.rb
>spec/factories/*.rb
>```

I am not sure why RuboCop-RSpec doesn’t include `spec/factories.rb` by default…

But, isn’t it safe to assume that for people with factory definitions in other locations, they will know what to do when RuboCop writes its warnings?

**Comment by composerinteralia** [comment]
People with factories under /test probably aren’t using RSpec, and so probably aren’t using rubocop-rspec. I think this is probably just a documentation issue on the factory_bot side to tell such users what the correct configuration would be to get this cop working for them.

**Comment by composerinteralia** [comment]
That's great. Thanks @sbleon!

**Comment by composerinteralia** [comment]
Another way we might be able to the experience less awkward for non-rspec users is to release a separate gem with just the one cop.

**Comment by composerinteralia** [comment]
It seems like a critical mass has gone through the upgrade so I am going to go ahead and close this.
