### ISSUE TITLE
Rails generated code uses static attributes

### ISSUE THREAD

**Issue by wilbertom** [thoughtbot/factory_bot#1174]
When creating a new rails model the `factory_bot` generator creates factories which use static attributes.  This leads to some warnings because those are depecrated. It would be nice if the factories generated used the dynamic ones.

Reproduce:

```
wil$ rails g model Something x
wil$ bundle exec rspec
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:

x { "MyString" }

To automatically update from static attributes to dynamic ones,
install rubocop-rspec and run:

rubocop \
  --require rubocop-rspec \
  --only FactoryBot/AttributeDefinedStatically \
  --auto-correct

 (called from block (2 levels) in <main> at /Users/wil/code/codetitans/syndicated/spec/factories/somethings.rb:3)

```

The factory looks like this:

```
FactoryBot.define do
  factory :something do
    x "MyString"
  end
end
```

Info:

* Ruby: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`
* Rails: `5.2.1`

**Comment by composerinteralia** [comment]
Yeah good call. I think we can fix that by updating https://github.com/thoughtbot/factory_bot_rails/blob/master/lib/generators/factory_bot/model/model_generator.rb#L73

I opened https://github.com/thoughtbot/factory_bot/issues/1174 as well, so we can track this on `factory_bot_rails`.
