### ISSUE TITLE
Instructions in static attributes deprecation warning do not work in some cases

### ISSUE THREAD

**Issue by ragesoss** [thoughtbot/factory_bot#1177]
There are some cases where rubocop-rspec does not fix the deprecated use of static attributes.: https://github.com/rubocop-hq/rubocop-rspec/issues/676

Hopefully this can be fixed in rubocop-rspec, but since it relates directly to FactoryBot I thought it would be helpful to open an issue here as well.

If it can't be fixed in rubocop-rspec, then tweaking the deprecation warning language might be helpful.

**Comment by Darhazer** [comment]
This is fixed in rubocop-hq/rubocop-rspec#677 and will be released shortly

**Comment by composerinteralia** [comment]
Thanks!
