### ISSUE TITLE
Gradually fix RuboCop todos

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/factory_bot#1202]
We added a .rubocop.yml in https://github.com/thoughtbot/factory_bot/commit/5b0257363ca4d14466e740b826374337f0c06d9b with a bunch of todos. It would be nice to gradually fix them. I would like to do it one at a time so nobody has to review a giant PR. 😸

**Comment by colinross** [comment]
Thinking like 1 commit per offense type?

**Comment by composerinteralia** [comment]
Yeah, I think so, but use your best judgement. The main thing would be to keep each pull request fairly small.

**Comment by ChaoticBoredom** [comment]
Are there any of these remaining to be addressed? It looks like #1208 hits most remaining things, unless we want to deviate from the primary rubocop.yml from thoughtbot.

**Comment by composerinteralia** [comment]
@ChaoticBoredom I merged #1208, but there are still a few more TODOs in https://github.com/thoughtbot/factory_bot/blob/master/.rubocop.yml
