### ISSUE TITLE
Disambiguate traits from associations

### ISSUE THREAD

**Issue by Epigene** [thoughtbot/factory_bot#1229]
Maybe I am doing something wrong, but when I define a trait that is named just like a factory I get 

```rb
NoMethodError:
  undefined method `user=' for #<Setting:0x007fdcc29fdb60>
```

```rb
FactoryBot.define do
  factory :user do
  end

  factory :setting do
    # using :user trait as default for setting factory
    user

    trait :user do
      setting_scope { "User" }
    end
  end
end
```

Looks like FactoryBot preferentially interprets the `user` call in setting factory body as a call to association rather than a trait, even though the instance does not have such an association (dunno if FB should care)

I know I can work around the problem by renaming the trait to something like `for_user`, but it seems to me FB should be able to tell that it's the trait I want, not the association.

Somewhat connected to https://github.com/thoughtbot/factory_bot/issues/1221

**Comment by composerinteralia** [comment]
Thanks for the issue! https://github.com/thoughtbot/factory_bot/pull/1017 also looks related.

**Comment by composerinteralia** [comment]
I looked at this issue again, and I think we can deal with it with documentation in #1221.

factory_bot will always look for a registered factory before it looks for a trait. If it finds a factory it uses it. It doesn't try to do any introspection on the instance, and I think doing so would get complicated and probably introduce all sorts of new problems.

I think in the documentation we can mention that in cases with any ambiguity it is better to use the explicit declaration. So for traits that would be:

```rb
factory :setting, traits: [:user] do
  trait :user
end
```

Many thanks for this issue!
