### ISSUE TITLE
Maybe deprecate `use_parent_strategy` configuration

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/factory_bot#1236]
https://github.com/thoughtbot/factory_bot/pull/1234#issuecomment-440902652 got me thinking more about this.

> I like using FactoryBot in my dev console, which means I do a certain amount of FactoryBot.reload. It looks like this config gets wiped when you do reload - reload calls reset_configuration, which does what one would expect.

That is a really good point! factory_bot_rails currently has `Spring.after_fork { FactoryBot.reload }` and factory_bot_rails 5 will have https://github.com/thoughtbot/factory_bot_rails/commit/02a0f584876ff5c7a6d6fa4965da58ed70464a73, which will call `FactoryBot.reload` whenever you change a factory definition or whenever you call `reload!` in the rails console. So I suspect this will cause problems at some point.

Right now I am tempted to get rid of the setting altogether for factory_bot 5 and just use the parent strategy all the time. This may cause some test failures for people, but they would be able to fix them by changing `build` to `create` for the failing tests.

**Comment by hmayer00** [comment]
👍 on the question of making use_parent_strategy the standard. 

I assume that it will cause some test failures for people, but I can't think of a time when you'd actually prefer the current default behavior over the new one - it would just be tests that happen to have developed that way (though of course I could be missing something). So for a major version release, it seems pretty reasonable to change the strategy without retaining an option for the old behavior. Just my 2c.

**Comment by composerinteralia** [comment]
I changed the default to true in d0208ed, but I am going to keep this issue open to track possibly deprecating `use_parent_strategy` down the line.
