### ISSUE TITLE
Fix "Self-referencing association" error for traits

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/factory_bot#1238]
This originally came up in https://github.com/thoughtbot/factory_bot/pull/1017, which includes a failing spec.

### Self-referencing association

The "Self-referencing association" error was introduced in e4a3d25711ffcc7945a49bdf67bdf564d1cb27e4 to catch this:

```rb
factory :user do
  user
end
```

This is still working as expected

### Trait referencing association with the same name

When the error was moved from `Factory` into `AttributeList` in e3bf491dd6af2b6c5c110c4a795db65bb458e3da it started catching associations with the same name as a trait as well:

```rb
factory :post

factory :user do
  trait :post do
    association :post
  end
end
```

The `AttributeList` doesn't know when it is part of a trait definition rather than a factory definition.
It just raises an error if its name matches the name of the association:
https://github.com/thoughtbot/factory_bot/blob/cffa56e4c8c55bb1467e14e6fb885a6b6fafc54f/lib/factory_bot/attribute_list.rb#L56

While I think naming the factory and trait the same thing is confusing, I am not convinced it should raise an error.

### Self-referencing trait

What should definitely raise an error is a self-referential trait, but this will currently give us a trait that calls itself recursively:

```rb
factory :user do
  trait :bad_trait do
    bad_trait
  end
end
```

I think it would make sense to catch this and 

```rb
raise TraitDefinitionError, "Self-referencing trait..."
```

**Comment by swetagsanghavi** [comment]
Just merged https://github.com/thoughtbot/factory_bot/pull/1294 which addresses this issue.
