### ISSUE TITLE
FactoryBot::DuplicateDefinitionError when defining the same-named sequence in the same-named trait in distinct factories 

### ISSUE THREAD

**Issue by shepmaster** [thoughtbot/factory_bot#1257]
After upgrading to 5.0, I'm seeing this error:

> Sequence already registered: __from_api_id__ (FactoryBot::DuplicateDefinitionError)

This code previously worked in 4.x. I've looked at the [release notes](https://github.com/thoughtbot/factory_bot/releases/tag/v5.0.0), but there's nothing *obvious* there about this (at least to me as a casual user of factory_bot).

## Steps to reproduce

**Gemfile**

```
# frozen_string_literal: true

source "https://rubygems.org"
gem "factory_bot", "~>5"
```

**example.rb**

```ruby
require 'factory_bot'

User = Struct.new(:id)
Company = Struct.new(:id)

FactoryBot.define do
  factory :user, class: User do
    trait :from_api do
      sequence(:id, '1')
    end
  end

  factory :company, class: Company do
    trait :from_api do
      sequence(:id, '1')
    end
  end
end
```

```
$ bundle exec ruby example.rb
Traceback (most recent call last):
	18: from example.rb:6:in `<main>'
	17: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot/syntax/default.rb:7:in `define'
	16: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot/syntax/default.rb:49:in `run'
	15: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot/syntax/default.rb:49:in `instance_eval'
	14: from example.rb:13:in `block in <main>'
	13: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot/syntax/default.rb:18:in `factory'
	12: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot/syntax/default.rb:18:in `instance_eval'
	11: from example.rb:14:in `block (2 levels) in <main>'
	10: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot/definition_proxy.rb:174:in `trait'
	 9: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot/definition_proxy.rb:174:in `new'
	 8: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot/trait.rb:12:in `initialize'
	 7: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot/trait.rb:12:in `instance_eval'
	 6: from example.rb:15:in `block (3 levels) in <main>'
	 5: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot/definition_proxy.rb:122:in `sequence'
	 4: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot.rb:105:in `register_sequence'
	 3: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot.rb:105:in `each'
	 2: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot.rb:106:in `block in register_sequence'
	 1: from /Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot/decorator/disallows_duplicates_registry.rb:6:in `register'
/Users/shep/.rvm/gems/ruby-2.5.3/gems/factory_bot-5.0.0/lib/factory_bot/decorator.rb:10:in `method_missing': Sequence already registered: __from_api_id__ (FactoryBot::DuplicateDefinitionError)
```

- Ruby Versions:
  - ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
  - ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
- macOS 10.14.3

**Comment by composerinteralia** [comment]
Thanks for the issue! That does seem unexpected. I'll try to look into this before the end of the week.

**Comment by shepmaster** [comment]
> It occurred to me that this is probably because of #1164.

Seems reasonable:

> > We register them with `__#{factory_name}_#{sequence_name}__`

**Comment by composerinteralia** [comment]
> We register them with `__#{factory_name}_#{sequence_name}__`

I don't think that is really true. We register them with `@definition.name`, which could be either a factory name or a trait name.

**Comment by shepmaster** [comment]
> I don't think that is really true

You should have a stern talking-to with the developer that opened that PR then 😉

**Comment by shepmaster** [comment]
Thanks!

**Comment by tilo** [comment]
@composerinteralia there is an odd corner case where raising this error causes problems:

Scenario:
* you're in a lengthy transition to break down a monolith 
* some of the code and factories were already pulled-out into an internal gem 🎉 
* you're working in another repo, something odd breaks, caused by a factory in that gem
* copying that factory code over into your current repo could help with setting a breakpoint,
   but FactoryBot will throw an error when it encounters the second definition introduced by the gem 😢 
   
 Is there a clever way to recover from `FactoryBot::DuplicateDefinitionError` and just ignore the second definition?

**Comment by tilo** [comment]
@composerinteralia Could this be optionally just print an error message to the console, and ignore the second definition? 
Perhaps print the __FILE__ location of the second definition?

https://github.com/thoughtbot/factory_bot/blob/893eb67bbbde9d7f482852cc5133b4ab57e34b97/lib/factory_bot/decorator/disallows_duplicates_registry.rb#L6

**Comment by composerinteralia** [comment]
@tilo I think it'd be best to to either open a separate issue or add a comment on an open issue (https://github.com/thoughtbot/factory_bot/issues/968 perhaps, especially as it relates to https://github.com/thoughtbot/factory_bot/pull/1064).

This particular issue was for a bug where we incorrectly raised a DuplicateDefinitionError. We've fixed that particular bug, so additional comments on this issue may get lost.
