### ISSUE TITLE
Deprecation warnings when upgrading Rails 5.0 to 5.1

### ISSUE THREAD

**Issue by veganstraightedge** [thoughtbot/factory_bot#1261]
Hi y'all.

I'm trying to upgrade a Rails app from rails `5.0.x` to `5.1.x`.

When I do that in the `Gemfile`, `bundle`, then run the specs, I get a pile of `DEPRECATION WARNINGS` from Rails.

The deprecated methods in question are never used directly in our codebase.
The files that the warnings point to are all in `/spec`. 
The lines in question look something like this:

```ruby
describe Foo do
  let :token do
    create(:access_token, password: 'abc123')
  end

  let :user do
    create(:user)
  end

  # ...
end
```

The deprecated methods are:

- `attribute_changed?`
- `attribute_change` 
- `attribute_was` 
- `changed_attributes` 

My first hunch was to upgrade `factory_bot`/`factory_bot_rails`, but we're already on `5.0.x`.

Any ideas where these deprecated methods are being used?

Thanks.

**Comment by composerinteralia** [comment]
Hm, we don't call those methods anywhere directly in factory_bot, and this issue doesn't sound familiar to me. Do you get the same warning if you create with factory_bot in the console (you may need to add factory_bot to the development group of your gemfile to check this if it isn't already there):

```
$ rails c
> FactoryBot.create(:user)
```

What about if you create the object manually without factory_bot (replacing the ... with all the attributes you need to create a user):

```
$ rails c
> User.create(...)
```

**Comment by composerinteralia** [comment]
@veganstraightedge were you able to make any progress on this? I may end up closing this issue unless somebody can help reproduce it. Many thanks!

**Comment by veganstraightedge** [comment]
We can close it. Thanks for the direction. It requires some more investigation on my end. If, by some weird chance, it comes back to being a FactoryBot concern, I'll re-open this issue. Thanks.

**Comment by AlexGascon** [comment]
@composerinteralia I'm exeperiencing the exact issue, also after updating from Rails 5.0 to Rails 5.1.

This is the message I get when running my tests:

```
DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead
```

The warnings always appear on spec files, when using `create` to create an object from a factory.

I'm using Rails 5.1.7, and I experience the warning both on `factory_bot_rails` versions 4.11.1 and 5.0.2. 

If there's any more information that I can provide to help with this, just let me know!

**Comment by composerinteralia** [comment]
@AlexGascon are you able to provide a sample application that reproduces this warning?

**Comment by gmanningcr** [comment]
If anyone else happens upon this issue, for me the deprecation warning was actually coming from the paper_trail gem, upgrading paper_trail resolved it https://github.com/paper-trail-gem/paper_trail/issues/974
