### ISSUE TITLE
NoMethodError for enum field

### ISSUE THREAD

**Issue by yosfik** [thoughtbot/factory_bot#1264]
I tried to create a model in rails 5.2.2 with an enum field
```
class Episode < ApplicationRecord
  validates :title, :start_time, presence: true
  validates_uniqueness_of :start_time

  enum status: {
    ready: 0,
    started: 1,
    finished: 2
  }
end
```
Then, I created `test/factories/episodes.rb` using `factory_bot_rails` v5.0.0, like so
```
FactoryBot.define do
  factory :episode do
    transient do
      time { (rand(199) + 1).minutes.from_now }
    end
    title { "Episode #{SecureRandom.hex(3)}" }
    start_time { time }
    status :ready
  end
end
```
When I tried to open rails console, I got following error
```
'method_missing': undefined method 'status' in 'episode' factory (NoMethodError)
```
Same error occurred when I tried to open rails db, or running tests. However, when `status` field is removed from the factory, the error is gone. Also, when downgrading to  v4.10.0, the `status` enum works fine. Any idea, what happened here?

This is how the migration looks like:
```
class CreateEpisode < ActiveRecord::Migration[5.2]
  def change
    create_table :episodes do |t|
      t.string :title
      t.datetime :start_time
      t.integer :status, default: 0

      t.timestamps
    end
  end
end
```

**Comment by composerinteralia** [comment]
Thanks for the issue! That is an expected error. We no longer support defining "static" attributes without a block, so you will need to write `status { :ready }`. We introduced the deprecation warning in 4.11, so it may be easier to upgrade to 4.11 and address all the deprecation warnings before upgrading to 5.0. You can read more about why we went ahead with the deprecation and removal of static attributes on the [thoughtbot blog](https://thoughtbot.com/blog/deprecating-static-attributes-in-factory_bot-4-11).

**Comment by yosfik** [comment]
@composerinteralia Thank you very much. Closing the issue.

**Comment by fdutey** [comment]
Hi.

Would you mind at least improving the error message? `NoMethodError` is so confusing
`RuntimeError("static attributes can not be defined without a block")` would have saved me half an hour.

Cheers

**Comment by composerinteralia** [comment]
@fdutey I am definitely open to improving the message on that `NoMethodError`, perhaps with a "Did you mean?" style recommendation.
