### ISSUE TITLE
Document Evaluator#association

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/factory_bot#1268]
https://github.com/thoughtbot/factory_bot/issues/1063
https://github.com/thoughtbot/factory_bot/issues/1255

The tests in https://github.com/thoughtbot/factory_bot/pull/1419 may serve as a starting point for some code examples as part of this documentation.

**Comment by hmayer00** [comment]
It's worth noting one oddity with this usage. If you have an association whose factory has a different name, in general one does
```ruby
association :association_name, factory: :factory_name
```
However, if you want to use the evaluator syntax, it appears that you need to do:
```ruby
association_name { association(:factory_name) }
```

That still works fine (and I'm stoked to have it!), but I would have expected this to work, and it doesn't for me:
```ruby
association_name { association(:association_name, factory: :factory_name) }
```

Probably fine just to document that, but I figured I'd throw that out there since it's not obvious, and would be easy to miss while documenting.

**Comment by composerinteralia** [comment]
Good find. I wonder if we can fix that. I won't have time to look into this for the couple weeks, but the method in question is [here](https://github.com/thoughtbot/factory_bot/blob/99ac02400fd56bd1872fc3ed84f81ea5e8f27737/lib/factory_bot/evaluator.rb#L24-L34) if you or anybody else wants to explore that.

**Comment by hmayer00** [comment]
I'll take a swing at it in the next few days and see what I can come up
with.

**Comment by hmayer00** [comment]
@composerinteralia no rush but since I never explicitly commented on it here I figured I should mention that I opened PR #1300 to resolve the oddity I noted above. I'm happy to also write the docs requested in this issue, pending your thoughts on the suggestion in that PR.

**Comment by composerinteralia** [comment]
Thanks! I am hoping to have some time next week to take a look.

**Comment by hmayer00** [comment]
No problem, thank y'all for the gems! And really no rush, none of this is urgent - just wanted to make sure it didn't get lost in what I assume are a large number of notifications.

**Comment by composerinteralia** [comment]
Now documented in:

* https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#inline-definition
* https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#has_many-associations
* https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#has_and_belongs_to_many-associations
* https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#interconnected-associations

**Comment by mickenorlen** [comment]
Is there any way to build associations directly in the test file? Below gives `undefined method association`

`category_spec.rb`
```RUBY
build(
    :category,
    name: "A test category",
    tags: [ association(:tag) ],
  )
```
