### ISSUE TITLE
Edge case for recommended way to define `has_many`

### ISSUE THREAD

**Issue by tejanium** [thoughtbot/factory_bot#1304]
The official way to define `has_many` based on the documentation [here](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#associations), is by using `after(:create)` callback:

```ruby
FactoryBot.define do
  factory :post do
    body { "nice!" }
  end

  factory :user do
    trait :with_post do
      after(:create) do |user|
        create(:post, user: user)
      end
    end
  end
end
```

Bur if we're doing something to the association before we save the object like:

```ruby
class User < ApplicationRecord
  has_many :posts
  validate :post_validity

  def post_validity
    posts.all? &:valid?
  end
end
```

then in the spec 

```ruby
user = create(:user, :with_post)
user.posts #=> []
```

expectation
```ruby
user.post #=> [Post]
```

I think it was because `user.posts` got cached when `after(:create)` being executed

I can solve it by doing 

```ruby
  factory :user do
    trait :with_post do
      after(:create) do |user|
        create(:post, user: user.reload)
      end
    end
  end
```

but is there any better way?

**Comment by composerinteralia** [comment]
Thanks for the issue! This came up back in https://github.com/thoughtbot/factory_bot/issues/549, and is ultimately related to improving support for collection associations, currently being tracked with https://github.com/thoughtbot/factory_bot/issues/458

**Comment by composerinteralia** [comment]
We have updated the documentation to include alternate approaches, and to mention that you may need to reload the record in some cases when using `after(:create)`.
