### ISSUE TITLE
ActiveModel::MissingAttributeError when using `build_stubbed`, primary_key is not set (Rails 6)

### ISSUE THREAD

**Issue by stevegeek** [thoughtbot/factory_bot#1305]
I am trying out Rails 6 RC1. It seems that when using `build_stubbed` I get 

```
ActiveModel::MissingAttributeError:
        can't write unknown attribute ``
```

I have been looking into it and it seems that `primary_key` isn't setup on the stub instance. 

In the stub strategy in `stub_database_interaction_on_result` the ID of the stub instance is set (https://github.com/thoughtbot/factory_bot/blob/master/lib/factory_bot/strategy/stub.rb#L47), however this fails with the above Error as `@primary_key` is `nil`.

Im not sure why this issue has started to occur,  Im assuming it was due to https://github.com/rails/rails/commit/b6828fc91531ae0cc0a0f216705dd19112596301 

I guess the solution is to explicitly call `primary_key=` when doing `build_stubbed`?

factory_bot version: 5.0.2 
Rails version : 6 RC1

**Comment by composerinteralia** [comment]
Thanks for the issue! We are running our tests on Rails 6.0.0.rc1 and they are all passing, so I am thinking you might be doing something a little different than anything we have tested against. Would you be able to provide a failing test or a sample application that reproduces the problem? You might be able to use something like this [reproduction script](https://github.com/thoughtbot/factory_bot/blob/master/.github/REPRODUCTION_SCRIPT.rb).

**Comment by stevegeek** [comment]
Thanks @composerinteralia ! Ok I will try to find a reproduction and get back asap

**Comment by stevegeek** [comment]
@composerinteralia , please find attached the repro script. It works when activerecord is version 5, but fails with version 6.

```require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "factory_bot", "~> 5.0"
  gem "activerecord", "6.0.0.rc1"
  gem "sqlite3"
end

require "active_record"
require "factory_bot"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "product_tags", id: :bigint, force: :cascade do |t|
    t.string "name", null: false
  end

  create_table "standardized_products", id: :bigint, force: :cascade do |t|
    t.text "description", null: false
  end

  create_table "product_tag_assignments", id: false, force: :cascade do |t|
    t.bigint "product_tag_id", null: false
    t.string "assigned_to_type"
    t.bigint "assigned_to_id"
  end
end


class ProductTag < ActiveRecord::Base
end

class StandardizedProduct < ActiveRecord::Base
end

class ProductTagAssignment < ActiveRecord::Base
  belongs_to :product_tag
  belongs_to :assigned_to, polymorphic: true
end

FactoryBot.define do
  factory :product_tag do
    name { "Best seller" }
  end

  factory :standardized_product do
    description { "Acme widget" }
  end

  factory :product_tag_assignment do
    product_tag
    association :assigned_to, factory: :standardized_product
  end
end

class FactoryBotTest < Minitest::Test
  def test_factory_bot_stuff
    post = FactoryBot.build_stubbed(:product_tag_assignment)
    assert_equal post.product_tag.name, "Best seller"
  end
end
```

Error is:
```
  1) Error:
FactoryBotTest#test_factory_bot_stuff:
ActiveModel::MissingAttributeError: can't write unknown attribute ``
    /Users/stephen/.rvm/gems/ruby-2.6.3/gems/activemodel-6.0.0.rc1/lib/active_model/attribute.rb:206:in `with_value_from_database'
```

**Comment by composerinteralia** [comment]
Thank you! 🙌

**Comment by stevegeek** [comment]
I should note that the above script passes the assertion is using `build` or `create` but not `build_stubbed`

**Comment by composerinteralia** [comment]
@stevegeek thanks for this fantastic report and reproduction. I opened #1316 to address the error on our side. I might also open an issue on Rails, since the behavior of `id`, `id=`, and `id?` is a bit strange when there is no primary key on the table.

**Comment by stevegeek** [comment]
@composerinteralia Ok thanks! :) Looking forward to the fix!
