### ISSUE TITLE
Make it easier to customise associations by accessing instance

### ISSUE THREAD

**Issue by lukeredpath** [thoughtbot/factory_bot#1309]
I find it very frustrating the hoops that Factory Bot makes us jump through to customise associations. We can specify which factory and traits we want to use using the `association` method and we can also pass in static values to override attributes but there is no way that I can see of dynamically overriding attributes. Being able to do this would simplify a number of use cases.

For example, it can be tricky to specify a `has_one` association without a circular reference:

```ruby
factory :employer do
  manager # has_one
end

factory :manager do
  employer # belongs_to
end
```

If I try to create an employer, it fails due to the circular reference. What I really need to be able to do in my `employer` factory is say - "create an associated manager with this instance as the employer". I believe the only way to do this is by moving the creation of `has_xxx` associations into a callback:

```ruby
factory :employer do
  after :build do |employer|
    employer.manager = build(:manager, employer: employer)
  end
end
```

This solution has problems of its own. Here I'm defining an after build callback but I have to be explicit about the build strategy for the association - we lose the automatic strategy inheritance you get with the normal association definition.

This means if I want to be able to do `build_stubbed :employer` I need to define another almost duplicate callback:

```ruby
factory :employer do
  after :build do |employer|
    employer.manager = build(:manager, employer: employer)
  end

  after :stub do |employer|
    employer.manager = build_stubbed(:manager, employer: employer)
  end
end
```

This issue has been raised before (#640).

So in an ideal world, I'd prefer if the original example just worked, rather than failing with a stack level too deep error. But if this isn't possible, it would make life much easier if we could just do this on the has_xxx side:

```ruby
factory :employer do
  manager do |evaluator| # gets called when building regardless of the build strategy
    association(:manager, employer: evaluator.instance) # inherits the build strategy from the parent
  end
end
```

We can already access other attributes of the factory, including transient attributes, but not the instance being built itself. I did notice I could sort of make this work by using `@instance` but this is a private API. It would be great if it could be exposed.

**Comment by franco** [comment]
Have you tried this? 

```ruby
factory :employer do
  manager { association :manager, employer: @instance }
end
```

**Comment by composerinteralia** [comment]
Thanks for opening this issue. I think ultimate this is similar to issues like https://github.com/thoughtbot/factory_bot/issues/1063 and https://github.com/thoughtbot/factory_bot/issues/458, and I think the [Josh Clayton's comment](https://github.com/thoughtbot/factory_bot/issues/1063#issuecomment-339418756) there probably applies to some extent here as well.

I don't see a way of making the first example work without making lots of assumptions about what sorts of objects are being built (AR, another ORM, plain Ruby objects?). If somebody would like to explore that further and prove me wrong, I would be interested in seeing that, but with the way things currently are a stack level to deep error is what I would expect here (the manager factory builds and employee, which builds a manager, which builds an employee, etc. ad infinitum).

```rb
factory :employer do
  manager # has_one
end

factory :manager do
  employer # belongs_to
end
```

I think that leaves us for now with making the evaluator instance available via a public reader. I have seen that come up in several contexts, and it seems to make the library more flexible for a bunch of these more complex use cases, so I am going to go ahead and do that.

That means you would be able to write:

```rb
factory :employer do
  manager { association(:manager, employer: instance) }
end
```

I will also try to prioritize writing some [documentation for `Evaluator#association`](https://github.com/thoughtbot/factory_bot/issues/1268), which this solution relies on.

**Comment by composerinteralia** [comment]
`Evaluator#association` is now officially documented: https://github.com/thoughtbot/factory_bot/issues/1268#issuecomment-656226689

**Comment by danielricecodes** [comment]
> ```ruby
> factory :employer do
>   manager { association(:manager, employer: instance) }
> end
> ```

This works perfectly inside of `trait`'s as well!  In my case, I needed to update a value while building and this worked perfectly.  Its also perfectly readable as well which I really like.

```ruby
trait :with_additional_fee do
  fee_cents { 500 }
  total_cents { @instance.total_cents + 500 }
end
```

I am sure I could have done `@instance.total_cents + @instance.fee_cents` but I didn't want to push it ;)
