### ISSUE TITLE
Lazy load factories' definitions?

### ISSUE THREAD

**Issue by khiav223577** [thoughtbot/factory_bot#1311]
I'm trying to figure out why my test is so slow in my project.

It seems that `require 'factory_bot_rails'` takes 1.46 seconds to load, and all files including factory_bot_rails take 2.2 seconds to load.`factory_bot_rails` occupied 65% of my time!

So I wonder whether it is possible to load the definitions only when the factory is used?
My project has hundreds of factories and only few of them will be used in a single test file.
It would be a waste of time to load all the factories when you are fixing a bug and just want to test a test case.

```rb
FactoryBot.define do
  factory :user do
    # user definitions here
    # load the definitions only when `:user` is used
  end
end
```

### System configuration
**factory_bot version**:  5.0.2
**rails version**:  4.2.11.1
**ruby version**:  2.5.5

**Comment by composerinteralia** [comment]
I think you could set `FactoryBot.definition_file_paths = []` to avoid automatically loading definitions, then if you have each factory in its own file you can just required the files that you need.

**Comment by khiav223577** [comment]
I found that the real problem is that I specify the class by constant (ex: `factory :admin, class: User`), and Rails will autoload it for me.

So I replaced all of them with string (ex: `factory :admin, class: 'User'`). 
And then it runs fast now :).
