### ISSUE TITLE
access instance in attributes blocks

### ISSUE THREAD

**Issue by ngouy** [thoughtbot/factory_bot#1312]
## not a bug it's more of a question.

Sorry if dup I can't find anything on SO nor here

short 
### Is there a reason we can't access the instance itself into an "attribute block" ?

------

long

lets have a `parent` model and a `child` model. `Parent.has_one(:child)`

In a callback (such as after create), we have access to the created instance as following : 
```rb
FactoryBot.define do
  factory :childs do
    # ...
    after(:create) do |newly_created_child_instance, _params|
      # ...
    end
  end
end
```

But when declaring an attribute such as `a_parent_model`, the block yields the current factory object (with a `class` class ...). Which expose the `instance` in **_write_only_**.
So I ended up using `factory_object.instance_variable_get(:instance)` to get it ... :

```rb
FactoryBot.define do
  factory :childs do
    parent_model do |factory_object|
      association(
        :parent_model,
        child: factory_object.instance_variable_get(:@instance)
      )
    end
  end
end
```

I have to do this because :
- my parent model `has_one child`
- my parent model have an `after_create` callback where he performs a  `Child.find_or_create_by(parent: self)`, 
so I can't just declare ` parent { association :parent }` in my factory, because I ended up with 2 `child` childs (the one created in the parent callback, and the one created by the factory)
- I don't want to simply do a 
```rb
# my spec
let(:child_instance) { parent_instance.child)
let(:parent_instance) { create(:parent) }
```
because it gets funkyer when using some custom params or trait on `child`. I have to perform some `update` instead of just
```rb
# spec
let(:child_instance) { create(:child, :some_traits_and_attributes, ...) }
let(:parent_instance) { child_instance.parent } 
```

Hope it's clear enought ... 😞

**Comment by ngouy** [comment]
hy @composerinteralia 

The question here was more about "why".

ATM, I found a way through with a simple monkey patch, but If it ment to be a feature, I can give a try and make a PR

**Comment by composerinteralia** [comment]
I'm having trouble understanding your precise use case here. Would you be able to provide a runnable example, preferably in this format: https://github.com/thoughtbot/factory_bot/blob/master/.github/REPRODUCTION_SCRIPT.rb?

**Comment by composerinteralia** [comment]
I noticed that https://github.com/thoughtbot/factory_bot/issues/1309 also mentions making a public reader for `@instance`. Is your use case similar to the one mentioned there?

**Comment by ngouy** [comment]
Yes it seems the same kind of issue.

**Comment by composerinteralia** [comment]
OK, thanks. I am going to close this issue for now and continue tracking it in #1309
