### ISSUE TITLE
Performance issues with traits

### ISSUE THREAD

**Issue by jeffcarbs** [thoughtbot/factory_bot#1332]
I'm using `FactoryBot` to test a small ruby gem and when I started using traits I noticed a pretty significant uptick in test runtime. I put together a script to show the performance impact even a few traits can have on factories.

I've been investigating a bit and have found what's likely the biggest culprit ([using a `detect` when we probably want a hash lookup](https://github.com/thoughtbot/factory_bot/blob/master/lib/factory_bot/definition.rb#L113-L115)). I'll send over a PR to improve that. However, it looks like even after fixing that there are more inefficiencies when using traits that get worse the more traits you have or the more traits you use on a given `build` or `create` call.

Also I wanted to call out that while I found this testing a small ruby gem my company's main application test suite has 500+ usages of `traits` (across ~100 different factories). One of our core models has over 25 traits on it.

### Steps to reproduce
Running the [reproduction script](https://gist.github.com/jeffcarbs/bc988c4b08aa81e013d22e8feb11c476) will show benchmark results of various scenarios.

### Expected behavior
Traits would have negligible performance overhead.

### Actual behavior
Using a single trait on a factory with one trait defined more than doubles the runtime of `build`. As you define more traits and/or use more of the defined traits performance gets worse.

Raw results:
```
Test one (n=10000): not setting anything
       user     system      total        real
Has  0 traits  0.630000   0.000000   0.630000 (  0.637583)
Has  1 trait   0.630000   0.000000   0.630000 (  0.631442)
Has  2 traits  0.710000   0.010000   0.720000 (  0.734025)
Has  3 traits  0.620000   0.010000   0.630000 (  0.622784)
Has 50 traits  0.610000   0.000000   0.610000 (  0.624279)

Test two (n=10000): passing attributes without using traits
       user     system      total        real
Has  0 traits  1.070000   0.010000   1.080000 (  1.079745)
Has  1 trait   1.090000   0.010000   1.100000 (  1.106030)
Has  2 traits  1.120000   0.000000   1.120000 (  1.126111)
Has  3 traits  1.220000   0.030000   1.250000 (  1.253315)
Has 50 traits  1.140000   0.000000   1.140000 (  1.152264)

Test three (n=10000): passing attributes and using traits
       user     system      total        real
Has  0 traits, using 0  1.160000   0.020000   1.180000 (  1.190228)
Has  1 trait,  using 1   2.600000   0.020000   2.620000 (  2.636136)
Has  2 traits, using 1   2.610000   0.010000   2.620000 (  2.634467)
Has  3 traits, using 1   2.730000   0.020000   2.750000 (  2.766916)
Has 50 traits, using 1   7.680000   0.040000   7.720000 (  7.758933)

Test three (n=10000): using traits without passing attributes
       user     system      total        real
Has  0 traits, using 0  0.550000   0.000000   0.550000 (  0.546372)
Has  1 trait,  using 1   1.810000   0.010000   1.820000 (  1.824369)
Has  2 traits, using 1   1.890000   0.000000   1.890000 (  1.901523)
Has  3 traits, using 1   1.960000   0.010000   1.970000 (  1.964625)
Has 50 traits, using 1   6.940000   0.010000   6.950000 (  6.965011)

Test five (n=10000): using different amounts of traits on factory with a 3 traits without passing attributes
       user     system      total        real
Has 3 traits, using 1  1.890000   0.000000   1.890000 (  1.899632)
Has 3 traits, using 2  2.310000   0.010000   2.320000 (  2.318839)
Has 3 traits, using 3  2.690000   0.000000   2.690000 (  2.699934)

Test six (n=10000): using different amounts of traits on factory with 50 traits without passing attributes
       user     system      total        real
Has 50 traits, using 1  6.720000   0.010000   6.730000 (  6.735540)
Has 50 traits, using 2  8.920000   0.020000   8.940000 (  8.958390)
Has 50 traits, using 3 10.700000   0.010000  10.710000 ( 10.725242)
Has 50 traits, using 4 13.410000   0.010000  13.420000 ( 13.439983)
```

### System configuration
**factory_bot version**: 5.1.0
**rails version**:  n/a
**ruby version**:  2.4.3

**Comment by composerinteralia** [comment]
Thanks for making such a huge improvement to the performance of traits. I played around with your benchmarks a bit and I think a see another potential culprit:

When you build a factory with traits (e.g. `FactoryBot.build(:factory_with_fifty_traits, :ny, :co, :ca)`) the runner [adds traits to the factories](https://github.com/thoughtbot/factory_bot/blob/2e48817badf3c4212697e71faf59c1a9a380dc38/lib/factory_bot/factory_runner.rb#L16-L18) by [cloning the factory](https://github.com/thoughtbot/factory_bot/blob/2e48817badf3c4212697e71faf59c1a9a380dc38/lib/factory_bot/factory.rb#L93-L97). Cloning the factory [clones the definition](https://github.com/thoughtbot/factory_bot/blob/2e48817badf3c4212697e71faf59c1a9a380dc38/lib/factory_bot/factory.rb#L93-L97), which [wipes out the cached traits](https://github.com/thoughtbot/factory_bot/blob/2e48817badf3c4212697e71faf59c1a9a380dc38/lib/factory_bot/factory.rb#L93-L97).

Deleting `FactoryBot::Definition#initialize_copy` improves the performance, but it breaks some tests.

**Comment by jeffcarbs** [comment]
@composerinteralia - sounds good, I’ll close this out. Thanks again for the quick review on that PR 🙂

**Comment by composerinteralia** [comment]
@entcheva @fridaland ^ I think this issue is also related to the traits restructuring we chatted today.
