### ISSUE TITLE
Unable to retrieve trait info in callback evaluator

### ISSUE THREAD

**Issue by ivar** [thoughtbot/factory_bot#1354]
### Steps to reproduce

Use an evaluator in a callback. e.g.
```ruby
    after(:build) do |contact|
      contact.company ||= build :company
    end
```
### Expected behavior
I expect to be able to query the evaluator to determine which traits (if any) were used to inform the creation of the model.

### Actual behavior
The evaluator has data on the build strategy, instance, cached_attributes and overrides.

### System configuration
**factory_bot version**:  5.1.1
**rails version**:  5.2.2.1
**ruby version**:  2.5.7 

---
This is arguably more of a feature request than a bug, but it would be super useful to be able to modify the callback behaviour based on traits.

**Comment by composerinteralia** [comment]
I think what you are describing is possible using a combination of traits and transients:

```rb
FactoryBot.define do
  factory :object do
    transient do
      with_message { false }
    end

    trait :with_message do
      transient do
        with_message { true }
      end
    end

    after(:build) do |object, evaluator|
      if evaluator.with_message
        puts "This message only printed when you use the `:with_message` trait" 
      end
    end
  end
end
```

As for adding information specifically about traits to the evaluator, I don't think that is something we are likely to do. The purpose of traits is to group attributes together so they can be applied all together. The purpose of the evaluator is to hold all the values of the attributes (including the transient ones). Adding the traits themselves to the evaluator would muddy the purpose of both objects.

Hopefully the solution with traits + transients will work for you. Let me know if you have any questions.

Thanks!

**Comment by henrik** [comment]
I wanted the same, and I thought I'd describe my use case:

If two traits are both set, a third value needs to be present.

E.g. if a Lookup has both the traits :manual and :verified, we should also set verified_by_user. (But not if it's verified but not manual, or manual but not verified.)

I can probably solve this with transients per above, but being able to check for the traits in an after(:build), or even better, being able to declare attributes for combined traits would be ideal.

**Comment by henrik** [comment]
Actually, the suggestion above doesn't work together with "default traits":

```
 factory :lookup do
   transient do
     foo_trait { false }
   end

   foo

  trait(:foo) do
     transient do
       foo_trait { true }
     end

    state { "foo" }
  end
end
```

`FactoryBot.build(:lookup)` will build a "foo" lookup, but with `foo_trait` set to false. Presumably because the trait transient is trumped by the top-level transient.

**Comment by henrik** [comment]
I ended up doing it this way:

``` ruby
after(:build) do |instance, evaluator|
  if instance.manual? && instance.verified? && !evaluator.passed_in?(:verified_by_user) && !evaluator.passed_in?(:verified_by_user_id)
    instance.verified_by_user = FactoryBot.build(:user)
  end
end
```

This relies on `passed_in?` that we define elsewhere:

``` ruby
class FactoryBot::Evaluator
  def passed_in?(name)
    # https://groups.google.com/g/factory_girl/c/MyYKwbq76d0/m/JrKJZCgaXMIJ
    __override_names__.include?(name)
  end
end
```
