### ISSUE TITLE
Merge traits on sub-factories?

### ISSUE THREAD

**Issue by rogercampos** [thoughtbot/factory_bot#1356]
### Steps to reproduce

Given the following factories:

```ruby
FactoryBot.define do
  factory :user, class: 'User' do
    email { "foo@cuca.com" }

    trait :one do
      first_name { "jon" }
    end
  end

  factory :sub_user, parent: :user do
    trait :one do
      last_name { "doe" }
    end
  end
end

a = FactoryBot.build :sub_user, :one
# a.first_name => nil
# a.last_name => "doe"
```

### Expected behavior

I would expect the object to have both `first_name` and `last_name` defined. Only in case both factories define the same attribute, the one from `sub_user` would be used and the other ignored.

### Actual behavior

`first_name` is nil. Only the trait definition on the sub_factory gets used.

### System configuration
**factory_bot version**:  5.0.2
**ruby version**:  2.5.3

---

I have a use case with factories creating products, which are complex models. I have two kind of products, as subclasses of a generic `Product` class. Both of them need a `publishable` trait, which prepares the products to be directly "publishable". This trait does many things, and needs to do some specific things for each subclass as well. Same happens with other traits.

I expected the traits to be "merged" to accomplish this, in sub-factories, but I found they get replaced instead. Is there any other way to approach this?

Thanks.

**Comment by composerinteralia** [comment]
Thanks for the issue. This reminds me a bit of https://github.com/thoughtbot/factory_bot/issues/968. Traits do behave in unexpected ways sometimes, and I have thoughts about reworking them to address some of these problems.

**Comment by composerinteralia** [comment]
I occurs to me there probably is a workaround here, which is to name the traits different things and then call one from the other:

```rb
FactoryBot.define do
  factory :user, class: 'User' do
    email { "foo@cuca.com" }

    trait :one do
      first_name { "jon" }
    end
  end

  factory :sub_user, parent: :user do
    trait :sub_one do
      one
      last_name { "doe" }
    end
  end
end

**Comment by composerinteralia** [comment]
I am going to close this issue for now. At least with the current way that traits work, the child factory overriding the parent's trait with the same name is the expected behavior. There may be room to change this behavior, or provide a way to opt-in to inheriting from the parent's trait (along the lines of a call to `super`), but I think we can consider that as part of the larger project of changing the internals of traits, currently tracked in https://github.com/thoughtbot/factory_bot/issues/968.

Thank you!
