### ISSUE TITLE
Trait applied twice if it's both a default trait and passed explicitly to constructor

### ISSUE THREAD

**Issue by goalaleo** [thoughtbot/factory_bot#1359]
### Steps to reproduce
Given this factory with a default trait
```
  factory :parent do
    with_children # default trait
    
    trait :with_children do
      transient do
        children_count { 1 }
      end

      after(:create) do |parent, evaluator|
        children = create_list(:child, evaluator.children_count)
        parent.add_children(*children)
      end
    end
  end
```
### Expected behavior
Expected
```
create(:parent, :with_children, children_count: 1)
```
to create a parent with 1 child
### Actual behavior
The trait is applied twice, and the parent is created with 2 children.
If the extra `:with_children` argument is omitted, or if the default trait is removed from the factory definition, then it will works as expected.

This is kind of my own fault as I forgot about the default trait, but still I found the behaviour strange.

### System configuration
**factory_bot version**:  5.0.2
**rails version**:  5.2.3
**ruby version**:  2.6.2

**Comment by composerinteralia** [comment]
I was not able to produce the error with this script. Can you update the script to reproduce the problem? Thanks!

```rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "factory_bot", "~> 5.0"
end

require "factory_bot"
require "minitest/autorun"
require "logger"

class Parent
  attr_reader :children

  def add_children(*children)
    @children = children
  end
end

class Child
end

FactoryBot.define do
  skip_create

  factory :child

  factory :parent do
    with_children # default trait

    trait :with_children do
      transient do
        children_count { 1 }
      end

      after(:create) do |parent, evaluator|
        children = create_list(:child, evaluator.children_count)
        parent.add_children(*children)
      end
    end
  end
end

class FactoryBotTest < Minitest::Test
  def test_factory_bot_stuff
    parent = FactoryBot.create(:parent, :with_children, children_count: 1)

    assert_equal 1, parent.children.length
  end
end
```

If it relies on ActiveRecord specifically you can use https://raw.githubusercontent.com/thoughtbot/factory_bot/master/.github/REPRODUCTION_SCRIPT.rb

**Comment by composerinteralia** [comment]
I'm going to close this. Feel free to reopen if you are able to provide a reproduction script. Thanks!
