### ISSUE TITLE
Inherited Factories With Accessors on Subclasses Result in NoMethodError

### ISSUE THREAD

**Issue by sshaw** [thoughtbot/factory_bot#1365]
### Steps to reproduce

```rb
class Foo < ActiveRecord::Base
end

class Bar < Foo
  attr_accessor :xxx
end

factory :foo do
  name { "some name" }
end

factory :bar do
  xxx { "yyy" }
end

# Works fine
build(:bar)
```

But, when `factory :bar` is changed to

```rb
factory :bar, :parent => :foo do
  xxx { "yyy" }  
end
```

`build(:bar)` results in:

```
NoMethodError (undefined method `xxx=' for #<Foo:0x00007fbef69d8688>)
```

### Expected behavior

It should not assume that the method exists on the parent class, it should set it on the subclass the factory's for.

### System configuration

**factory_bot version**:

4.8.2

But took a look at NEWS file and did not see updates for 5.X

**rails version**:

5.2.3

**ruby version**:

2.5

**Comment by composerinteralia** [comment]
Thanks for the issue. `factory :bar, :parent => :foo` building a `Foo` is the expected behavior. If you want a child factory to build a different type of object than the parent factory you can pass in a `class` option: `factory :bar, parent: :foo, class: Bar`.

**Comment by sshaw** [comment]
Ah yes, it's not the _class_ inheritance hierarchy, it's the _factory_ inheritance hierarchy. Thanks.
