### ISSUE TITLE
Transient Support for initialize_with

### ISSUE THREAD

**Issue by allcentury** [thoughtbot/factory_bot#1367]
### Steps to reproduce

```ruby
factory :my_factory, class: ProtoClass do
  trait :error do
    summary { "this failed" }
    error do
      {
        name: "INVALID_REQUEST",
        details: [
          {
            field: "The Response Type is not supported",
            value: "",
          },
        ],
      }
  end
  
  transient do 
    with_encoding { true }
  end

  initialize_with do
    # here I would like to toggle encoding w/ a transient
    Base64.encode64(
      ProtoClass
      .decode_json(attributes.deep_stringify_keys.to_json)
      .to_proto,
    )
  end
end

```

### Expected behavior

This works [as the docs describe](https://github.com/thoughtbot/factory_bot/blob/6fddc456738185d1f7728b5e1a53afa1ce16a2f6/GETTING_STARTED.md#custom-construction), transients are ignored in `initialize_with`. 

> This will build a hash of all attributes to be passed to new. It won't include transient attributes, but everything else defined in the factory will be passed (associations, evaluated sequences, etc.)

### Actual behavior

I would like to have a conversation to see if this feature can be supported or understand why `transient` is omitted.

**Comment by allcentury** [comment]
I instead created a wrapper class here that took an encoding flag and the proto as an argument.  It returned a serialized proto via `#to_proto`.  I now have 2 factories but I think that's fine, thanks for the :rubber-duck:

**Comment by dmitry** [comment]
Any reason not to pass `transient` data into the `initialize_with` block?
