### ISSUE TITLE
Unset or override default trait

### ISSUE THREAD

**Issue by axelson** [thoughtbot/factory_bot#1369]
Is it possible to unset or override a default trait?

This is especially important where a default trait uses an `after` callback.

**Comment by composerinteralia** [comment]
I don't think there is any way to unset a default trait.

As it sounds like you have discovered, a callback in a default trait definition is effectively the same as a callback in the factory definition itself. In either case there is no way to skip that callback.

If there is a callback you want applied only some of the time, you would need to put that in a non-default trait and use that trait when you specifically want that callback to run.

Or, alternatively, you could get clever with transient attributes:

```rb
FactoryBot.define do
  factory :object do
    transient do
      # with_callback defaults to true
      with_callback { true }
    end

    after :build do |_, evaluator|
      # Only run the callback code if with_callback is true
      if evaluator.with_callback
        puts "Built object with a callback"
      end
    end
  end
end
```

That would allow you to have the callback by default, but then disable it by passing `with_callback: false`.

**Comment by axelson** [comment]
Okay, I'll work around it in the after build hook. Thanks for the clarification and workaround.

**Comment by fridaland** [comment]
@axelson thanks for this issue! 

As @composerinteralia described - a default trait definition is effectively the same as a callback in the factory definition. Since this work around seems to be the ideal solution for your particular use case, I'll be closing this issue.
