### ISSUE TITLE
`validates_associated` causes associations not to be properly set

### ISSUE THREAD

**Issue by agatheblues** [thoughtbot/factory_bot#1371]
### Steps to reproduce

```
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "factory_bot", "~> 5.0"
  gem "activerecord"
  gem "sqlite3"
end

require "active_record"
require "factory_bot"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :profiles, force: true do |t|
    t.string :name
  end
  create_table :languages, force: true do |t|
    t.string :title
  end
  create_table "languages_profiles", id: false, force: :cascade do |t|
    t.bigint "profile_id", null: false
    t.bigint "language_id", null: false
  end
end

class Language < ActiveRecord::Base
  has_and_belongs_to_many :profiles
end

class Profile < ActiveRecord::Base
  has_and_belongs_to_many :languages
  validates_associated :languages               # <--- Problematic line
end

FactoryBot.define do
  factory :language do
    title { "" }
  end

  factory :profile do
    name { "John Doe" }

    factory :profile_with_languages do
      after(:create) do |profile|
        create_list(:language, 5, profiles: [profile])
      end
    end
  end
end

class FactoryBotTest < Minitest::Test
  def test_factory_bot_stuff
    p = FactoryBot.create(:profile_with_languages)

    assert_equal 5, p.languages.length
    # assert_equal 5, Profile.first.languages.length
  end
end
```

### Expected behavior
The profile should get 5 languages associated.

### Actual behavior
The profile gets 0 languages associated. If you comment out the `validates_associated` line, then everything works fine.

Also, fun fact, if you do this:

```
 after(:create) do |profile|
     profile.languages = create_list(:language, 5, profiles: [profile])
 end
```

Then the languages are inserted twice in the DB (so, 10 are created, with different object IDs).

### System configuration
**factory_bot version**:  5.1.1
**rails version**:  5.2.3
**ruby version**:  2.5.3p105

This is not anything urgent for me, but I thought this is an interesting bug, and if you have any idea why this happened, I'd be glad to know! Thanks for you work and your time ❤️

**Comment by composerinteralia** [comment]
Thanks for the reproduction script! I have seen some version of this before (I will see if I can track down the previous issue later). Adding `profile.reload` after `create_list(:language, 5, profiles: [profile])` should get this working.

This may come up more in a factory_bot context because of `create_list`, but it is not strictly a factory_bot issue. Replacing:

```rb
p = FactoryBot.create(:profile_with_languages)
```

and creating the object without factory_bot:

```rb
p = Profile.create!
5.times { Language.create!(profiles: [p]) }
```

would give you the same error.
