### ISSUE TITLE
Model's `dependent` option is ignored when association objects are referred in callbacks

### ISSUE THREAD

**Issue by jagaapple** [thoughtbot/factory_bot#1372]
### Steps to reproduce
Firstly, a parent model has associated models and set `dependent` option to `:destroy` like the following.

```rb
# /app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
end
```

Then, refers or updates associated model objects of the parent model in its factory definition file.

```rb
# /spec/factories/posts.rb
FactoryBot.define do
  factory :post do
    after(:build) do |post|
      p post.comments
    end

    title { "xxx" }
  end
end
```

In this case, even if the parent model object is destroyed, children are not deleted, but child objects have the parent model object ID as foreign key. If you configure associations in a parent object or do not refer child objects in any callbacks, children will be deleted expectedly.

```rb
# /spec/models/post_spec.rb
describe Post do
  context "when a post which has comments is destroyed" do
    let!(:post) { create(:post, id: 123) }
    let!(:comments) { create_list(:comment, 3, post: post) }

    it "should destroy associated comments" do
      expect { post.destroy! }.to change { Comment.count }.by(-comments.count) # FAILED!!

      p comments.pluck(:post_id) # [123, 123, 123]
    end
  end

  context "when a post which has comments is destroyed (a different way)" do
    let!(:post) { create(:post, id: 123, comments: comments) }
    let!(:comments) { create_list(:comment, 3) }

    it "should destroy associated comments" do
      expect { post.destroy! }.to change { Comment.count }.by(-comments.count) # SUCCEEDED!!
    end
  end
end
```

### Expected behavior
The child objects are deleted following model's `dependent` option.

```rb
# /spec/models/post_spec.rb
describe Post do
  context "when a post which has comments is destroyed" do
    let!(:post) { create(:post, id: 123) }
    let!(:comments) { create_list(:comment, 3, post: post) }

    it "should destroy associated comments" do
      expect { post.destroy! }.to change { Comment.count }.by(-comments.count) # SUCCEED
    end
  end
end
```

### Actual behavior
```rb
# /spec/models/post_spec.rb
describe Post do
  context "when a post which has comments is destroyed" do
    let!(:post) { create(:post, id: 123) }
    let!(:comments) { create_list(:comment, 3, post: post) }

    it "should destroy associated comments" do
      expect { post.destroy! }.to change { Comment.count }.by(-comments.count) # SUCCEED
    end
  end

  context "when a post which has comments is destroyed (a different way)" do
    let!(:post) { create(:post, id: 123, comments: comments) }
    let!(:comments) { create_list(:comment, 3) }

    it "should destroy associated comments" do
      expect { post.destroy! }.to change { Comment.count }.by(-comments.count) # SUCCEED
    end
  end
end
```

### System configuration
**factory_bot version**:  5.1.1
**rails version**:  6.0.2
**ruby version**:  2.6

**Comment by entcheva** [comment]
Hi @jagaapple - @composerinteralia and I reproduced this issue using the [reproduction script](https://gist.github.com/entcheva/22b7ee4181654d5e35036d9bb31c6eb3). It looks like this issue is also present when creating a test without using FactoryBot, suggesting it's a Rails issue. 

Notably, these tests only fail when introspecting on the comments in between build and save, suggesting it could be related to ActiveRecord association caching. 

What was your goal in referring to `post.comments` in `after(:build)`? Would there be a way to work around that using `after(:create)` instead?

We also ran these tests again Rails master and saw the same failures. A good next step here could be opening an issue against Rails.

**Comment by jagaapple** [comment]
@entcheva 
Thank you for your confirmation!

In our project using PostgreSQL, some models have `<CHILD_MODEL_NAME>_order_ids` array-type column in order to get and sort CHILD_MODEL records. (In general, to use other methods such as linked list is better to do them, but using array-type column is possible to rearrange using only one query, so I like this method.) In this case, we don't need to set both of child model objects and `<CHILD_MODEL_NAME>_order_ids` if this bug doesn't exist.

```rb
# Normally
build(:account, pinned_items: items, pinned_item_order_ids: items.map(&:id))

# Ideal
build(:account, pinned_items: items)
```

However this bug exists in Active Record as you said, so we'll find and use alternative ways. If you need to close this issue, please do it. 😢
