### ISSUE TITLE
[Feature] Do not depend on ActiveSupport

### ISSUE THREAD

**Issue by qortex** [thoughtbot/factory_bot#1376]
Would it be a big effort to drop dependency on ActiveSupport?

I'd like not to pull this dependency in my Ruby-only project.

**Comment by composerinteralia** [comment]
Thanks for the issue!

See #903. The short version is that we are not likely to drop ActiveSupport.

**Comment by qortex** [comment]
Sorry didn't see this issue.
Understood, closing this issue.
