### ISSUE TITLE
has_one :through Association

### ISSUE THREAD

**Issue by YassineDM** [thoughtbot/factory_bot#1392]
If we take following example from Rails guides:
```ruby
class Supplier < ApplicationRecord 
  has_one :account
  has_one :account_history, through: :account
end
class Account < ApplicationRecord
  belongs_to :supplier
  has_one :account_history
end
class AccountHistory < ApplicationRecord
  belongs_to :account
end
```
And create corresponding factories:
```ruby
FactoryBot.define do
  factory :supplier do
    account
  end
  factory :account do
    account_history
  end
  factory :account_history do
  end
end
```

This is working:
```ruby
build(:supplier).account.account_history
```
But this is not:
```ruby
build(:supplier).account_history
```
How to make it work?

**Comment by composerinteralia** [comment]
Thanks for the issue. Please provide a [reproduction script in this format](https://github.com/thoughtbot/factory_bot/blob/master/.github/REPRODUCTION_SCRIPT.rb) so we can run your example and explore what is going on.

**Comment by composerinteralia** [comment]
Under the hood factory_bot builds your objects with:

```rb
    supplier = Supplier.new
    account = Account.new
    account_history = AccountHistory.new
    account.account_history = account_history
    supplier.account = account
```

If you run these lines without using factory_bot at all you will see that `supplier.account_history` is `nil`. So this is a Rails issue, rather than a factory_bot one.
