### ISSUE TITLE
Philosophy question, override sequence unique key.

### ISSUE THREAD

**Issue by j3ck** [thoughtbot/factory_bot#1393]
Hello.
In my case, im try to overrides sequence attribute for unique filed.
Example:
```
FactoryBot.create(:model, sequence_uniq_attribute: 5)
```
then
if i call FactoryBot.create(:model) - 5 times, for the 5'th time it will generate sequence_attribute: 5 but it already exists in database and i will get duplication error.

How can i avoid this situations, maybe there are some best practices like - ' not override sequence attributes' ?

**Comment by composerinteralia** [comment]
This is not something I recall running into, so I don't have much advice here. Could share more about your use case—what is the attribute, what does your factory definition look like, and what are you trying to do when you override it?

You can also [set the starting value for a factory_bot sequence](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#initial-value), if that helps at all.

**Comment by j3ck** [comment]
@composerinteralia Thank you for response



DB schema
```sql
CREATE TABLE public.trackers (
    id integer NOT NULL,
    tracker_code integer NOT NULL
);

CREATE SEQUENCE public.trackers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.trackers_id_seq OWNED BY public.trackers.id;

ALTER TABLE ONLY public.trackers ALTER COLUMN id SET DEFAULT nextval('public.trackers_id_seq'::regclass);

CREATE UNIQUE INDEX index_trackers_tc ON public.trackers USING btree (tracker_code);
```
factory definition
```ruby
FactoryBot.define do
  factory :tracker do
    sequence(:tracker_code, 1)
  end
end
```
Rspec case usage
```ruby
require 'spec_helper'

describe Tracker do
  let!(:default_tracker) { FactoryBot.create(:tracker, tracker_code: 5) }

  context 'test tracker' do
    it {}
  end

  context 'another test tracker' do
    let!(:tracker) { FactoryBot.create(:tracker) }

    it '1' do
    
    end

    it '2' do

    end

    it '3' do

    end

    it '4' do

    end

    it '5' do

    end
  end
end
```

output
```bash
.....F

Failures:

  1) Tracker another test tracker 5
     Failure/Error: let!(:tracker) { FactoryBot.create(:tracker) }

     Sequel::UniqueConstraintViolation:
       PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_trackers_tc"
       DETAIL:  Key (tracker_code)=(5) already exists.
     # ------------------
     # --- Caused by: ---
     # PG::UniqueViolation:
     #   ERROR:  duplicate key value violates unique constraint "index_trackers_tc"
     #   DETAIL:  Key (tracker_code)=(5) already exists.

Finished in 1.12 seconds (files took 1.07 seconds to load)
6 examples, 1 failure
```

**Comment by composerinteralia** [comment]
With the code given in your example there isn't a reason for `default_tracker` to have `tracker_code` set to `5`, so in this particular case I would prefer replacing:

```rb
FactoryBot.create(:tracker, tracker_code: 5)
```

with

```rb
FactoryBot.create(:tracker)
```

If the number 5 is in some way significant, could you also share the relevant lines from the test case?

**Comment by j3ck** [comment]
Now replaced it 
```
let(:default_tracker) { FactoryBot.create(:tracker, tracker_code: 5) }
```
to 
```
let(:default_tracker) { FactoryBot.create(:tracker) }
let!(:default_tracker_code) { default_tracker.tracker_code }
```
I use default_tracker_code below, it's work fine. 

But i'm thinking, should FactoryBot have some protection from sequence fields overrides? Because sequence always used to get unique values.
Mb something like `sequence(:name, 1, uniq: true)` to force ignore override value ?

**Comment by composerinteralia** [comment]
Since this is not something that has come up before, I am hesitant to introduce additional code to prevent it at this point. What do you think about adding a note to the documentation along the lines of: "When working with uniqueness constraints, be careful not to pass in override values that conflict with the generated sequence values."

**Comment by composerinteralia** [comment]
I added a note to the documentation in 218eb72 and will close this issue for now.
