### ISSUE TITLE
Documentation isn't on Rubygems

### ISSUE THREAD

**Issue by tmcw** [thoughtbot/factory_bot#1394]
### Description

From the readme, the line is

> You should find the documentation for your version of factory_bot on Rubygems.

I'd read this as API documentation, or user documentation, or some other sort of documentation. I click through to the [Rubygems page for FactoryBot](https://rubygems.org/gems/factory_bot), though, and there's nothing of that sort. It _does_ give copy & pasteable ways to copy the Gemfile syntax for installing this gem, but that's – as far as I can tell – the only kind of documentation you can find there.

### Reproduction Steps

Click through to Rubygems.org from the README.

### Expected behavior

There should be documentation on Rubygems

### Actual behavior

There isn't documentation on Rubygems. The getting started guide appears to be the main narrative source of documentation.

**Comment by composerinteralia** [comment]
Thanks for the issue. I see a link to [documentation for v5.1.2](https://rubygems.org/gems/factory_bot/versions/5.1.2) but that seems to have been replaced by a [changelog link for v5.2.0](https://rubygems.org/gems/factory_bot/versions/5.2.0). He added the changelog link in https://github.com/thoughtbot/factory_bot/commit/0bcb6151b884d421ef4e7d840c1b098e6ca74d97#diff-ff1a92cd12d8179e487b79302e7e9316, but I did not expect that to remove the documentation link. Hmm....

In the meantime, https://www.rubydoc.info/gems/factory_bot/5.2.0 is the link to documentation for 5.2.0.

**Comment by composerinteralia** [comment]
This should be fixed with the next release.
