### ISSUE TITLE
(docs) JRuby note very old

### ISSUE THREAD

**Issue by olleolleolle** [thoughtbot/factory_bot#1395]
### Description

This section on JRuby mentions _very_ old JRuby things.

https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#jruby

### Expected behavior

I expect JRuby not be mentioned specially at all.

### Actual behavior

We have this old note.

### System configuration
**factory_bot version**:  `master`
**rails version**:  
**ruby version**:

**Comment by composerinteralia** [comment]
Thanks! Yup, we should definitely remove that.

**Comment by volfgox** [comment]
You mean JRuby things in that document is no longer needed and should be removed?
