### ISSUE TITLE
Tests are getting slower and slower until the system crashes

### ISSUE THREAD

**Issue by oanstein** [thoughtbot/factory_bot#1411]
### Description

Since update 6.0.0 my system (AWS Cloud 9 cloud-based IDE) crashes after about 100 tests. The tests are getting slower and slower, from which I suspect a memory leak. Especially since I get the message that I have no more memory.

Version 5.2.0 works. Does anyone else have these problems?

### Reproduction Steps

I use for testing: 

- factory_bot_rails
- rspec-rails
- shoulda-matchers
- database_cleaner-active_record
- byebug
- bullet
- timecop
- faker

### Expected behavior

No crashes

### Actual behavior

System crashes

### System configuration
**factory_bot_rails version**:  6.0.0
**factory_bot version**:  6.0.0
**rails version**:  6.0.3.2
**ruby version**: 2.6.5

**Comment by composerinteralia** [comment]
Many thanks for reporting this so quickly. I released 6.0.2 with the fix from #1412. Could one of you confirm that you are now able to run your test suite without setting `FactoryBot.automatically_define_enum_traits = false`?

**Comment by oanstein** [comment]
> Many thanks for reporting this so quickly. I released 6.0.2 with the fix from #1412. Could one of you confirm that you are now able to run your test suite without setting `FactoryBot.automatically_define_enum_traits = false`?

It's working again now without changing the setting. Thanks
