### ISSUE TITLE
A way to reset FactoryBot inside a running Process (Clearing traits, callbacks and sequences)

### ISSUE THREAD

**Issue by grantspeelman** [thoughtbot/factory_bot#1429]
### Problem this feature will solve

Allow a way of reloading all factories, traits, callbacks and sequences.

We have a gem that allows you to use `factory_bot` with integration tests that run using cypress. https://github.com/shakacode/cypress-on-rails
We basically load `factory_bot` into a running server and every time a factory file is changed we reload all the factories inside the running process by first clearing everything and then loading the factory files again.

This is what the code looked like that clears everything
```ruby
FactoryBot.factories.clear
FactoryBot.traits.clear
FactoryBot.callbacks.clear
FactoryBot.sequences.clear
```

### Desired solution

Would like a way to reset the entire FactoryBot so that we can reload the factory files inside a running process.

```ruby
FactoryBot.reset
```

## Alternatives considered

We looking at changing our code to do the following in the meantime so that our gem works with v6 of `factory_bot` but this is of course not ideal and would prefer a solution that would avoid touching internals.
```ruby
FactoryBot.factories.clear
FactoryBot::Internal.traits.clear
FactoryBot::Internal.callbacks.clear
FactoryBot::Internal.sequences.clear
```

**Comment by composerinteralia** [comment]
[`FactoryBot.reload`](https://github.com/thoughtbot/factory_bot/blob/master/lib/factory_bot/reload.rb) sounds like what you might want here.

**Comment by grantspeelman** [comment]
Awesome, thank you!
