### ISSUE TITLE
Interconnected Associations: instance is nil in inline-defined associations, at least in the build-strategy.

### ISSUE THREAD

**Issue by Shigawire** [thoughtbot/factory_bot#1430]
### Description

In association definitions,  the `instance` method should provide access to the current object. However, using the inline-format of specifying associations, inside the block `instance` is always nil. As we are using FactoryBot to mock immutable objects (see solution below), this may have some unexpected consequences.

### Reproduction Steps

Our factories populate `dry-struct` objects (https://dry-rb.org/gems/dry-struct/1.0/). To work around immutability of these objects, we are using a quirk described in another blog post (https://selleo.com/til/posts/g173snp89l-factorybot-constructing-objects-using-drytypes) and also the documentation, as FactoryBot calls <Object>.new to instantiate the object and then subsequently assigns its attributes.

```ruby
FactoryBot.define do
  factory :base, class: BaseFactory do
    skip_create

    # https://selleo.com/til/posts/g173snp89l-factorybot-constructing-objects-using-drytypes
    initialize_with { new(attributes) }
  end
end
```

Now as we are having interconnected associations (even though we are not using ActiveRecord), I would like to use the options provided (https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#overriding-attributes):

```ruby
FactoryBot.define do
  factory(:person), parent: :base do
    # other attribute definitions go here

    # an association that should inject the parent instance into the associated model as `member_contact`
    household_membership { build :household_membership, member: instance }
    household_membership { association :household_membership, member: instance }
  end
end
```

However, `instance` is always `nil`. As far as I understood, `association(...)` is primarily to be used with ActiveRecord models, as it also aliases the object's `_id` attribute. Thus, we also tried `build(...)`. Same results.

We also use FactoryBot (although version 4) in another project that uses ActiveRecord, and the `@instance` variable (Version 4 does not expose the variable publicly, yet) is set, as expected.

Maybe someone is able to shed a bit of light on why actually `instance` is not populated in our case. I suspect it to be due to our way applying `initialize_with(...)` or not "pulling through" and only using the build-strategy...

### Expected behavior

The  `instance`-variable is nil within inline-associations.

### Actual behavior

The  `instance`-variable should not be nil within inline-associations.

### System configuration
**factory_bot version**:  6.1.0
**rails version**:  none
**ruby version**: 2.6.3.

**Comment by composerinteralia** [comment]
Thanks for the report! I'll try to take a look later this week. `instance` was only officially added to the public API recently, so it is quite possible there are still some kinks to work out.

**Comment by composerinteralia** [comment]
Ah yes, this makes sense now. This does indeed have to do with the fact that you are using `initialize_with`, and specifically that you are using `attributes` in `initialize_with`.

`attributes` includes all the non-transient attributes on the factory, including associations. Since you are using `attributes` to instantiate the object, we need to get the values for all the attributes **before** the object instance exists. When we get to the association, `instance` is `nil` because we need the association itself to build `instance`. Does that make sense?

The normal behavior in factory_bot is to build the instance, then assign all the attributes afterward, which it sounds like you are not able to do with `dry-struct`.

I think the right thing to do here is to add a note in the documentation that `instance` is not compatible with `initialize_with { new(attributes) }`.

**Comment by Shigawire** [comment]
Dear @composerinteralia, thank you so much for the detailed reply and looking into this matter. This definitely clears up some issues on our end.

If okay for you I'll open a PR adjusting the documentation accordingly?

**Comment by composerinteralia** [comment]
Yes, I would be most grateful if you would open a PR to adjust the documentation. Thanks!

**Comment by composerinteralia** [comment]
Forgot to close this one. Looks like it was resolved with a change to the docs.
