### ISSUE TITLE
Rename this project

### ISSUE THREAD

**Issue by davividal** [thoughtbot/factory_bot#1441]
Following on #1148 and #1204 I ask you to rename this project.

Bot comes from Robot.
And Robot means "forced laborer": https://en.wikipedia.org/wiki/Robot#Origin_of_the_term_'robot'

This would make this project complies with the most recent changes:
https://www.bbc.com/news/technology-53050955
https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/
https://www.cnet.com/news/microsofts-github-is-removing-coding-terms-like-master-and-slave/

https://github.com/phpmyadmin/phpmyadmin/issues/16197
https://github.com/ibm-cloud-docs/RegistryImages/issues/51

Among many other.

I don't have a suggestion though.

**Comment by g13ydson** [comment]
when we change the terms master or slave, we change because there are communities that are offended by those terms. I don't know anyone who is offended by the term BOT.

**Comment by davividal** [comment]
@g13ydson the term "bot" literally means "forced laborer". "Forced laborer" is a "pretty" name for slave.

I'm offended by using a tool named "factory slave".

**Comment by g13ydson** [comment]
@davividal But the term is attributed to a humanoid. this forced labor is done by a humanoid, not a human.

**Comment by davividal** [comment]
The term master/slave is applied on a software. A software is a (state) machine. It is way more abstract than an humanoid slave ("robot"). Still, both are machines.

Still you are saying that I can't say that I'm going to setup a "master/slave mysql", but I can use humanoid slaves.

Forced labor is not ok. It does not matter who is making it.

What about "factory collaborator"?

**Comment by composerinteralia** [comment]
Please read our [code of conduct](https://thoughtbot.com/open-source-code-of-conduct) before contributing to this project. Our reasons for the previous rename are well documented, and we will not tolerate issues opened not in good faith.
