### ISSUE TITLE
Missing **kwargs

### ISSUE THREAD

**Issue by omisei** [thoughtbot/factory_bot#1443]
/Users/deissim/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/decorator.rb:16: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/deissim/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/decorator/invocation_tracker.rb:10: warning: The called method `method_missing' is defined here

**Comment by composerinteralia** [comment]
I should also mention that we did a bunch of work to fix the keyword arg warnings in factory_bot 6.1.0 (https://github.com/thoughtbot/factory_bot/pull/1415), so if you haven't upgraded to that version you may need to do so.
