### ISSUE TITLE
Associations "lost" in transaction

### ISSUE THREAD

**Issue by coding-bunny** [thoughtbot/factory_bot#1450]
### Description

I'm not sure what to write as a better title, but I'm running into a very weird issue. I'll use this block to describe it as detailed as I can.

My application has three basic classes: A User, a Task and a TaskEvent.
For the sake of simplicity, I'm leaving out all the `enum` fields etc:

```ruby
class User < ApplicationRecord
  has_many_attached :uploads

  def self.inkbot
    @inkbot ||= find_by(email: 'inkbot@customink.com')
  end
end

class Task < ApplicationRecord
  belongs_to :assignee, class_name: 'User', optional: true
  has_many :events, class_name: 'TaskEvent'
  has_many_attached :uploads
end

class TaskEvent < ApplicationRecord
  belongs_to :task
  belongs_to :user

  store :data, coder: JSON
end
```
So the structure is pretty straightforward, the only caveat is that when creating a `TaskEvent`, I need to make sure the `Task` and `User` exists, which I am trying to implement in my factories:

```ruby
FactoryBot.define do
  factory :user do
    sequence(:name) { |n| "Test User #{n}" }
    sequence(:email) { |n| "test_user_#{n}@example.com" }
    sequence(:image_url) { |n| "https://example.com/#{n}.jpg" }
    sequence(:inker_id) { |n| n }
    
    # Bunch of Traits

   # To not create duplicate records
   initialize_with do
      User.find_or_initialize_by(email: email, name: name, image_url: image_url, inker_id: inker_id)
    end
  end

  factory :task do
    hot_savers # Because the profile is mandatory, we default to hot_savers
    status { :waiting }
    due_by { 1.day.from_now }

    trait :claimed_then_expired do
      status { :expired }
      assignee { association(:user, :artist) }

      after(:create) do |task, _evaluator|
        create(:task_event, :claimed, task: task, user: task.assignee, inker_id: task.assignee.inker_id)
        create(:task_event, :expired, task: task, user: task.assignee, inker_id: task.assignee.inker_id)
      end
    end
  end

  factory :task_event do
    trait :approved do
      transient do
        note { 'Looks great, thanks!' }
      end

      event_type { :approved }
      data { { note: note } }
      user { association(:user, :ink_bot) }
      inker_id { user.inker_id }
    end
  end
end
```

So this is crucial, but what I am seeing is the following:

* When I run `bundle exec rspec` almost every spec with the transactions fails randomly with the FK issue
* When I run the specific file, the same behavior
* When I run the specs individually one by one it works

So from the above there seems to be some hidden chain that's somehow causing the User to either not be created, or to be removed when and not created again when RSpec is rolling a transaction back.
As far as I am aware, my specs use the recommended `let` statements or `before` blocks to ensure the user actually exists.

### Reproduction Steps

Create a class that opens a transaction, and expects a specific User to exist in the database.
Use this User to just create a TaskEvent object:

```
class Expire < BaseCommand
  def run(task_id:, reason:)
    ActiveRecord::Base.transaction do
      task = Task.find(task_id)

      raise InvalidStateError unless task.waiting? || task.in_progress?

      task_event = task.events.create!(event_type: :expired, data: {reason: reason}, user: User.inkbot, inker_id: User.inkbot.inker_id)
      task.update!(status: :expired)

      TaskEventJob.perform_later(task_event.id) if reason == :timeout
    end
  end
end
```

### Expected behavior

I expect the RSpec test to invoke the class and create the required records

### Actual behavior

MySql2 is throwing Foreign Key errors saying my user doesn't exist.

### System configuration
**factory_bot version**:  6.1.0
**rails version**:  5.2.4.3
**ruby version**: 2.7.1

i know there's probably...a lot of details missing, but this problem seems to occur when I'm trying to upgrade FactoryBot to the 6.x release. We were on the 4.x release before, and I'm aware of the defaults being changed, but our code is adjusted for that.

**Comment by coding-bunny** [comment]
Please let me know if you want specifics about something, and I'll share what I can.
I'd like to understand first of all  WHAT is causing this behavior, as I currently can't even wrap my head around it.

**Comment by coding-bunny** [comment]
## RSpec Tests

This is for example the relevant RSpec test that keeps failing:

```ruby
require 'rails_helper'

RSpec.describe Expire do
  before { create(:user, :ink_bot) }

  it 'moves from waiting to expired state' do
    task = create(:task)

    Expire.new.run(task_id: task.id, reason: :timeout)

    task.reload
    expect(task.events.last).to have_attributes(
                                  event_type: 'expired',
                                  data: {reason: 'timeout'},
                                  user: User.inkbot,
                                  inker_id: User.inkbot.inker_id
                                )

    expect(task).to have_attributes(status: 'expired')
  end

  it 'moves from in_progress to expired state' do
    task = create(:task, :in_progress)

    Expire.new.run(task_id: task.id, reason: :timeout)

    task.reload
    expect(task.events.last).to have_attributes(
                                  event_type: 'expired',
                                  data: {reason: 'timeout'},
                                  user: User.inkbot,
                                  inker_id: User.inkbot.inker_id
                                )

    expect(task).to have_attributes(status: 'expired', assignee: create(:user, :artist))
  end

  it 'accepts order placement as a reason' do
    task = create(:task)

    Expire.new.run(task_id: task.id, reason: :order_placed)

    task.reload
    expect(task.events.last).to have_attributes(
                                  event_type: 'expired',
                                  data: {reason: 'order_placed'},
                                  user: User.inkbot,
                                  inker_id: User.inkbot.inker_id
                                )

    expect(task).to have_attributes(status: 'expired')
  end
end
```

The first 2 tests keep failing about the missing User, the third one however just passes.

**Comment by pirj** [comment]
I guess the problem is that you `perform_later` inside the transaction, and your job executes inline in tests, but probably outside that transaction.
That can hit you on production as well. Problems like this led to a recommendation to schedule jobs from `after_commit` and gems like [`isolator`](https://github.com/palkan/isolator).

Not sure exactly if it's the root of the problem, but at least I suggest you move `perform_later` out of the transaction and see if the problem is gone.

**Comment by coding-bunny** [comment]
Will give it a test and see what happens.

**Comment by coding-bunny** [comment]
So I've tried moving the code around, but I keep running into the same behavior. The issue is not related to the enqueu'd job, it's really when trying to make an association object using the factories :

```ruby
class Expire < BaseCommand
  def run(task_id:, reason:)
    ActiveRecord::Base.transaction do
      task = Task.find(task_id)

      raise InvalidStateError unless task.waiting? || task.in_progress?

      task_event = task.events.create!(event_type: :expired, data: {reason: reason}, user: User.inkbot, inker_id: User.inkbot.inker_id)
      task.update!(status: :expired)

      TaskEventJob.perform_later(task_event.id) if reason == :timeout
    end
  end
end
```

The exception is always raised on the creation of the `task_event`, saying it fails to insert a foreign key or user_id.
So the way I understand it is that the User "inkbot" doesn't seem to exist for the inner transaction, despite the object clearly having an ID and existing in the DB. Going to do some more searching why this happens, cause I simply cannot explain the behavior...

**Comment by coding-bunny** [comment]
Found the problem....
cached class instance variable :/
