### ISSUE TITLE
Specifying multiple traits that inherit from the same base trait only invokes the base trait in the context of the last specified trait

### ISSUE THREAD

**Issue by TheDeepestSpace** [thoughtbot/factory_bot#1476]
First of all, thank you very much for this awesome gem.

### Description
Oftentimes I pass traits down to the associated factories. For example, I have the following two structs:
```ruby
Internal = Struct.new(:sticks, :stones)
External = Struct.new(:content)
```
I want to have a factory for `External` that can set `External#content` to an instance of `Internal` with either `Internal#sticks` set to `true`, or `Internal#stones` set to `true`, or both of these attributes set to true. 

First, I create the following basic factories:
```ruby
factory :internal, class: Internal do
  trait :with_sticks do
    sticks { true }
  end

  trait :with_stones do
    stones { true }
  end
end

factory :external, class: External do
  trait :with_content_with_sticks do
    content { build :internal, :with_sticks }
  end

  trait :with_content_with_stones do
    content { build :internal, :with_stones }
  end
end
```
This yields the following interface:
```ruby
a = build :external, :with_content_with_sticks
b = build :external, :with_content_with_stones
c = build :external, :with_content_with_sticks, :with_content_with_stones
```
Which in turn yields the following objects: 
```
(a) #<struct External content=#<struct Internal sticks=true, stones=nil>>
(b) #<struct External content=#<struct Internal sticks=nil, stones=true>>
(c) #<struct External content=#<struct Internal sticks=nil, stones=true>>
```
This works except for the last one. In order to fix this I build a more elaborate factory with a base trait that `with_content_with_sticks` and `with_content_with_stones` inherit from:
```ruby
factory :external_take2, class: External do
  trait :__with_content do
    transient do
      __with_sticks { false }
      __with_stones { false }
    end

    content do
      traits = []
      traits << :with_sticks if __with_sticks
      traits << :with_stones if __with_stones
      build :internal, *traits
    end
  end

  trait :with_content_with_sticks do
    __with_content

    __with_sticks { true }
  end

  trait :with_content_with_stones do
    __with_content

    __with_stones { true }
  end
end
```
However this yields the same output as the above. That is, using both `with_content_with_stones` and `with_content_with_sticks` still yields only one of the traits getting passed down to the `internal` factory. 
### Reproduction Steps
```ruby
require 'bundler/inline'

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "factory_bot", "~> 5.2"
end

require "factory_bot"
require "minitest/autorun"

Internal = Struct.new(:sticks, :stones)
External = Struct.new(:content)

FactoryBot.define do
  factory :internal, class: Internal do
    trait :with_sticks do
      sticks { true }
    end

    trait :with_stones do
      stones { true }
    end
  end

  factory :external, class: External do
    trait :with_content_with_sticks do
      content { build :internal, :with_sticks }
    end

    trait :with_content_with_stones do
      content { build :internal, :with_stones }
    end
  end

  factory :external_take2, class: External do
    trait :__with_content do
      transient do
        __with_sticks { false }
        __with_stones { false }
      end

      content do
        traits = []
        traits << :with_sticks if __with_sticks
        traits << :with_stones if __with_stones

        p "actual traits:   #{traits}"

        build :internal, *traits
      end
    end

    trait :with_content_with_sticks do
      __with_content

      __with_sticks { true }
    end

    trait :with_content_with_stones do
      __with_content

      __with_stones { true }
    end
  end

  # fix the issue by moving transient attributes to the root of the factory
  factory :external_take3, class: External do
    transient do
      __with_sticks { false }
      __with_stones { false }
    end

    trait :__with_content do
      # transient attributes used to be here

      content do
        traits = []
        traits << :with_sticks if __with_sticks
        traits << :with_stones if __with_stones

        p "actual traits:   #{traits}"

        build :internal, *traits
      end
    end

    trait :with_content_with_sticks do
      __with_content

      __with_sticks { true }
    end

    trait :with_content_with_stones do
      __with_content

      __with_stones { true }
    end
  end
end

class FactoryBotTest < Minitest::Test
  include FactoryBot::Syntax::Methods

  def test_it
    p 'expected traits: [:with_sticks, :with_stones]'
    e2 = build :external_take2, :with_content_with_sticks, :with_content_with_stones

    p 'expected traits: [:with_sticks, :with_stones]'
    e3 = build :external_take3, :with_content_with_sticks, :with_content_with_stones

    assert_equal true, e2.content.sticks
    assert_equal true, e2.content.stones

    assert_equal true, e3.content.sticks
    assert_equal true, e3.content.stones
  end
end
```
### Expected behavior
```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using minitest 5.14.3
Using thread_safe 0.3.6
Using bundler 2.2.9
Using concurrent-ruby 1.1.8
Using tzinfo 1.2.9
Using i18n 1.8.9
Using activesupport 5.2.4.5
Using factory_bot 5.2.0
Run options: --seed 34022

# Running:

"expected traits: [:with_sticks, :with_stones]"
"actual traits:   [:with_sticks, :with_stones]"
"expected traits: [:with_sticks, :with_stones]"
"actual traits:   [:with_sticks, :with_stones]"
.

Finished in 0.001732s, 577.2792 runs/s, 1731.8376 assertions/s.

1 runs, 4 assertions, 0 failures, 0 errors, 0 skips
```
### Actual behavior
```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using minitest 5.14.3
Using thread_safe 0.3.6
Using bundler 2.2.9
Using concurrent-ruby 1.1.8
Using i18n 1.8.9
Using tzinfo 1.2.9
Using activesupport 5.2.4.5
Using factory_bot 5.2.0
Run options: --seed 3592

# Running:

"expected traits: [:with_sticks, :with_stones]"
"actual traits:   [:with_stones]"
"expected traits: [:with_sticks, :with_stones]"
"actual traits:   [:with_sticks, :with_stones]"
F

Finished in 0.003142s, 318.2721 runs/s, 318.2721 assertions/s.

  1) Failure:
FactoryBotTest#test_it [factory_bot.rb:111]:
Expected: true
  Actual: nil

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration
**factory_bot version**:  5.2.0
**rails version**:  5.1.7 (the reproduction script is not Rails-specific)
**ruby version**: ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]

### Quick fix

As can be seen in the reproduction script I was able to fix the issue by moving the traits from the trait declaration block to the factory level. 

Another approach would be to simply use the transient attributes instead of the "wrapper" traits. In the context of the reproduction script this would be equivalent of:
```ruby
build :external_take2, :__with_content, __with_sticks: true, __with_stones: true
```

### P.S.

Excuse me for providing such an elaborate description, but I just wanted to make sure that the usecase is clear. The issue seems to be quite minor, and I think that it is only in more extensive factories where this would make a difference in terms of readability.

**Comment by NoahTheDuke** [comment]
The issue you're running into with `external` is that each trait writes over the previous `content` attribute. In `external_take2`, you're doing the same thing: because the `transient` attributes are within the `:__with_content` trait, the implicit `__with_content` attributes in the `:with_content_with_sticks` and `:with_content_with_stones` traits ends up creating two wholly separate sets of transient attributes, and the final one is the one that ends up being used.

It looks like you already have the solution in `:external_take3`, where you've moved the transients outside of the `__with_content` trait so that each `:with_content_with_X` trait correctly sets only one or the other. What is wrong with that approach?

**Comment by TheDeepestSpace** [comment]
@NoahTheDuke Thank you for the quick reply! The approach taken in `:external_take3` did indeed solve my problem. 

It seems like I assumed that transient attributes in the base trait (`__with_content`) would be combined when multiple inheriting traits are being requested. The reason I was hoping to keep transient attributes within the trait definition block is simply out of organizational purposes. That is, `__with_sticks` and `__with_stones` are only relevant to `__with_content` trait.

Judging by your comment my initial assumption is wrong, which nullifies this bug report.
