### ISSUE TITLE
Custom methods available to every factory (extending a module globally)

### ISSUE THREAD

**Issue by ReganRyanNZ** [thoughtbot/factory_bot#1480]
### Problem this feature will solve

I want some code to be executed in multiple factories. The way I have done it is by:

- Making a module
- Extending the module in the factory
- Calling a method from the module inside the factory

e.g.:

```
module FactoryBotEnhancements
  def add_active_trait
    trait :active do
      active { true }
      updated_at { Time.now }
      last_used_by { "System" }
    end
  end
end

FactoryBot.define do
  factory :my_factory do
    extend FactoryBotEnhancements
    add_active_trait

    some_attribute { 42 }
    other_attribute { "hello" }
  end
end

FactoryBot.create(:my_factory, :active)
```
### Desired solution

I would like to extend every factory, so I can call the module's methods in any factory without needing to extend each factory manually.

I.e. instead of:

```
factory :my_factory do
  extend FactoryBotEnhancements
  my_method
end

factory :my_other_factory do
  extend FactoryBotEnhancements
  my_method
end
```

I want simply:

```
factory :my_factory do
  my_method
end

factory :my_other_factory do
  my_method
end
```
## Additional context

Note that this is focused on methods that are called in the factory definition, not in the blocks where values are created. I.e.:

```
factory :my_factory do
  my_method_here

  some_attribute { not_something_here }
end
```

**Comment by ReganRyanNZ** [comment]
I found a way (whether it's recommended by the devs, not so sure):

```
# config/initializers/factory_bot.rb

module FactoryBotEnhancements
  def my_custom_method
    after(:build) do |record|
      puts "whoop"
    end
  end
end

class FactoryBot::DefinitionProxy
  include FactoryBotEnhancements
end
```

Then when defining factories:

```
FactoryBot.define do
  factory :my_factory do
    my_custom_method

    name { "yolo" }
    age { 42 }
  end
end
```

**Comment by composerinteralia** [comment]
Yeah, that's pretty much what other folks have done. Related to https://github.com/thoughtbot/factory_bot/issues/1252. I don't think it was ever officially supported, but enough folks are doing it now that we're not likely to change the behavior, so you should be good.
