### ISSUE TITLE
DEPRECATION WARNING: sequence_by_name is deprecated and will be removed from factory_bot 6.0

### ISSUE THREAD

**Issue by mshenton75** [thoughtbot/factory_bot#1481]
It looks like `sequence_by_name` was deprecated.  Was it replaced by something? Context is I need to be able to rewind a specific sequence.

**Comment by composerinteralia** [comment]
That method was not documented, and was only really meant to be used internally, so we moved it to [FactoryBot::Internal](https://github.com/thoughtbot/factory_bot/blob/18bbc5b5822e32aa8259a1f67fb6296fcf04a2b0/lib/factory_bot/internal.rb#L53-L55). It's now basically private, and could technically change at any time. However, the method has been around for a long time, and it seems pretty stable, so it's probably fairly safe for you to use `FactoryBot::Internal.sequence_by_name`.

This hasn't come up before, so I'm guessing it's a fairly niche use case. If there are broader use cases for `sequence_by_name`, we'll consider moving it back to the public `FactoryBot` module.
