### ISSUE TITLE
Is it possible to log attributes as objects are created? Devise is failing User objects sometimes and we can't figure out why.

### ISSUE THREAD

**Issue by arimendelow** [thoughtbot/factory_bot#1484]
[See here for open issue explaining my bug](https://github.com/heartcombo/devise/issues/5371).

Basically, in order to debug this, I would like to log the user email as it's created so that we can see why it's failing validation.

Thanks!

**Comment by composerinteralia** [comment]
I'd probably start with a [Ruby inspect](https://ruby-doc.org/core-3.0.0/Kernel.html#method-i-p) right where you're creating the Faker email.

```rb
email {  p Faker::Internet.email }
```

FWIW, I don't generally use Faker in tests for this reason. It often leads to mysterious, intermittent errors. For attributes that need to be unique, I stick to factory_bot [sequences](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#inline-sequences).

**Comment by arimendelow** [comment]
Ah! I learn new Ruby features every day :)

Okay, turns out that Devise doesn't support email addresses that have only two letters in the username or domain (this is the regex they use: `/\A(\w+)([\w+\-.]+)(\w+)(@)([a-z\d]+)([a-z\d\-\.]+)([a-z\d]+)(\.)([a-z]{2,})\z/i `).

Using sequences is also a good idea, and a feature that I didn't know existed - thanks! Closing this issue.
