### ISSUE TITLE
use_parent_strategy is not working as expected 

### ISSUE THREAD

**Issue by albertpaulp** [thoughtbot/factory_bot#1494]
### Description

Creating a factory creates associated model(with `strategy: :build`) in database even when `use_parent_strategy` is set as false.

[Documentation](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#build-strategies-1)
### Reproduction Steps
```
FactoryBot.use_parent_strategy = false

FactoryBot.define do
  factory :teacher do
    association :student, strategy: :build
  end

  factory :student do
  end
end

irb(main):016:0> FactoryBot.create(:teacher).student.new_record?
false
```
### Expected behavior

Expectation is to only store `teacher` and `student` should be an in memory object.

FactoryBot.create(:teacher) -> Creates both `teacher` and `student` object in database.

### System configuration
**6.1.0**:  
**Rails 5.2.6**:  
**ruby 2.6.3p62**:

**Comment by composerinteralia** [comment]
Thanks for the issue. Could you put your reproduction steps in [this format](https://github.com/thoughtbot/factory_bot/blob/master/.github/REPRODUCTION_SCRIPT.rb) so it's easier for us to run and debug?

**Comment by albertpaulp** [comment]
@composerinteralia Thanks for checking it out, Github wouldn't let attach .rb files so adding the code below.
I am able to reproduce the bug with below snippet.
```
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "factory_bot", "~> 6.0"
  gem "activerecord"
  gem "sqlite3"
  gem "pry"
end

require "active_record"
require "factory_bot"
require "minitest/autorun"
require "logger"
require 'pry'

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  # TODO: Update the schema to include the specific tables or columns necessary
  # to reproduct the bug
  create_table :masters do |t|
  end
  create_table :students do |t|
    t.references :master, foreign_key: true
  end
end

# TODO: Add any application specific code necessary to reproduce the bug
class Master < ActiveRecord::Base
end

class Student < ActiveRecord::Base
  belongs_to :master
end

FactoryBot.define do
  # TODO: Write the factory definitions necessary to reproduce the bug
  factory :master do
  end
  factory :student do
    association :master, strategy: :build
  end
end

FactoryBot.use_parent_strategy = false
class FactoryBotTest < Minitest::Test
  def test_factory_bot_stuff
    student = FactoryBot.create(:student)
    # master should be an associated factory object to be built in memory
    assert_equal(student.master.new_record?, true)
  end
end
```

**Comment by composerinteralia** [comment]
Thank you, that helps a lot.

factory_bot builds the objects roughly like this:

```rb
    student = Student.new
    teacher = Teacher.new
    student.teacher = teacher
    teacher.save!
    student.save!
```

Specifying `strategy: build` for the teacher association changes that to:

```rb
    student = Student.new
    teacher = Teacher.new
    student.teacher = teacher
    student.save!
```

But when factory_bot saves the student, Rails still automatically saves the associated teacher—thus the behavior you are seeing where it is persisted. If you don't want Rails to do that, you'd need to assign the teacher association _after_ saving the student record:

```rb
    student = Student.new
    student.save!
    teacher = Teacher.new
    student.teacher = teacher
```
To do that in factory_bot you would probably need to get rid of the teacher association in your student factory and assign it separately (either in each place you need it, or maybe in an `after(:create)` callback).

While I can see why this might be a little confusing, it's not really a bug in factory_bot so I'm going to close this issue.
