### ISSUE TITLE
Documentation missing on rubydocs

### ISSUE THREAD

**Issue by brodock** [thoughtbot/factory_bot#1505]
### Description

Readme points people to look for documentation through rubygems.org, which directs them to `rubydoc.info`.

There is currently a problem indexing `factory_bot`, so to anyone looking for documentation, you need to run `yard server --gems` on your local machine as a workaround. (`gem install yard` if you don't have it).

Reported here: https://rubydoc.tenderapp.com/discussions/problems/775-problem-indexing-factory_bot

### Reproduction Steps

1. Try to access https://www.rubydoc.info/gems/factory_bot/6.1.0
2. `Oops, We Couldn't Find That Gem`

### Expected behavior

1. Should have access to gems documentation

### Actual behavior

1. No documentation available online

**Comment by composerinteralia** [comment]
Thanks for the report! I have no idea what's going on there, or what to do about it. The documentation has definitely been there in the past, but it seems to be totally gone for all versions now. I appreciate you opening that rubydoc issue. Hopefully we'll get some clues from that.

**Comment by brodock** [comment]
yep, I've reported the issue to their issue track system, hopefully they will fix this soon.

**Comment by aledustet** [comment]
@brodock did you read anything else from the ticket you opened? I am able to see the documentation on the [route](https://www.rubydoc.info/gems/factory_bot/6.1.0) you mentioned.

**Comment by composerinteralia** [comment]
Seems to be back, so I'll close this for now.
