### ISSUE TITLE
Using gem Faker to set locale by factory

### ISSUE THREAD

**Issue by masterT** [thoughtbot/factory_bot#1506]
### Problem this feature will solve

When I am using [faker](https://github.com/faker-ruby/faker) to generate factory attributes I find it difficult to set the "locale" for all the attributes of the factory.

With `faker` you can set the locale with `Faker::Config.locale = locale` (by default it uses `rails-i18n` locale) and then, when you call the generation methods on `faker` it will generate the output for the [right format for the locale](https://github.com/faker-ruby/faker#customization). 

Ex:

```ruby
FactoryBot.define do
  factory :user do
    # ...
    name { Faker::Name.name }
    postal_code { Faker::Address.postcode }
    phone_number { Faker::PhoneNumber.phone_number }
  end
end
```

For the `phone_number` attribute, `faker` will use the `rails-i18n` key `en.faker.phone_number.formats` (the default locale set is `en`). 

### Desired solution

The feature or change that would solve the problem

I would like to be able to set the `faker` locale for a factory, maybe this would be possible if an `around hook exists, using a transient attribute.

Ex:

```ruby
FactoryBot.define do
  factory :user do
    arround do
      I18n.with_locale(evaluator.locale) do
        yield
      end
    end
    
    transient do
      locale {  I18n.locale }
    end
    
    # ...
    name { Faker::Name.name }
    postal_code { Faker::Address.postcode }
    phone_number { Faker::PhoneNumber.phone_number }
  end
end
```

Then you can easily generate users using locale "fr" and "en-US".

```ruby
attributes_for(:user, locale: "fr")
# => {
          :name => "Dr Thomas Roché",
   :postal_code => "61331",
  :phone_number => "+33 2 55 61 87 68"
}

attributes_for(:user, locale: "en-US")
# => {
          :name => "Elliott Marquardt",
   :postal_code => "29958-7969",
  :phone_number => "520-256-2473"
}
```

## Alternatives considered

Currently, I am setting the locale in the first attribute of the factory, for nested factories, but it's not very elegant...

```ruby
FactoryBot.define do
  factory :user do
    # ...    
    name { Faker::Name.name }
    postal_code { Faker::Address.postcode }
    phone_number { Faker::PhoneNumber.phone_number }
  end
  
  factory :user_fr do
    name { 
      I18n.locale = 'fr'
      Faker::Name.name 
    }
  end
end
```

Another solution is to set the locale before calling the factory, but it makes it very verbose...

```ruby
let(:user) do
  I18n.with_locale('fr') do
    create(:user)
  end
end
```

## Additional context

I would be happy to contribute to this feature if this is something you think is worth adding to the gem. This issue is very close to the gem `Faker` and the fake that you can't specify the "format" you want, for that you need to base the country in the locale.

**Comment by composerinteralia** [comment]
I believe you can get the behavior you are looking for by using a custom [`initialize_with`](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#custom-construction). That should allow you to construct the object and assign the attributes all within the `I18n.with_locale` block:

```rb
  factory :user do
    initialize_with do
      I18n.with_locale(locale) do
        new(attributes)
      end
    end
    
    transient do
      locale {  I18n.locale }
    end
  end
```

**Comment by masterT** [comment]
Nice, thank you for answering, since then I switch to [FFaker](https://github.com/ffaker/ffaker) which does not leverage _i18n_ directly to generate data in a specific language/geo.

I will close the issue.
