### ISSUE TITLE
The reason we still keep bundled with activesupport tightly

### ISSUE THREAD

**Issue by zw963** [thoughtbot/factory_bot#1509]
### Problem this feature will solve

I never use ruby on rails recent years, in fact, i use roda + sequel technical stacks
I don't want to pull activesupport as dependency, but i like to use factory_bot

### Desired solution

Don't add activesupport as runtime dependency.

**Comment by composerinteralia** [comment]
This has come up a couple times over the years. See https://github.com/thoughtbot/factory_bot/issues/903 for past discussion.

**Comment by zw963** [comment]
Thank you for answer,  anyway,  i don't want pull this not necessary gem, i switch to use [fabrication](https://gitlab.com/fabrication-gem/fabrication) for now, if i use rails again, i will consider continue use this gem.
