### ISSUE TITLE
Reorganize documentation

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/factory_bot#1527]
### Problem this feature will solve

Our GETTING_STARTED file is overwhelmingly large. It isn't so much a guide for getting started with factory_bot as complete documentation for every factory_bot feature. Having such a long file makes it difficult to get started, and difficult to find specific documentation once you have gotten started.

### Desired solution

I'd like to see most of this file moved out into a docs/ directory or something, and then GETTING_STARTED can link to that. Then we can keep GETTING_STARTED focused on just that.

## Alternatives considered

It'd be really fancy if there was a site with nicely formatted documentation (perhaps a nice investment time project for someone from thoughtbot?).

**Comment by mike-burns** [comment]
Solved in #1570 .
