### ISSUE TITLE
ArgumentError: wrong number of arguments (given 0, expected 1) - factory_bot ~> 6.2.0

### ISSUE THREAD

**Issue by andregit1** [thoughtbot/factory_bot#1528]

**Comment by composerinteralia** [comment]
This isn't quite enough for me to be able to diagnose the problem, but I can see from the backtrace that it is indeed different from the other issue you had commented on. Can you provide a reproduction script in the format linked to in the issue template you used to open this issue?

Any chance you have a custom `to_create` method in one of your factories?

**Comment by andregit1** [comment]
> This isn't quite enough for me to be able to diagnose the problem, but I can see from the backtrace that it is indeed different from the other issue you had commented on. Can you provide a reproduction script in the format linked to in the issue template you used to open this issue?
> 
> Any chance you have a custom `to_create` method in one of your factories?

just updated my issue template code, about `to_create` method, i never use this one in any spec/factories of my current projects

@composerinteralia

**Comment by composerinteralia** [comment]
Unfortunately I don’t see anything obvious in any of the code you shared. I’d need a script or example application I can run that reproduces the problem to help diagnose further. Right now I don’t understand the problem enough to know what we’d need to change in factory_bot, if anything.
