### ISSUE TITLE
Path collisions `docs/src/{SUMMARY,summary}.md`

### ISSUE THREAD

**Issue by grekko** [thoughtbot/factory_bot#1580]
### Description

When cloning the current repository on a case-insensitive file system git warns about path collisions:

```
git clone https://github.com/thoughtbot/factory_bot.git tmp
…

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'docs/src/SUMMARY.md'
  'docs/src/summary.md'
```

### Reproduction Steps

Create a case sensitive file system and clone the repository:

```
git clone https://github.com/thoughtbot/factory_bot.git tmp
```

### Expected behavior

No issues for users with case-insensitive file systems.

### Proposed changes

The 2 conflicting file paths are:

- `docs/src/summary.md`: An intro describing the contents
- `docs/src/SUMMARY.md`: An index file listing the relevant individual docs

How about renaming `docs/src/summary.md` to `docs/src/readme.md` and renaming `docs/src/SUMMARY.md` to `docs/src/summary.md`.

`docs/src/readme.md` should be read first when looking at the docs.
`docs/src/summary.md` seems to be the default pattern for similar files in sub-directories.

See PR proposal here https://github.com/thoughtbot/factory_bot/pull/1581

**Comment by grekko** [comment]
I hope this does not break any links/references to the documents. I searched for references to `SUMMARY.md` in this repository but there could be external links or other dependencies on the file names 🤔

Maybe those who recently worked on the big docs refactoring have better knowledge and can check if my proposed changes are breaking anything.

**Comment by sarahraqueld** [comment]
Closing as Fixed by https://github.com/thoughtbot/factory_bot/pull/1666 🥳
