### ISSUE TITLE
Using name-spaced models

### ISSUE THREAD

**Issue by ream88** [thoughtbot/factory_bot#199]
Hello folks,

I have Rails projects with name-spaced models. At the moment my factories look like the following with a lot of clutter, because of the name-spaced models:

```
# factories/user.rb
FactoryGirl.define do
  factory(:account, :class => MyProject::User::Account) do
    # ...
  end

  factory(:user, :class => MyProject::User::User) do
    # ...
  end

  # and so on ...
end
```

They are working, though it doesn't feel very DRY. Is (or will be) there any way to define the name-space once? Like the following?

```
FactoryGirl.define(:namespace => MyProject::User) do
  factory(:account) do
    # I'm a MyProject::User::Account class
  end
end
```

**Comment by djnawara** [comment]
FYI, given this class:

```ruby
module ModuleA
  class Foo
    attr_accessor :uuid
  end
end
```

Then this works for me:

```ruby
module ModuleA
  FactoryGirl.define do
    factory :module_a_foo, class: Foo do
      sequence(:uuid) { UUIDTools::UUID.random_create }
    end
  end
end
```

So, in theory, you could do something like this:

```ruby
module ModuleA
  FactoryGirl.define(factory_name_prefix: :module_a) do
    factory :foo, class: Foo do
      sequence(:uuid) { UUIDTools::UUID.random_create }
    end
  end
end

FactoryGirl.build(:module_a_foo)
```

Just a random thought.

**Comment by tf** [comment]
Yes, but this does not solve the problem of having to repeat the, for example, gem name all over the gem codebase. Always having to write `FactoryGirl.build(:some_engine_post)` hinders code mobility and makes extracting engines hard when things originally started out as `FactoryGirl.build(:post)`. This is the sort of duplication I'd like to prevent by adding the scope concept.

**Comment by cec** [comment]
@joshuaclayton I believe that having this in FG would benefit not only engine creators, since namespaced models are not uncommon in non-trivial apps.

@tf Thank you for leading this discussion. 
I believe the scoping idea to be the way to go.
When writing specs for a namespaced models, it would be nice to be able to set the default_scope for those specs individually.

````
module NameSpace
  describe MyModel, type: model, factories_scope: NameSpace do
    #....
  end
end
````
Implementing this would be trivial.

**Comment by mooreniemi** [comment]
I wish I had this now, as I am struggling with a large project with many name-spaces.

**Comment by joshuaclayton** [comment]
I still have a number of concerns around edge cases, implied global state around RSpec blocks, and overhead (see https://github.com/thoughtbot/factory_girl/issues/199#issuecomment-64422463 for history).

I'd love to see people implement this without modifying FG and see what they run into. A few different implementations might all help us understand what issues might arise.

As an example of namespace support with zero modification of FG, please take a look at https://github.com/thoughtbot/factory_girl/commit/524b4463a299f88a9bd732f8471cf33986c94561. This demonstrates default namespaces, namespaces wrapping multiple factories, and automatic name prefixing in instances where the same class name exists under multiple namespaces.

Note that this doesn't handle association prefixes, which I demonstrated in the `Bar` namespace.

**Comment by evgen3d** [comment]
Any progress with it?
I really cant understand why this in discussion a few years already.
Rails Engines is most powerful encapsulation tool and I cant find any solution to make FactoryGirl work with namespaces. 
Joshua, please provide working example of it!
This is not working in my case.
This is in mainapp/spec/factories.rb:
```
FactoryGirl.define do
  factory :eb_user, class: Eb::User do
   # ----
  end
end
```
```
NameError:
       uninitialized constant Eb::User
```
I spend two days already to make it work without any success.
Could you advice any solution? 
Thanks

**Comment by joshuaclayton** [comment]
@evgen3d without access to the codebase, I'm afraid I can't offer much help. Seems this is related to load order (especially if you expect that constant to be available), but I don't have specific guidance here, apart from ensuring the engine is loaded before the factories file is.
