### ISSUE TITLE
Support nested_attributes

### ISSUE THREAD

**Issue by pacoguzman** [thoughtbot/factory_bot#221]
To add values to the nested attributes for some of my Models, I have to do the following

``` ruby
   factory(:avatar) do
     icon 'smiling'
   end

   factory(:user) do
     avatar_attributes { attributes_for(:avatar) }   
   end
```

It'd be wonderful if I could just do:

``` ruby
  factory(:user) do
    avatar_attributes
  end
```

or

``` ruby
  factory(:user) do
    nested_attributes :avatar, :factory => :awesome_avatar, {:icon => 'override_awesome_avatar'}
  end
```

What do you thing about it? By now I've resolved for has_one association but not for has_many associations maybe related with #202

**Comment by ruwhan** [comment]
thanks @pacoguzman , was stuck on this for a day and found this (http://stackoverflow.com/questions/32450502/rspec-factory-girl-build-with-has-many/32468672).
