### ISSUE TITLE
Using traits for an association

### ISSUE THREAD

**Issue by TMaYaD** [thoughtbot/factory_bot#263]
Can not use traits from association

``` ruby
factory :user do
  trait :with_profile do
    name "John Doe"
  end
end

factory :subscription do
  association :user, :traits => [:with_profile]
end
```

Gives the error "undefined method `traits=' for #User:0xced2284"

**Comment by Nowaker** [comment]
Is it still available? Current docs don't mention that.

**Comment by joshuaclayton** [comment]
@Nowaker yep, it's still there, in the [Traits section](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#traits). The commit adding the documentation is here: https://github.com/thoughtbot/factory_girl/commit/c9ed3d88e5aa8d02ffd3e8b63ea80542caee1a01

**Comment by dsandstrom** [comment]
I wanted to use a trait in an association in my factory definition. I'm not sure if things changed, but the syntax suggested here doesn't work.  In case it helps someone else, here is what I got to work:

```ruby
FactoryWhatever.define do
  factory :subscription do
    association :user, factory: :user_factory do
      with_profile
    end
  end
end
```

**Comment by gnfisher** [comment]
@dsandstrom the syntax in the current guide worked for me. In the [Traits](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#traits) section scroll down to the series of examples sections beginning with: **"Traits can be used with associations easily too:"**

```ruby
FactoryBot.define do
  factory :subscription do
    association :user, :with_profile
  end
end
```

**Comment by haanhduclinh** [comment]
@gnfisher Thanks. It works

**Comment by CoderMiguel** [comment]
Looks like the documentation has changed locations and now lives here:
[Traits Documentation](https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md)
