### ISSUE TITLE
NoMethodError: undefined method `attributes'

### ISSUE THREAD

**Issue by sekrett** [thoughtbot/factory_bot#277]
Hello!

I have a `Contact` model:

<pre>class Contact
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  validates :name, :contact, :question, :presence => true

  attr_accessor :name, :contact, :subject, :question

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end</pre>

A factory:

<pre>Factory.define :contact do |f|
  f.name 'my name'
  f.contact 'my contact'
  f.subject 'my subject'
  f.question 'my question'
end</pre>

And then I do:

<pre>Loading test environment (Rails 3.1.3)
>> Factory.build(:contact).attributes
NoMethodError: undefined method `attributes' for #<Contact:0x007f894b42f140>
        from (irb):1
        from /Users/sekrett/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.3/lib/rails/commands/console.rb:45:in `start'
        from /Users/sekrett/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.3/lib/rails/commands/console.rb:8:in `start'
        from /Users/sekrett/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.3/lib/rails/commands.rb:40:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
>></pre>

It works when using old `attributes_for` method.

**Comment by emersona** [comment]
> include ActiveModel::Conversion

 undefined method `has_attribute?' for
