### ISSUE TITLE
Save instances with random ids?

### ISSUE THREAD

**Issue by evgenyneu** [thoughtbot/factory_bot#350]
Is it possible to create and save instances with random IDs, the same way it works in fixtures?

**Comment by BKSpurgeon** [comment]
a question: is there such a method/feature within this gem which can generate unique and random ids as above?

**Comment by composerinteralia** [comment]
Nothing built in that I know of, but you should be able to use one of the solutions suggested in this issue.

**Comment by BKSpurgeon** [comment]
@composerinteralia chrs. i have followed the solutions suggested above.
