### ISSUE TITLE
attributes_for should honor associations defined in the factory

### ISSUE THREAD

**Issue by ghost** [thoughtbot/factory_bot#359]
I've looked over the issues surrounding `attributes_for` (#316, #274, #261) and I think there's still a problem.

As currently documented in [Getting Started](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md), `attributes_for`

```
Returns a hash of attributes that can be used to build a[n ...] instance
```

But as currently implemented, `attributes_for` elides any associations.  For example, if a factory is defined as:

``` ruby
factory :membership do
  user
  club
end
```

... `attributes_for` returns an empty hash:

```
>> FactoryGirl.attributes_for(:membership)
=> {}
```

This is surprising.  @joshuaclayton says that this is to keep `attributes_for` ORM agnostic.  The suggested workaround is to use `build` and `attributes`:

``` ruby
>> FactoryGirl.build(:membership).attributes
=> {"id"=>nil, "user_id"=>3, "club_id"=>6, "created_at"=>nil, "updated_at"=>nil}
```

but this isn't useful for testing.

I'd like to propose that the contract of `attributes_for` is to return a hash of exactly the fields defined in the factory, i.e.:

```
>> FactoryGirl.attributes_for(:membership)
=> {:user_id => 1002, :club_id => 1004}
```

(I naively imagine that you can avoid hitting the DB by calling `build_stubbed` on the associated objects, but I suspect it's more complicated than that.)

**Comment by craigweston** [comment]
One thing I found with @ghosts (thank you btw) approach is that ```FactoryGirl.build(*args).attributes``` will convert ActiveRecord enums into integers in the outputted attributes hash. 

``` "content_type"=>1 ```

If using this for POST params in testing, it will break with something similar to:

```
     Failure/Error: post :create, comment: attributes_with_foreign_keys(:comment)
     ArgumentError:
       '1' is not a valid content_type
```
(given an enum called content_type on the comment model)

This enum conversion difference between the two functions was brought up by @dankohn in [FactoryGirl.attributes converting enum to integer - Issue #680](https://github.com/thoughtbot/factory_girl/issues/680)

> In my company model: enum auth_type: { default: 1, ny: 2 }
> In my company factory: auth_type "ny"
> In rails console:

> [1] pry(main)> FactoryGirl.attributes_for(:company)[:auth_type]
> :ny
> [2] pry(main)> FactoryGirl.build(:company).attributes['auth_type']
> 2

I've added the following to @ghost's code to set the enum attributes back (```"content_type"=>"publication"```), allowing params to continue to work:

```
attrs.each { |k, v| attrs[k] = inst.send(k) if inst.class.defined_enums.has_key?(k) }
```
See below...
```
def attributes_with_foreign_keys(*args)
  inst = FactoryGirl.build(*args)
  attrs = inst.attributes
  attrs.delete_if do |k, v| 
    ["id", "type", "created_at", "updated_at"].member?(k)
  end
  attrs.each { |k, v| attrs[k] = inst.send(k) if inst.class.defined_enums.has_key?(k) }
end
```
Hopefully this helps someone who, like me, is using this method and also has enums defined in their model.

**Comment by sadaf2605** [comment]
Some of you who has come across via google may find this post/code-snippet useful:

https://www.sadafnoor.com/blog/little-hack-to-get-factorygirl-return-more-getpost-friendly-nested-attributes/

**Comment by sadaf2605** [comment]
Or you can use `gem 'nested_attr'`: https://github.com/sadaf2605/nested_attr

**Comment by Shrugs** [comment]
I was looking to create nested attributes (for example, because my model validates the presence of a `has_one` association). I ended up writing this code snippet:

```ruby
  def nested_attributes_for(*args)
    attrs = FactoryGirl.attributes_for(*args)
    klass_name = args.first.to_s.camelize.constantize
    klass_name.reflect_on_all_associations(:has_one).each do |r|
      attrs["#{r.name}_attributes"] = FactoryGirl.attributes_for(r.name)
    end

    attrs
  end
```

So, given a factory definition like 
```
  factory :location do
    name 'Location Name'
    address
  end
```

`nested_attributes_for` returns

```ruby
{:name=>"Location Name",
 "address_attributes"=>
  {:country=>"USA",
   :state=>"New York",
   :city=>"New York",
   :zip_code=> 11001,
   :address_line_one=>"Union Square",
   :address_line_two=>""}}
```

**Comment by Ghosts** [comment]
Every time someone adds an s to @ghost I feel like I'm actually contributing to an important project :)

**Comment by nwshane** [comment]
After stealing @craigweston and @ghost's code snippet above, I was briefly tripped up by the fact that the attribute keys in the hash returned by `attributes_with_foreign_keys` **are strings and not symbols**.

```
person_attr = attributes_with_foreign_keys(:person, name: 'Bob')
person_attr[:name] // returns nil
person_attr['name'] // returns 'Bob'
```

This is different from the FactoryGirl.attributes_for method, which returns a hash with the attribute keys as symbols. I didn't want to deal with that inconsistency, so I tweaked the `attributes_with_foreign_keys` to transform all hash keys to symbols:

```
  def attributes_with_foreign_keys(*args)
    inst = FactoryGirl.build(*args)
    attrs = inst.attributes
    attrs.delete_if do |k, v|
      ["id", "type", "created_at", "updated_at"].member?(k)
    end
    inst.class.defined_enums.each { |k, v| attrs[k] = inst.send(k) }
    return attrs.deep_transform_keys(&:to_sym)
  end
```

**Comment by gosukiwi** [comment]
@nwshane why not just do `.with_indifferent_access`?

**Comment by atz** [comment]
@gosukiwi because the poster wants it to be the same as `attributes_for`.

**Comment by brunofacca** [comment]
Another possible solution is:

`FactoryGirl.build(:foo).attributes.except('id', 'created_at', 'updated_at').symbolize_keys`

**Comment by mbedarff** [comment]
As @joshuaclayton proposed earlier I defined an own strategy `:attributes_with_foreign_keys` that includes the foreign keys in the the hash:
```ruby
module FactoryBot
  module Strategy
    class AttributesWithForeignKeys
      def initialize
        @strategy = FactoryBot.strategy_by_name(:attributes_for).new
      end

      def result(evaluation)
        attributes = @strategy.result(evaluation)

        # iterate over associations defined in factory and find matching belongs_to association in model
        # => don't iterate over belongs_to associations defined in model since there maybe more associations defined in the model than in the factory
        belongs_to_associations = build_class(evaluation).reflect_on_all_associations(:belongs_to)
        get_association_names(evaluation).each do |association_name|
          belongs_to_association = belongs_to_associations.find {|a| a.name == association_name}
          # set id of association target in attributes hash if belongs_to association was found in the model and the attribute was not overridden in the factory
          unless belongs_to_association.blank? || get_overrides(evaluation).include?(association_name)
            target = get_evaluator(evaluation).send(association_name)
            attributes[belongs_to_association.foreign_key.to_sym] = target&.id
          end
        end

        attributes
      end

      def association(runner)
        # restore usage of default strategy defined in factory
        runner.run
      end

      private

        def build_class(evaluation)
          evaluation.instance_variable_get(:@attribute_assigner).instance_variable_get(:@build_class)
        end

        def get_association_names(evaluation)
          evaluation.instance_variable_get(:@attribute_assigner).instance_variable_get(:@attribute_list).associations.names
        end

        def get_evaluator(evaluation)
          @evaluator ||= evaluation.instance_variable_get(:@attribute_assigner).instance_variable_get(:@evaluator)
        end

        def get_overrides(evaluation = nil)
          @overrides ||= get_evaluator(evaluation).instance_variable_get(:@overrides).symbolize_keys
        end
    end
  end

  register_strategy(:attributes_with_foreign_keys, Strategy::AttributesWithForeignKeys)
end
```

In order to work properly the association in the factory needs to use the `:create` strategy. Otherwise there isn't any id to add to the attributes hash.

**Comment by JorgeCoock** [comment]
@joshuapinter The @ghost solution can be included in any part of the documentation ?

**Comment by Dschee** [comment]
Solution of @ghost is working fine for me, I changed a few things though:

1. Added a `_for` at the end to be consistent with the naming of `attributes_for`
2. Updated to the new name of `FactoryBot` (instead of `FactoryLint`)
3. Inclusion through `FactoryBot::Syntax::Methods` instead of an own module limited to controllers

```ruby
module FactoryBot::Syntax::Methods
  def attributes_with_foreign_keys_for(*args)
    FactoryBot.build(*args).attributes.delete_if do |k, v|
      ["id", "type", "created_at", "updated_at"].member?(k)
    end
  end
end

RSpec.configure do |config|
  config.include FactoryBot::Syntax::Methods
end

```

**Comment by danielricecodes** [comment]
Nice @Dschee.  FYI the @ghost is me - BigNerdRanchDan was my old github username :-)

**Comment by jamesst20** [comment]
Something else that could possibly work with belongs_to, has_many and has_one could be something like this. However, keep in mind that in case of belongs_to relationship, it creates a new record, except if the belongs_to match the parent has_many.

spec/support/controller_macros.rb
```
module FactoryBot
  module Syntax
    module Methods
      def nested_attributes_for(*args)
        skip = args[1].delete :_skip if args.length > 1

        attrs = FactoryBot.attributes_for(*args)
        klass_name = args.first.to_s.camelize.constantize

        # Process has_one
        klass_name.reflect_on_all_associations(:has_one).each do |r|
          attrs["#{r.name}_attributes"] = nested_attributes_for(r.class_name.underscore)
        end

        # Process belongs_to
        klass_name.reflect_on_all_associations(:belongs_to).each do |r|
          next if r.name == skip || attrs["#{r.name}_id"].present?

          attrs["#{r.name}_id"] = FactoryBot.create(r.class_name.underscore).id
        end

        # Process has_many
        klass_name.reflect_on_all_associations(:has_many).each do |r|
          next if r.class_name == "PaperTrail::Version"

          attrs["#{r.name}_attributes"] = [nested_attributes_for(r.class_name.underscore, _skip: args[0])]
        end

        attrs
      end
    end
  end
end
```

Models

```
class Expert < ApplicationRecord
  has_paper_trail

  belongs_to :region

  has_many :expert_partners, inverse_of: :expert, dependent: :destroy
  has_many :expert_operating_regions, inverse_of: :expert, dependent: :destroy

  accepts_nested_attributes_for :expert_partners, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :expert_operating_regions, reject_if: :all_blank, allow_destroy: true
end

class ExpertPartner < ApplicationRecord
  has_paper_trail

  belongs_to :expert

  validates :name, presence: true
end

class ExpertOperatingRegion < ApplicationRecord
  has_paper_trail

  belongs_to :expert
  belongs_to :region

  validates :expert, :region, presence: true
end
```

Output
```
{
    "email": "MyString",
    "name": "MyString",
    "region_id": 22,
    "expert_partners_attributes": [
        {
            "name": "MyString"
        }
    ],
    "expert_operating_regions_attributes": [
        {
            "region_id": 23
        }
    ]
}
```

**Comment by davegson** [comment]
### A clean version for the most basic functionality for Rails 5+

This **creates** `:belongs_to` associations and adds their `id` (and `type` if `:polymorphic`)
to the attributes.

**spec/support/factory_bot_macros.rb**

```ruby
module FactoryBot::Syntax::Methods
  def nested_attributes_for(*args)
    attributes = attributes_for(*args)
    klass = args.first.to_s.camelize.constantize

    klass.reflect_on_all_associations(:belongs_to).each do |r|
      association = FactoryBot.create(r.class_name.underscore)
      attributes["#{r.name}_id"] = association.id
      attributes["#{r.name}_type"] = association.class.name if r.options[:polymorphic]
    end

    attributes
  end
end

RSpec.configure do |config|
  config.include FactoryBot::Syntax::Methods
end
```

-------------------------

this is an adapted version of @jamesst20 - kudos to him 👏

**Comment by loqimean** [comment]
> ### A clean version for the most basic functionality for Rails 5+
> This **creates** `:belongs_to` associations and adds their `id` (and `type` if `:polymorphic`) to the attributes.
> 
> **spec/support/factory_bot_macros.rb**
> 
> ```ruby
> module FactoryBot::Syntax::Methods
>   def nested_attributes_for(*args)
>     attributes = attributes_for(*args)
>     klass = args.first.to_s.camelize.constantize
> 
>     klass.reflect_on_all_associations(:belongs_to).each do |r|
>       association = FactoryBot.create(r.class_name.underscore)
>       attributes["#{r.name}_id"] = association.id
>       attributes["#{r.name}_type"] = association.class.name if r.options[:polymorphic]
>     end
> 
>     attributes
>   end
> end
> ```
> 
> this is an adapted [version of @jamesst20](https://github.com/thoughtbot/factory_bot/issues/359#issuecomment-465208154) - kudos to him 👏

```ruby
module FactoryBot::Syntax::Methods
  def nested_attributes_for(*args)
    attributes = attributes_for(*args)
    klass = args.first.to_s.camelize.constantize

    klass.reflect_on_all_associations(:belongs_to).each do |r|
      association = FactoryBot.create(r.class_name.underscore)
      attributes[:"#{r.name}_id"] = association.id
      attributes[:"#{r.name}_type"] = association.class.name if r.options[:polymorphic]
    end

    attributes
  end
end
```

You forgot to add symbol transformation, because of attributes_for returns keys as symbols

**Comment by oniram88** [comment]
> > ### A clean version for the most basic functionality for Rails 5+
> > This **creates** `:belongs_to` associations and adds their `id` (and `type` if `:polymorphic`) to the attributes.
> > **spec/support/factory_bot_macros.rb**
> > ```ruby
> > module FactoryBot::Syntax::Methods
> >   def nested_attributes_for(*args)
> >     attributes = attributes_for(*args)
> >     klass = args.first.to_s.camelize.constantize
> > 
> >     klass.reflect_on_all_associations(:belongs_to).each do |r|
> >       association = FactoryBot.create(r.class_name.underscore)
> >       attributes["#{r.name}_id"] = association.id
> >       attributes["#{r.name}_type"] = association.class.name if r.options[:polymorphic]
> >     end
> > 
> >     attributes
> >   end
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this is an adapted [version of @jamesst20](https://github.com/thoughtbot/factory_bot/issues/359#issuecomment-465208154) - kudos to him 👏
> 
> ```ruby
> module FactoryBot::Syntax::Methods
>   def nested_attributes_for(*args)
>     attributes = attributes_for(*args)
>     klass = args.first.to_s.camelize.constantize
> 
>     klass.reflect_on_all_associations(:belongs_to).each do |r|
>       association = FactoryBot.create(r.class_name.underscore)
>       attributes[:"#{r.name}_id"] = association.id
>       attributes[:"#{r.name}_type"] = association.class.name if r.options[:polymorphic]
>     end
> 
>     attributes
>   end
> end
> ```
> 
> You forgot to add symbol transformation, because of attributes_for returns keys as symbols

don't know if its with new FactoryBot Versions but for finding the correct class I use directly `FactoryBot::Factory#build_class` and so the helper is:

```ruby
module FactoryBot::Syntax::Methods
  def nested_attributes_for(*args)
    attributes = attributes_for(*args)
    klass = FactoryBot::Internal.factory_by_name(args.first).build_class

    klass.reflect_on_all_associations(:belongs_to).each do |r|
      association = FactoryBot.create(r.class_name.underscore)
      attributes[:"#{r.name}_id"] = association.id
      attributes[:"#{r.name}_type"] = association.class.name if r.options[:polymorphic]
    end

    attributes
  end
end
```
