### ISSUE TITLE
Fixture_file_upload problems

### ISSUE THREAD

**Issue by davidpatrick** [thoughtbot/factory_bot#385]
The other day I was having no problems running fixture_file_upload in my factory.  Previously I just used a basic Factory.define but I wanted to get rid of the deprecated warnings.

So today I went to run my tests and I am getting the following errors:

```
undefined method 'fixture_file_upload' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_2:0x007fe6822f6e10>
undefined method `fixture_file_upload' for #<FactoryGirl::SyntaxRunner:0x007fe6827c2188>
```

The code looks like this

```
FactoryGirl.define do
    factory :mongo_document do 
      original_filename "test.jpg"
      file {fixture_file_upload(Rails.root.to_s + '/spec/fixtures/files/test.jpg', 'img/jpeg')}
  end
end
```

I have even tried putting in
# spec_helper / test_helper

include ActionController::TestProcess

No luck.  What am I missing?

**Comment by pjg** [comment]
Don't include ActionDispatch::TestProcess. It has some (nasty consequences)[https://github.com/honeybadger-io/honeybadger-ruby/blob/a18b1c3c4d912f96f1a3cb1435cc8a50e436f7f5/lib/honeybadger/notice.rb#L487]

Proper solution is to use `Rack::Test::UploadedFile` directly in the factory (what `fixture_file_upload` essentially does anyway):

```ruby
file { Rack::Test::UploadedFile.new('spec/factories/test.png', 'image/png') }
```

**Comment by josephbhunt** [comment]
@pjg I've been trying to use `Rack::Test::UploadedFile`, but I get an error `REXML::UndefinedNamespaceException: Undefined prefix Rack::Test: found`. Do I need to require a file or include a module to make this work?

**Comment by pjg** [comment]
@josephbhunt Judging by the `REXML::UndefinedNamespaceException` exception it looks like you're in the wrong context when you execute this `file` helper (do you have it in the factory definition?). As a workaround you might try to prefix `Rack` with `::` so that it references top-level namespace and becomes `::Rack::Test::UploadedFile`.
