### ISSUE TITLE
build & build_stubbed skip "before_validation" calls?

### ISSUE THREAD

**Issue by brycesenz** [thoughtbot/factory_bot#483]
I am using FactoryGirl to test a model that is being extended with a Concern.  A simplified version is below:

```
module SampleConcern
  extend ActiveSupport::Concern

  included do
    include ActiveModel::Validations
  end

  module ClassMethods
    def has_before_validations
      before_validation :strip_username_whitespace
      before_validation :strip_email_whitespace
    end
  end
  ...
end

class SampleUser < ActiveRecord::Base
  include ActiveModel::Validations
  include SampleConcern
  has_before_validations

  attr_accessible :username, :email
  ...
end
```

If I create a SampleUser with factory girl create, then the before_validation hooks in the concern are run.  If I use 'build' or 'build_stubbed' though, then my before_validation hooks are somehow being skipped.  Is that desired behavior?  I couldn't find it in the documentation.

**Comment by quinHD** [comment]
Thanks joshuaclayton! Your explanation is great. It was very useful for me
