### ISSUE TITLE
Is it possible to pass an argument into a trait?

### ISSUE THREAD

**Issue by chintanparikh** [thoughtbot/factory_bot#527]
I'm trying to do something like this:

`FactoryGirl.create(:referral, :with_sent_referrals => 10)`

So the argument 10 would be passed onto the trait :with_sent_referrals.

Is this possible? And if not, could anyone guide me on how to get started monkey patching factorygirl to do it?

**Comment by danuker** [comment]
DEPRECATION WARNING: `#ignore` is deprecated and will be removed in 5.0. Please use `#transient` instead.
