### ISSUE TITLE
Memory Leak in FactoryGirl::Declaration::Implicit ?

### ISSUE THREAD

**Issue by tehprofessor** [thoughtbot/factory_bot#542]
Howdy,

Recently, we (my team) were attempting to deploy a migration where we had to modify existing records of our database by adding an association if it was empty (e.g. User's have profiles, but existing user's did not so we wanted to add them).

``` ruby
User.find_each(&:add_profile)
```

Mysteriously, the migration would always fail after consuming all available RAM on the machine. We could see it growing in nearly perfectly linear fashion in New Relic.

![factory-girl-in-gemfile](https://f.cloud.github.com/assets/995086/785303/7e0c10d0-ea7a-11e2-8c23-eb2e2bc226e6.png)

Completely confused by why this was going on, I decided to take data points from the ObjectSpace over time... So every 500 users, I'd `binding.pry` and take the data points.  After about 30,000 users, I decided it was time to graph 'em and see if I could find something... Low and behold:

![objectspace](https://f.cloud.github.com/assets/995086/785308/d5abbd4a-ea7a-11e2-8932-362b337da933.png)

I was rather shocked since none of the code even touched FactoryGirl, I grepped our entire app/ directory and found nothing. We use FactoryGirl to seed from time to time in production, and for testing... With this migration we aren't seeding; so, I decided I should try commenting it out from our Gemfile and re-run the migration.

![sans-factory-girl-in-gemfile](https://f.cloud.github.com/assets/995086/785423/fb337bc6-ea7e-11e2-8cdd-802e3fc1f576.png)

Fixed... well from my perspective

Things to note:

I did attempt to force GC at various intervals of user's processed (100, 500, and even 1) with something like:

``` ruby
i = 0
User.find_each do |u|
  u.add_profile
  GC.start if (i % 100) == 0
end
```

I am using: 

```
Ruby 2.0.0-p0 
factory_girl 4.2.0
factory_girl_rails 4.2.1
rails 3.2.13
Deiban 7.0 (Wheezy)
```

I did look at `FactoryGirl::Declaration::Implicit` but nothing stood out to me as a reason why this would be going on. So I figured I'd at least let you all know; maybe you'll have some clues? Also, if you all have no clues, don't worry-- it may be something specific to our app that's causing it. 

Best,
Seve

**Comment by daniel-rikowski** [comment]
@jleven Thank you for sharing this. I had a similar problem with thousands of leaked `FactoryGirl::Declaration::Implicit` instances in a delayed_job worker. Adding `class` to the list effectively fixed that.

I also didn't notice any problem using FactoryGirl, so I agree this should really be added to the offical code, even if it was not the root cause of @tehprofessor's problem.
