### ISSUE TITLE
FactoryGirl with Mongoid: Not generate id when id is rewrite.

### ISSUE THREAD

**Issue by jamesrxian** [thoughtbot/factory_bot#544]
Hi, I've been using FactoryGirl with Mongoid, it seems that FactoryGirl does not generate proper id for a document when the id field is rewrite using another field.

e.g, I have a User model

``` ruby
class User
  include Mongoid::Document
  field :num, type: String
  field :_id, type: String, default: ->{ num }
end
```

and factory

``` ruby
FactoryGirl.define do
  factory :user do
    sequence(:num) { |n| "0000#{n}" }
  end
end
```

when I call FactoryGirl.create(:user), then I get a document with id of nil.

so what''s happening?

I'm using Mongoid from the master branch(06b708d37cdebdc50b69614e9ff84dd953993a12) and Rails 4.0.0 and FactoryGirl 4.2.0

**Comment by chrishough** [comment]
Just ran into the same issue in Mongoid, thank you so much for posting this. Cheers 😸
