### ISSUE TITLE
Problems with factory_girl and has_many / belongs_to associations

### ISSUE THREAD

**Issue by appplemac** [thoughtbot/factory_bot#549]
Good morning everyone,
Yesterday I started to use factory_girl with Rails. My setup features two classes with has_many / belongs_to relation between them. I literally followed the instructions for the has_many case [here](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md). My current code features this:

``` ruby
class User < ActiveRecord::Base
  has_many :assistants, dependent: :destroy
end

class Assistant < ActiveRecord::Base
  belongs_to :user
end

FactoryGirl.define do
  factory :assistant do
    name { Faker::Name.name }
    user
  end

  factory :user do
    name { Faker::Name.name }
    email { Faker::Internet.email }

    factory :user_with_assistants do
      ignore do
        assistants_count 5
      end

      after(:create) do |user, evaluator|
        FactoryGirl.create_list(:assistant, evaluator.assistants_count, user: user)
      end
    end
  end
end
```

My current problem is that the same kind of expression you use in the example does not work for me in the same way:

``` ruby
# I get this:
FactoryGirl.create(:user_with_assistants).assistants.length # => 0
```

I tried to dig a bit further and discovered the following:

``` ruby
# In Rails console
user = FactoryGirl.create(:user_with_assistants)
user.assistants.length # => 0
Assistant.where(user_id: user.id).all.length # => 5
```

As you can see, the list of assistants gets created correctly, but it is not available through the ActiveRecord association, and I need it to be available through the association to be able to test the relation between my two classes.

Obviously, I checked if the association works at all, and it does:

``` ruby
user = User.create(name: "Jony Ive", email: "jive@apple.com")
user.assistants.create(name: "Design Intern")
user.assistants.length # => 1
```

I will be very very thankful for any hints on what I am doing wrong.

**Comment by mrgordon** [comment]
+1, this is really annoying

**Comment by rguerrettaz** [comment]
+1

**Comment by DonGiulio** [comment]
+1

**Comment by Sanmoo** [comment]
+1

**Comment by rloomba** [comment]
+1

**Comment by craigweston** [comment]
+1

**Comment by hosseintoussi** [comment]
+1

**Comment by Tensho** [comment]
+1

**Comment by bluehallu** [comment]
+1

**Comment by thenashfactor** [comment]
+1

**Comment by levlaz** [comment]
+1

**Comment by chaadow** [comment]
+1

**Comment by fcarrega** [comment]
:+1:

**Comment by darryn02** [comment]
+1

**Comment by ericsteen** [comment]
+1

**Comment by Schwad** [comment]
+1

**Comment by mark-kolodkin** [comment]
+1

**Comment by joshuaclayton** [comment]
Looks like there's a lot of interest here; does someone have a proposal as to how to do this?

A couple things to consider:

1. Not everyone is using ActiveRecord, so there's not guarantee `{Thing}#reload` is the correct method to call
2. Associated records could be created with FG directly (e.g. with `create_list` like in the example above) or with a service object/test harness

Perhaps a callback where people could call whatever they want at the very end of object creation?

**Comment by Andjeliko** [comment]
+1

**Comment by bluehallu** [comment]
Honestly, I feel like populating has_many relationships with an after(:create) hook is inherently flawed and the culprit for this behaviour.

**Comment by chrishough** [comment]
+1 http://stackoverflow.com/questions/35950470/rails-factorygirl-trait-association-with-model-after-create-callback-not-setting

**Comment by chrishough** [comment]
When I try to run model.reload I am not seeing a change in my callbacks

**Comment by dan-corneanu** [comment]
What is the status of this issue? Was it fixed?
According to the documentation, using create_list in after(:create) should properly update both ends of the has_many relation. However, using factory_girl (4.5.0) I can still experience the issue.

**Comment by tfluehmann** [comment]
same same in 4.7 😕

**Comment by alnet82** [comment]
If current object runs save validations that depend on the relationship with its `has_many` objects, the workaround of calling `reload` in `after(:create)` won't work.

**Comment by poc7667** [comment]
This is annoying!!!! sucks feature

**Comment by darrenterhune** [comment]
What about traits? Not sure on the internals of this vs the factory method, or how it differs, but we use this quite a bit:

``` ruby
FactoryGirl.define do
  factory :assistant do
    name { Faker::Name.name }
    user
  end

  factory :user do
    name { Faker::Name.name }
    email { Faker::Internet.email }

    trait :with_assistants do
      ignore do
        assistants_count 5
      end

      after(:create) do |user, evaluator|
        FactoryGirl.create_list(:assistant, evaluator.assistants_count, user: user)
      end
    end
  end
end

user = FactoryGirl.create(:user, :with_assistants, assistants_count: 3)
user.assistants.count
```

**Comment by ethagnawl** [comment]
I'm hesitant to add noise here, but I just wasted ~1 hour because of this issue. Perhaps, if nothing is done on the library side, the associations documentation could have a note added that mentions this behavior.

**Comment by Cremz** [comment]
2019 and still running into this issue. it only took me 5 mins to realise it's because the association wasn't reloading..but would be really nice to come up with a solution. 
I create a model at the beginning of my tests and then i keep adding associated models to it to test different scenarios, and it's really unfeasible to keep doing the reload

**Comment by alex-benoit** [comment]
+1

**Comment by krim** [comment]
up!

**Comment by dsusviela** [comment]
I think it gets real bad when your `User` model has the following validation: `validates :assistant, presence: true`. Basically you can't do `after(:create)` because the creation failed in the first place (there's no related assistant).

I don't think you can even build both objects before saving them to circumvent this. AFAIK the parent must be saved before the other object in the relationship can be built [as explained here](https://github.com/thoughtbot/factory_bot/issues/649).

Unless I'm understanding something wrong if your users must have at least one assistant there seems to be no way out of this.
