### ISSUE TITLE
Add possibility to include helper methods into FactoryGirl to be able to use them on factory definition

### ISSUE THREAD

**Issue by pkuczynski** [thoughtbot/factory_bot#564]
I have a `spec/my_helper.rb` in a form of:

``` ruby
module MyHelper
  def my_method
    ...
  end
end
```

I would like to use this method both in RSpec and during factory definition:

``` ruby
FactoryGirl.define do
  factory :my_factory do
    ...
    my_value: { my_method }
    ...
  end
end
```

Unfortunately this is not possible or I don't know how to do that? RSpec provides very nice way of including helpers in `spec_helper.rb`:

``` ruby
require 'my_helper'

RSpec.configure do |config|
   ...
   config.include MyHelper
   ...
end
```

Would it be possible to add something similar to FactoryGirl?

**Comment by fuzzyalej** [comment]
What's the status of this?

**Comment by git-toni** [comment]
+1! Although the proposed approaches do work :)

**Comment by arnlen** [comment]
Up!
Is the proposed solution still the only one available?
Any plan to include a more "native" way to be able to require helper methods inside factories?

**Comment by arthwood** [comment]
What I did is I extended `FactoryGirl::Syntax::Methods` module that I include in RSpec anyway:

In support/factory_girl.rb:
```ruby
require_relative 'helpers/factory_girl'

RSpec.configure do |config|
  config.include FactoryGirl::Syntax::Methods
  # ...
end
```

In support/helpers/factory_girl.rb:
```ruby
module FactoryGirl
  module Syntax
    module Methods
      def my_helper_method
        # ...
      end
    end
  end
end
```

**Comment by geekazoid** [comment]
Similar to what the OP asked for, I wanted to create a helper function that automatically creates `traits` for each possible value of an `enum` of a class. 

The module I wrote is 
```
module FactoryGirl
  module DeclarationHelpers
    #
    # This helper converts an enum to traits that represent each possible value
    # Suppose the following case:
    #
    # Example:
    #
    #   class Foo
    #     enum status: [:a, :b, :c]
    #   end
    #
    #   factory :foo do
    #     traits_for :status
    #   end
    #
    #  This is the same as doing
    #
    #   factory :foo do
    #     trait :a do
    #       status "a"
    #     end
    #
    #     trait :b do
    #       status "b"
    #     end
    #
    #     trait :c do
    #       status "c"
    #     end
    #   end
    #
    # obs: klass was the only form I found to infer the proper class

    def traits_for(klass, *enum_names)
      enum_names.each do |enum_name|
        pluralized_name = enum_name.to_s.pluralize

        # Ok, it says 'keys' but they are the possible values of the enum
        values = klass.send(pluralized_name).keys

        values.each do |value|
          trait value.to_sym do
            send(enum_name, value)
          end
        end
      end
    end
  end
end
```

I figure that is different from what the OP and following posters wanted to do. I tried to do the `include` in `FactoryGirl::SyntaxRunner` with no success, as well as many other hacky things (trying to `include` it into `FactoryGirl::Declaration` and other nasty stuff).

In spite of not being totaly DRY and nice, I came up with this solution

```
require_relative '../support/declaration_helpers'

FactoryGirl.define do
  factory :mymodel do
    extend FactoryGirl::DeclarationHelpers

    # Some attributes here

    traits_for Animal, :status, :classification, :kind
  end
end
```
Is there any other possibility instead of extending it in every factory?

**Comment by oniksfly** [comment]
@finiteautomata thank you for your solution. BTW you have ability to declare after/before blocks in such helper methods.

**Comment by itay-grudev** [comment]
How about simply:

```ruby
# spec/factories.rb
include SomeHelper

FactoryGirl.define do
  # ...
end
```

This allowed me to reuse Rails Helpers in factories.

**Comment by arthwood** [comment]
@itay-grudev but that would allow you to use helper methods only in the file where it is included, whereas extending `FactoryGirl::Syntax::Methods` gives you access to helper methods in all factories (and test examples) without explicit inclusion.

**Comment by itay-grudev** [comment]
@arthwood That's true, but it would also pollute the namespace which usually is not a good thing. Also tests tend to be specific so you would only need to include the relevant helpers.

P.S. Nice telescope. I was working on 50/70cm one two nights ago.

**Comment by nomasprime** [comment]
Has there been any progress?

Would like to be able to use `file_fixture`.

**Comment by mxdavis** [comment]
Same here :)

**Comment by Haegin** [comment]
I was also trying to use `file_fixture` inside a factory for testing purposes. To get my test working with ActiveStorage I ended up using the following to open the test file and read it in to a `Tempfile` (needed so ActiveStorage can call `#open` on the instance, which is a private method on `File`.

```ruby
trait :with_attachment do
  attachments do
    file = Tempfile.new("attachment")
    file.write(File.read(Rails.root.join("spec", "data", "test_attachment.txt")))
    [
      ActionDispatch::Http::UploadedFile.new(
        filename: "test_attachment.txt",
        type: "text/plain",
        tempfile: file,
      )
    ]
  end
end
```

**Comment by ReganRyanNZ** [comment]
Similar to an existing comment, here's my hack:

```ruby
module FactoryBotEnhancements
  def change_factory_to_find_or_create
    # Note that this will ignore nil value attributes, to avoid auto-generated attributes such as id and timestamps
    to_create do |instance|
      attributes = instance.class.find_or_create_by(instance.attributes.compact).attributes
      instance.attributes = attributes.except('id')
      instance.id = attributes['id'] # id can't be mass-assigned
      instance.instance_variable_set('@new_record', false) # marks record as persisted
    end
  end
end

FactoryBot.define do
  factory :my_factory do
    extend FactoryBotEnhancements
    change_factory_to_find_or_create

    label { "Relationship" }
  end
end

FactoryBot.create(:my_factory) # creates
FactoryBot.create(:my_factory) # finds
```

The annoying thing is needing two lines to do one thing. Is there a way to make a method be called when the module is extended?

**Comment by henry-p** [comment]
@ReganRyanNZ

> The annoying thing is needing two lines to do one thing. Is there a way to make a method be called when the module is extended?

```ruby
# spec/factories/support/elasticsearch_factory_helper.rb
module MyFactoryHelper
  def self.extended(base)
    base.to_create do |instance|
      # stuff
    end
  end
end

# config/initializers/factory_bot.rb
Dir[Rails.root.join("spec", "factories", "support", "**", "*.rb")].sort.each { |f| require f }

# spec/factories/location.rb
FactoryBot.define do
  factory :location do
    extend MyFactoryHelper

    stuff {}
  end
end
```
