### ISSUE TITLE
Allow return values from 'to_create'

### ISSUE THREAD

**Issue by jneander** [thoughtbot/factory_bot#565]
From my understanding, the return value from a factory's 'to_create' method is ignored. This approach supports the model-centric idea of persisting an object by calling 'save' on an instance of the object, updating it in-place. With regard to FactoryGirl, this means that the object returned from the 'build' or 'initialize_with' portion of the factory is the object ultimately returned when calling 'create' within a test.

For a user designing with the Repository Pattern (or a variant), persisting an object may not work in the same model-centric way. The Repository 'save' method may not modify the given object, but instead return a new object representing the persisted form of the original.

FactoryGirl does not currently support this idea. The instance returned from the 'build' block is returned from the factory, and not the instance created in the 'to_create' block. This means that the "unpersisted" form of the object is returned, not the object with updated attributes (e.g. 'id') from the 'save' action.

Is there an opportunity to allow a return value from 'to_create'?

```
class Foo
  attr_accessor :id, :name
  ...
end

class FooRepository
  def self.create(name)
    Foo.new(name) # this object is not yet persisted and has no .id
  end

  def self.save(foo)
    # this method must not guarantee that the original Foo instance
    # will always be returned
    ...
    updated_foo # this is a duplicate of the original object
  end

  ...
end

FactoryGirl.define do
  factory :foo, class: FooRepository do
    # create an example Foo
    initialize_with { FooRepository.create(name: "Example") }
    # save the Foo to the datastore, returning what may be a duplicate
    to_create {|instance| FooRepository.save(instance)}
  end
end

describe FooRepository do
  it "saves the given Foo to the datastore" do
    foo = create(:foo)
    foo.id #=> nil
    ...
  end
end
```

**Comment by Bajena** [comment]
I'm currently using FactoryBot with Hanami's repositories and  when I replace original `:create` strategy with @joshuaclayton's snippet it works perfectly with one minor issue - if you need to run `after_create` callbacks then you most probably want to replace:
```ruby
evaluation.notify(:after_create, instance)
```

with:
```ruby
evaluation.notify(:after_create, result)
```

otherwise `after_create` callback will be using the original instance.

P.S. For anyone interested. My factory looks like this:
```ruby
FactoryBot.define do
  factory :word_list, class: WordList do
    name { "A list" }
    user_id { nil }

    trait :anonymous do
      user_id { nil }
    end

    trait :with_words do
      transient do
        word_count { 1 }
      end

      after(:create) do |list, evaluator|
        create_list(:word, evaluator.word_count, word_list_id: list.id)
      end
    end

    initialize_with do
      new(attributes)
    end

    to_create do |instance|
      WordListRepository.new.create(instance.to_h)
    end
  end
end
```
