### ISSUE TITLE
Factory girl and Postgres UUID attempts to insert NULL.

### ISSUE THREAD

**Issue by lethjakman** [thoughtbot/factory_bot#576]
Hey, I'm trying to use factory girl along with Postgres and a UUID PK in rails. It seems that when it attempts to create the object it inserts the PK as NULL rather than leaving it blank and causes Postgres' NOT NULL constraint to throw an error. Here is a gist I've created with all the information I think you'll need on the issue. Would you have any idea of how to fix this? Thank you for your time! https://gist.github.com/lethjakman/7292445

**Comment by cesc1989** [comment]
> I didn't have time to actually look at it, but I got myself up and running like this:
> 
> id { SecureRandom.uuid }

Thanks for your suggestion. Works even today 😂
