### ISSUE TITLE
Forced creating of an invalid record

### ISSUE THREAD

**Issue by shaggyone** [thoughtbot/factory_bot#578]
Hello, is there any standart way to create an invalid record using factory girl.

First thing, of course is to use:
let(:var) { FactoryGirl.build :factory_name, ... }
before { var.save(validate: false) }

But maybe there is some pretty looking syntax for using FactoryGirl.create ?

**Comment by servel333** [comment]
Does this work?

    factory :user do
      factory :user_skips_validate do
        to_create {|instance| instance.save(validate: false) }
      end
    end

    FactoryGirl.create(:user, username: "valid_username")
    FactoryGirl.create(:user_skips_validate, username: "invalid username -!@#$%^&*-=")

**Comment by waiting-for-dev** [comment]
Yeah, surely it works... but I usually like to have one factory per model, and just provide ways to have fined control over it through traits. But surely this is just my workflow and your proposal should be 100% acceptable. Thanks.

**Comment by thomassnielsen** [comment]
Using this technique inside traits seems to work.

```ruby
trait :pay do
  # Turn off validation so we can create order with pay status directly
  to_create {|instance| instance.save(validate: false) }
  status "pay"
end
```

**Comment by aldrienht** [comment]
what about forcing to save record, column_validation not in model.
`PG::NotNullViolation: ERROR:  null value in column "not_null_column_here" violates not-null constraint`

is it still possible?

**Comment by jferris** [comment]
@aldrienht You can't ignore or disable constraints in Postgres. If you really want to test with a `nil` value, you can use `build_stubbed` and mocks to simulate getting a `nil` result. However, given that it's impossible in your database, I can't think of why you'd want to model this in your tests.

**Comment by TorvaldsDB** [comment]
```ruby
trait :skip_validate do
  to_create {|instance| instance.save(validate: false) }
end
```
