### ISSUE TITLE
how to use traits to append values to a postgres array type?

### ISSUE THREAD

**Issue by odigity** [thoughtbot/factory_bot#582]
First time using new PG features in Rails 4.0  I have an Announce model with a channel field defined as array of strings, so you could put an announcement in two "channels" (panels on a website) and have them show up in both places.

```
create_table :announcements do |t|
  t.string      :title, null: false
  t.text        :body, null: false
  t.datetime    :published_at
  t.string      :channels, array: true, null: false, default: []
  t.timestamps

  t.index       :channels
end
```

I created a factory that uses traits to let me populate the field:

```
FactoryGirl.define do
  factory :announcement do
    trait :published do
      published_at { Time.now.ago(rand(1.year)) }
    end

    trait :main do
      channels { channels + ['main'] }
    end

    trait :tech do
      channels { channels + ['tech'] }
    end

    title { Faker::Lorem.words(6).join(' ').titleize }
    body  { Faker::Lorem.paragraphs(3).join("\n\n") }
  end
end
```

When I try to use them:

```
before :each do
  @main    = create(:announcement, :main, :published)
  @tech    = create(:announcement, :tech)
  @general = create(:announcement, :main, :tech, :published)
end
```

I get the following error:

 1) Announcement scopes .published returns only published announcements
     Failure/Error: Unable to find matching line from backtrace
     SystemStackError:
       stack level too deep
     # /home/ofer/.rvm/gems/ruby-2.0.0-p247/gems/factory_girl-4.3.0/lib/factory_girl/attribute/dynamic.rb:14

Clearly, I'm doing it wrong, resulting in infinite recursion when trying to append to the channels value in the block.

So... what's the right way?

**Comment by gkop** [comment]
How about building up an abstract transient array via traits, is this possible yet?
