### ISSUE TITLE
after_create callbacks

### ISSUE THREAD

**Issue by pathouse** [thoughtbot/factory_bot#585]
Hey spent quite a bit of time trying to figure out some test failures last week and ended up narrowing it down to the way that factory girl handles after_create callbacks. 

I expected these callbacks to work as they do in rails where they are a part of the db transaction. However, after looking at the code and your own specs for callbacks its become clear that factory girl's after_create callbacks as they exist now are not intended for directly updating the db and the object is not reloaded afterward. All tests of after_create callbacks test assignment, not db updates. 

Unless this is intentional or enforcing some kind of best-practice around after_create callbacks that I'm not aware of, it's a bug that could easily be fixed.

**Comment by chrishough** [comment]
Is this similar to this issue? http://stackoverflow.com/questions/35950470/rails-factorygirl-trait-association-with-model-after-create-callback-not-setting  I can not seem to figure out why my callbacks are not working...
