### ISSUE TITLE
Deprecate static attributes?

### ISSUE THREAD

**Issue by jferris** [thoughtbot/factory_bot#592]
Many of the questions on Stackoverflow and the former mailing list are because of confusion as to when you do and don't need to define your attributes using a block.

Using a block to define dynamic attributes will ALWAYS work, whereas static attributes only work when the value never changes.

Have we done recent benchmarks to determine the performance advantages of static attributes in a realistic test suite? If they aren't significant, I think it's worth deprecating static attributes to improve consistency and reduce confusion.

**Comment by odlp** [comment]
I think in general encouraging dynamic attributes by default is sensible. I wonder if we can evaluate the impact of this on test times with a realistic suite? (Perhaps Hub would be a good candidate).

If dynamic-attributes do become the default perhaps it might make sense to...

- Introduce a `#add_static_attribute` method (allowing an explicit choice by the dev) 
- Change [`#add_attribute`](https://github.com/thoughtbot/factory_girl/blob/8a65569f102ac2593e7c73bd029d5072e4641af8/lib/factory_girl/definition_proxy.rb) to only accept a block.

**Comment by odlp** [comment]
PR adding deprecation notice: #1135

**Comment by composerinteralia** [comment]
I just merged the PR to deprecate static attributes (#1135). To make this as painless as possible, @seanpdoyle and I worked on a [rubocop-rspec Cop](https://github.com/rubocop-hq/rubocop-rspec/pull/666) that can automatically update static to dynamic attributes.

As the next release goes out I will write up a blog post to cover why I think the deprecation was necessary.
