### ISSUE TITLE
Unsatisfied dependency on DatabaseCleaner, breaks Rails apps.

### ISSUE THREAD

**Issue by edelgado** [thoughtbot/factory_bot#644]
If you follow the "Linting Factories" instructions in your [GETTING_STARTED.md](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#linting-factories) file, a Rails application will break with this error message:

`uninitialized constant DatabaseCleaner (NameError)`

This is because `DatabaseCleaner` is class defined in the `database_cleaner` gem. This dependency is currently unsatisfied by the `factory_girl` and `factory_girl_rails` gems.

Seems like the gemspecs need to be updated.

**Comment by jaykilleen** [comment]
Same here. I just ran into this issue and then googled it and found this page. Yay that for #645.
