### ISSUE TITLE
Factory for model with `enum` not generating correct data

### ISSUE THREAD

**Issue by koenpunt** [thoughtbot/factory_bot#656]
My application has Dossiers which can contain multiple Items:

My setup

``` ruby
# Item class using ActiveRecord::Enum
class Item < ActiveRecord::Base
  enum item_type: %w(file link)
end

# Simplified factory for dossier
FactoryGirl.define do
  factory :dossier do
    sequence(:title) {|n| "Dossier title #{n}" }
    sequence(:description) {|n| "Dossier description #{n}" }
  end
end

# Simplified factory for item
FactoryGirl.define do
  factory :item do
    sequence(:title) {|n| "Item title #{n}" }
    sequence(:description) {|n| "Item description #{n}" }
    item_type { Item.item_types.keys.sample }
  end
end
```

My tests looks like the following:

``` ruby
feature 'Can view dossier' do
  scenario 'with items' do
    dossier = create :dossier
    3.times do
      item = create(:item)
      dossier.items << item
      # here item's `item_type` is still an integer and the method returns a string; "file" or "link"
      # but when accessing `item` through `dossier`; `item_type` is string of "0" or "1" and the method returns `nil`.
    end
    visit dossier_path(dossier)
  end
end
```

As described in the comment above the attribute type of `item_type` changes from integer to string when added to the association.

I'm guessing that it has something to do with the fact that the result of the enum is a string, but the column type is an integer.

I'll try to setup a test case for this and submit a PR.

**Comment by emmanuelmillionaer** [comment]
@koenpunt , @rohitpaulk , @joshuaclayton  for me the tests in:

https://github.com/thoughtbot/factory_girl/commit/33d3c063aa1b84fb8f0ef362f8047c58c39d3016

Fail. After I copied them into my Rails project into `spec/models/enum_spec.rb`
What do I wrong? Can this be because I'm using `gem "factory_girl_rails", "~> 4.5.0"` there?

Thanks!

**Comment by antifun** [comment]
I offer the following breadcrumb in the hope that some other poor soul does not spend an entire day chasing down this ghost, as I just did:

*rake db:test:prepare*

If you did what I did, you had a development database up to date with an enum *and* a migration, but were running specs against a test database with the enum specified but *no* column to back it. In this case, Rails/factory_girl will happily infer that the type of the attribute is a string, and the enum logic will happily convert its values to an integer, but they will not be returned as such, and consequently you'll always get `nil` for your enum value no matter what, or how, you set it (to).

**Comment by chenyunli6** [comment]
像 @antifun 所说的，test 环境下的 migrate 有问题，可以试着 rollback 然后再 migrate 一次看看。

**Comment by ColinLeefwz** [comment]
> 像 @antifun 所说的，test 环境下的 migrate 有问题，可以试着 rollback 然后再 migrate 一次看看。

用中文回复美国人？虽然我看comments也只看代码。

**Comment by johnpitchko** [comment]
> I offer the following breadcrumb in the hope that some other poor soul does not spend an entire day chasing down this ghost, as I just did:
> 
> _rake db:test:prepare_
> 
> If you did what I did, you had a development database up to date with an enum _and_ a migration, but were running specs against a test database with the enum specified but _no_ column to back it. In this case, Rails/factory_girl will happily infer that the type of the attribute is a string, and the enum logic will happily convert its values to an integer, but they will not be returned as such, and consequently you'll always get `nil` for your enum value no matter what, or how, you set it (to).

Facing this issue in 2021 :D Thanks for the solution @antifun !

**Comment by douglas** [comment]
> > I offer the following breadcrumb in the hope that some other poor soul does not spend an entire day chasing down this ghost, as I just did:
> > _rake db:test:prepare_
> > If you did what I did, you had a development database up to date with an enum _and_ a migration, but were running specs against a test database with the enum specified but _no_ column to back it. In this case, Rails/factory_girl will happily infer that the type of the attribute is a string, and the enum logic will happily convert its values to an integer, but they will not be returned as such, and consequently you'll always get `nil` for your enum value no matter what, or how, you set it (to).
> 
> Facing this issue in 2021 :D Thanks for the solution @antifun !

Just faced this issue in 2024 :D Thanks a lot, @antifun ❤️
