### ISSUE TITLE
How to make factories using existing associated entities by default

### ISSUE THREAD

**Issue by snoblenet** [thoughtbot/factory_bot#679]
Say a factory looks like this:

```
factory :post do
  # ...
  author
end
```

Then `create(:post)` creates a post, creates an author, and assigns the post to the author.

And `create(:post, :author => @author)` creates a post and assigns it to the existing @author.

But let's there is already an author. Is there a way to have `create(:post)` automatically assign the post to that author instead of creating a new one?

The reason I ask is for the sake of brevity as at present many of my specs looks like this:

```
@model1 = create(:model1)
@model2 = create(:model2)
@model3 = create(:model3)

@modela = create(:modela, :model1 => @model1, :model2 => @model2, :model3 => @model3)
@modelb = create(:modelb, :model1 => @model1, :model2 => @model2, :model3 => @model3)
@modelc = create(:modelc, :model1 => @model1, :model2 => @model2, :model3 => @model3)
```

The following would be better:

```
@modela = create(:modela)
@modelb = create(:modelb)
@modelc = create(:modelc)
```

**Comment by mockdeep** [comment]
FWIW, I came across this issue and wanted to share the approach I'm poking around with. The vast majority of my factories would typically be associated with the same user, so I want to have a cached user to use by default across all of them unless I specify otherwise. Here's what I came up with:

```rb
module FactoryCache
  def self.user
    @user ||= FactoryBot.create(:user)
  end

  def self.reset
    @user = nil
  end
end

RSpec.configure do |config|
  config.include(FactoryBot::Syntax::Methods)

  config.after { FactoryCache.reset }
end

module FactoryBot
  module Syntax
    module Methods
      def default_user
        FactoryCache.user
      end
    end
  end
end
```

Then in factories we can use it:

```rb
FactoryBot.define do
  factory(:check) do
    user { default_user }
  end
end
```

Likewise, in tests we can use `default_user` to whatever end:

```rb
before { sign_in(default_user) }
```
