### ISSUE TITLE
Attributes for factories associations

### ISSUE THREAD

**Issue by douglascamata** [thoughtbot/factory_bot#693]
I got this example factory: 

``` ruby
FactoryGirl.define do 
  factory :foo do
    bar
  end

  factory :bar do
  end
end
```

And in my specs I needed to set specific attributes for the `bar` object inside each `foo` I was creating and it's really boring. The solution was something like:

``` ruby
bar1 = create :bar, attribute: value
bar2 = create :bar, attribute: value

foo1 = create :foo, bar: bar1
foo2 = create :foo, bar: bar2
```

Maybe you (or we) could improve this to something like:

``` ruby
foo1 = create :foo, bar: { attribute: value1 }
foo2 = create :foo, bar: { attribute: value2 }
```

Of course, nesting more levels should be possible.

**Comment by boardfish** [comment]
[This](https://makandracards.com/makandra/32679-factorybot-passing-attributes-to-associated-records-using-transient-attributes) still holds up, and you could take it further by having a transient attribute that's a hash and spreading it:

```
    factory :parent do
      transient do
        child_attributes { { sensible_default: 'can be specified here' } }
      end

      association :child, **child_attributes
    end
```

However, it doesn't give you the usual FactoryBot freedom of changing one attribute (from the default) at a time. So I think there's still a need for this if it doesn't exist already.

**Comment by jdufresne** [comment]
FWIW, this feature is built into [factory_boy](https://github.com/FactoryBoy/factory_boy) which was originally inspired by factory_bot. Coming from Python, I miss this feature. That project uses a double underscore syntax to traverse factory relationships, but the general concept is there.

Here is an example from the docs:

https://factoryboy.readthedocs.io/en/stable/reference.html#calling

> Fields of the `SubFactory` may be overridden from the external factory:

```py
>>> c = CompanyFactory(owner__first_name='Henry')
c.owner
<User: Henry Doe>
```

This would be handy for [dependent attributes](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#dependent-attributes) in the association's factory.
