### ISSUE TITLE
`FactoryGirl.lint` behavior differs from documentation

### ISSUE THREAD

**Issue by fishermand46** [thoughtbot/factory_bot#726]
The documentation for the `FactoryGirl.lint` method suggests that you can run it on any model which defines a `valid?` method ([link](https://github.com/thoughtbot/factory_girl/blame/v4.5.0/GETTING_STARTED.md#L78-L82)).

However, the [linting code](https://github.com/thoughtbot/factory_girl/blob/v4.5.0/lib/factory_girl/linter.rb#L25) calls `FactoryGirl.create` which assumes the model defines a `save` method as well.

The reason this is a problem is that I am using factory_girl to create models which are not persisted, but still have validations.

**Comment by dcarral** [comment]
@jswoods @mbasset Should we document it? It seems like it's the way to go for use cases like factories for embedded documents @ _Mongo_.

@joshuaclayton After reading this thread I'm interested in checking what are those reasons and if they still apply as they did back then. In my opinion, using `#valid?` (of course, if the effort is worth it) should be the way to lint. Added to the personal TODO ;)
