### ISSUE TITLE
Factory girl breaks test migrations

### ISSUE THREAD

**Issue by retospect** [thoughtbot/factory_bot#88]
Factory girl sometimes breaks migrations in the test environment.
I found it's necessary to avoid the default naming scheme (spec/factories.rb etc), and add a "require 'spec/xfactory.rb'"line at the end of spec_helper.rb. 

Otherwise, the migrations do not take place when I run rake db:test:prepare.

**Comment by kingofwhales** [comment]
@jferris  Hi can you explain a little bit why using string references here will magically make the migrations error go away?  THANKS A TON
