### ISSUE TITLE
initialize_with for create_list

### ISSUE THREAD

**Issue by dkniffin** [thoughtbot/factory_bot#956]
I'm looking for a way to customize the way lists of objects are created. For example, if I want to create 5 objects, and I have a service class called `SomeService` that will create `n` of those objects, how would I override the create_list functionality to call that service?

There's intitialize_with, which works for creating a single item in a custom way:

``` ruby
FactoryGirl.define do
  factory :some_custom_object, class: String do
    skip_create

    initialize_with do
       new('blah')
    end
  end
end
```

But that doesn't allow me to bulk-create a bunch Here's an example of what I'm trying to do:

``` ruby
FactoryGirl.define do
  factory :some_custom_object, class: String do
    skip_create

    initialize_with_for_create_list do
       SomeService.run('blah', n)
    end
  end
end
```

Sorry if something like this already exists. I searched around and couldn't find anything.

**Comment by composerinteralia** [comment]
I know it has been a while, but I don't believe anything like this exists. Just out of curiosity, it you already have a service for creating lists of objects, why do you need to use `create_list`?

**Comment by dkniffin** [comment]
@composerinteralia Great question! It's been a while since I opened this, and I honestly don't even remember the initial use-case anymore. I'm going to go ahead and close this.
