### ISSUE TITLE
single-table inheritance error is not raised

### ISSUE THREAD

**Issue by Ana06** [thoughtbot/factory_bot#959]
When having the two following models:

``` Ruby
class Parent < ApplicationRecord
  validates :type, presence: true
end

class Child1 < Parent
end

class Child2 < Parent
end
```

If you try to create a parent with a type different from `"Child1"` and `"Child2"` (something like `Parent.create(type: "foo")`) it will raise the following error:

`ActiveRecord::SubclassNotFound: The single-table inheritance mechanism failed to locate the subclass: 'foo'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Parent.inheritance_column to use another column for that information.`

But if you create the following factory in Factory Girl **it does work**.

``` ruby
FactoryGirl.define do
  factory :parent do
    type "foo"
  end
end
```

It is that fine? It is an error in the database level so maybe FactoryGirl shouldn't raise an error and this is the expected behavior.

**Comment by tmikeschu** [comment]
@Ana06 I was able to duplicate this bug, for what it's worth!

Following the same setup:

<img width="1680" alt="screen shot 2017-04-19 at 2 41 15 pm" src="https://cloud.githubusercontent.com/assets/19894032/25201254/517cf0b6-250e-11e7-85b2-d8eafc3f2d88.png">

**Comment by joshuaclayton** [comment]
This looks to be a behavior specific to ActiveRecord.

I can reproduce this as such:

```ruby
    user = User.new
    user.type = "Admin"
    user.save!
    expect(user).to be_a(Admin)
```

This fails via vanilla AR (which is what FB uses behind the scenes).

Instead, I'd recommend declaring the class on the factory:

```ruby
    FactoryBot.define do
      factory :user, class: "Admin"

      factory :admin
    end
```
