### ISSUE TITLE
Linting behavior inconsistent between simple conditional validations and grouped conditional validations

### ISSUE THREAD

**Issue by gkop** [thoughtbot/factory_bot#963]
In Rails 4.2.7 and Factory Girl 4.7.0, the linter produces false positives when using grouped conditional validations.

Say we have a factory

```ruby
FactoryGirl.define do
  factory :user
end
```

When using ordinary conditional validations, the linter correctly finds no errors:

```ruby
class User < ActiveRecord::Base
  validates :name, presence: true, if: Proc.new { false }
end
```

However, using [grouped conditional validations](http://guides.rubyonrails.org/v4.2.7.1/active_record_validations.html#grouping-conditional-validations), the linter appears to ignore the conditional, thereby incorrectly marking the factory invalid:

```ruby
class User < ActiveRecord::Base
  with_options if: Proc.new { false } do |user|
    user.validates :name, presence: true
  end
end
```

The workaround I am using successfully is to use the simple conditional validations rather than the grouped validations.

**Comment by joshuaclayton** [comment]
@gkop strange - any ideas on how to replicate? If you do, please reopen this issue; I'm going to close this for now, as it seems unrelated to FB proper.
