### ISSUE TITLE
Abstract factory

### ISSUE THREAD

**Issue by axelson** [thoughtbot/factory_bot#985]
Is it possible to create an abstract factory? We want to use an abstract factory for the base class of an STI (Single Table Inheritance) model. But since the base class cannot be directly created in the database, currently our base factory cannot actually be instantiated. But we still want to use it as the base factory so that we can define the common elements (especially after build callbacks) there instead on the child factories. Is there a way to accomplish this in factory girl?

**Comment by koffeinfrei** [comment]
I guess the answer is no.

You could use a workaround like this:

```ruby
FactoryGirl.define do
  factory :base_class do

    transient do
      abstract_factory { raise "You can't instantiate this abstract factory." }
    end

    after(:build) do |runner, evaluator|
      evaluator.abstract_factory
    end

    factory :child_class do
      transient do
        abstract_factory false
      end
    end
  end
end

Alternatively you can prevent instantiating directly on the class itself, see http://stackoverflow.com/a/4834082/232838.

**Comment by pedroadame** [comment]
I think it would be a great feature, @axelson

**Comment by joshuaclayton** [comment]
@axelson In that situation, [transient attributes](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#transient-attributes) are a great way to solve this.

**Comment by joshuaclayton** [comment]
@tylerhunt another option for providing a base set of attributes - including callbacks and associations! - is [traits](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#traits).

**Comment by tylerhunt** [comment]
@joshuaclayton I didn't quite understand how this would be done at first, but after playing with it a bit, I guess it would be something like this?

```ruby
require 'faker'

FactoryBot.define do
  trait :user do
    name { Faker::Name.name }
    email { Faker::Internet.email }
    password { Faker::Internet.password }
  end

  factory :company_user, traits: %i(user) do
    company
  end

  factory :customer_user, traits: %i(user) do
    customer
  end
end
```

This seems to work. The only real downside I see to this approach is the pollution of the global namespace with what's effectively a private trait.

**Comment by artinboghosian** [comment]
@tylerhunt tried out this approach, the other downside is that if you had traits in your base sti parent factory, you will have to figure out a different way to handle that:

```
FactoryBot.define do
  factory :base_class do
    name { 'Hi' }
    trait :activated do
      activated_at { Time.current }
    end
  end

  factory :sub_class, parent: :base_class do
    type { 'Subclass' }
  end
end
```

Converting to use `trait :base_class`, you lose the `:activated` trait functionality.
