### ISSUE TITLE
AttributeAssigner ignores fields like :origin if another field :origin_id is present

### ISSUE THREAD

**Issue by AlexanderZaytsev** [thoughtbot/factory_bot#989]
So I have this factory:

```ruby
factory :product do
  origin { :amazon }
  origin_id { rand(100000).to_s }
end
```
If I create it like this then `origin` and `origin_id` are present:
```ruby
@product = create(:product)
```
But if I create it like this, then `origin` and `origin_id` are nil:
```ruby
@product = create(:product, origin: :amazon, origin_id: '1234')
```

I traced it down to `AttributeAssigner#alias_names_to_ignore` but I lack deep knowledge of the gem to  send a pull request.

**Comment by ento** [comment]
I've found these previous discussions helpful:

* https://github.com/thoughtbot/factory_girl/issues/734
  * mentions the workaround of marking either of the attributes as a transient and setting it manually in an `after` callback
* https://github.com/thoughtbot/factory_girl/issues/851
  * mentions the workaround of overwriting `FactoryGirl.aliases`

**Comment by composerinteralia** [comment]
Closing in favor of #1142
