### ISSUE TITLE
Add `did_you_mean` to "Trait not registered"

### ISSUE THREAD

**Issue by Dorian** [thoughtbot/factory_bot#992]
It would be nice to have:

```
     ArgumentError:
       Trait not registered: in_progess
       Did you mean? in_progress
```

Instead of:

```
     ArgumentError:
       Trait not registered: in_progess
```

**Comment by Thomascountz** [comment]
@joesasson and I looked into utilizing the [did_you_mean](https://github.com/yuki24/did_you_mean) gem to output spellcheck suggestions. We discovered the the gem is only invoked for `NameError`s and `NoMethodError`s, as opposed to in our case, handling `ArgumentError`s. 

We did discuss possibly changing the `ArgumentError` into a `NameError`, as a means to better express the exception being raised and in hopes that it may automatically invoke the spell checker, but were unable to test this. 

Another possibility would be to import the more abstract `SpellChecker` class inside the gem, however we reached a deadend. `did_you_mean` has been added to Ruby core as of [2.3](https://bugs.ruby-lang.org/issues/11252), and it seems inefficient to copy so much functionality out of Ruby to reimplement it for our use case.
